# Redis configuration
bind 0.0.0.0
protected-mode no
port 6379

# Load ACL file
aclfile /usr/local/etc/redis/users.acl

# Other standard configs
tcp-keepalive 300
timeout 0
databases 16
loglevel notice
