// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: message_api.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message
type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: json:"msg_id"
	MsgId string `protobuf:"bytes,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id"`
	// @gotags: json:"client_id"
	ClientId string `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id"`
	// @gotags: json:"conversation_id"
	ConversationId string `protobuf:"bytes,3,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id"`
	// @gotags: json:"from_user_id"
	FromUserId uint64 `protobuf:"varint,4,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id"`
	// @gotags: json:"msg_type"
	MsgType int32 `protobuf:"varint,5,opt,name=msg_type,json=msgType,proto3" json:"msg_type"`
	// @gotags: json:"seq"
	Seq uint64 `protobuf:"varint,6,opt,name=seq,proto3" json:"seq"`
	// @gotags: json:"content"
	Content string `protobuf:"bytes,7,opt,name=content,proto3" json:"content"`
	// @gotags: json:"media_url"
	MediaUrl string `protobuf:"bytes,8,opt,name=media_url,json=mediaUrl,proto3" json:"media_url"`
	// @gotags: json:"extra"
	Extra string `protobuf:"bytes,9,opt,name=extra,proto3" json:"extra"`
	// @gotags: json:"status"
	Status int32 `protobuf:"varint,10,opt,name=status,proto3" json:"status"`
	// @gotags: json:"create_time"
	CreateTime    int64 `protobuf:"varint,11,opt,name=create_time,json=createTime,proto3" json:"create_time"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_message_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_message_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_message_api_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *Message) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *Message) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *Message) GetFromUserId() uint64 {
	if x != nil {
		return x.FromUserId
	}
	return 0
}

func (x *Message) GetMsgType() int32 {
	if x != nil {
		return x.MsgType
	}
	return 0
}

func (x *Message) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetMediaUrl() string {
	if x != nil {
		return x.MediaUrl
	}
	return ""
}

func (x *Message) GetExtra() string {
	if x != nil {
		return x.Extra
	}
	return ""
}

func (x *Message) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Message) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

type Conversation struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ConversationId   string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	ConversationType int32                  `protobuf:"varint,2,opt,name=conversation_type,json=conversationType,proto3" json:"conversation_type,omitempty"`
	MaxSeq           int64                  `protobuf:"varint,3,opt,name=max_seq,json=maxSeq,proto3" json:"max_seq,omitempty"`
	CreateTime       int64                  `protobuf:"varint,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime       int64                  `protobuf:"varint,5,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Conversation) Reset() {
	*x = Conversation{}
	mi := &file_message_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Conversation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Conversation) ProtoMessage() {}

func (x *Conversation) ProtoReflect() protoreflect.Message {
	mi := &file_message_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Conversation.ProtoReflect.Descriptor instead.
func (*Conversation) Descriptor() ([]byte, []int) {
	return file_message_api_proto_rawDescGZIP(), []int{1}
}

func (x *Conversation) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *Conversation) GetConversationType() int32 {
	if x != nil {
		return x.ConversationType
	}
	return 0
}

func (x *Conversation) GetMaxSeq() int64 {
	if x != nil {
		return x.MaxSeq
	}
	return 0
}

func (x *Conversation) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *Conversation) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

// UserConversation
type UserConversation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: json:"user_id"
	UserId uint64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id"`
	// @gotags: json:"conversation_id"
	ConversationId string `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id"`
	// @gotags: json:"is_top"
	IsTop bool `protobuf:"varint,3,opt,name=is_top,json=isTop,proto3" json:"is_top"`
	// @gotags: json:"is_disturb"
	IsDisturb bool `protobuf:"varint,4,opt,name=is_disturb,json=isDisturb,proto3" json:"is_disturb"`
	// @gotags: json:"is_mute"
	IsMute bool `protobuf:"varint,5,opt,name=is_mute,json=isMute,proto3" json:"is_mute"`
	// @gotags: json:"last_read_seq"
	LastReadSeq uint64 `protobuf:"varint,6,opt,name=last_read_seq,json=lastReadSeq,proto3" json:"last_read_seq"`
	// @gotags: json:"create_time"
	CreateTime int64 `protobuf:"varint,7,opt,name=create_time,json=createTime,proto3" json:"create_time"`
	// @gotags: json:"update_time"
	UpdateTime    int64 `protobuf:"varint,8,opt,name=update_time,json=updateTime,proto3" json:"update_time"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserConversation) Reset() {
	*x = UserConversation{}
	mi := &file_message_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserConversation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserConversation) ProtoMessage() {}

func (x *UserConversation) ProtoReflect() protoreflect.Message {
	mi := &file_message_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserConversation.ProtoReflect.Descriptor instead.
func (*UserConversation) Descriptor() ([]byte, []int) {
	return file_message_api_proto_rawDescGZIP(), []int{2}
}

func (x *UserConversation) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserConversation) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *UserConversation) GetIsTop() bool {
	if x != nil {
		return x.IsTop
	}
	return false
}

func (x *UserConversation) GetIsDisturb() bool {
	if x != nil {
		return x.IsDisturb
	}
	return false
}

func (x *UserConversation) GetIsMute() bool {
	if x != nil {
		return x.IsMute
	}
	return false
}

func (x *UserConversation) GetLastReadSeq() uint64 {
	if x != nil {
		return x.LastReadSeq
	}
	return 0
}

func (x *UserConversation) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *UserConversation) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

// GetHistoryReq
type GetHistoryReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: form:"conversation_id,optional" json:"conversation_id,optional"
	ConversationId string `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,optional" form:"conversation_id,optional"`
	// @gotags: form:"start_seq,optional" json:"start_seq,optional"
	StartSeq int64 `protobuf:"varint,2,opt,name=start_seq,json=startSeq,proto3" json:"start_seq,optional" form:"start_seq,optional"`
	// @gotags: form:"end_seq,optional" json:"end_seq,optional"
	EndSeq int64 `protobuf:"varint,3,opt,name=end_seq,json=endSeq,proto3" json:"end_seq,optional" form:"end_seq,optional"`
	// @gotags: form:"limit,optional,default=20" json:"limit,optional"
	Limit         int32 `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,optional" form:"limit,optional,default=20"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryReq) Reset() {
	*x = GetHistoryReq{}
	mi := &file_message_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryReq) ProtoMessage() {}

func (x *GetHistoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_message_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryReq.ProtoReflect.Descriptor instead.
func (*GetHistoryReq) Descriptor() ([]byte, []int) {
	return file_message_api_proto_rawDescGZIP(), []int{3}
}

func (x *GetHistoryReq) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *GetHistoryReq) GetStartSeq() int64 {
	if x != nil {
		return x.StartSeq
	}
	return 0
}

func (x *GetHistoryReq) GetEndSeq() int64 {
	if x != nil {
		return x.EndSeq
	}
	return 0
}

func (x *GetHistoryReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// GetHistoryResp
type GetHistoryResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: json:"list"
	List          []*Message `protobuf:"bytes,1,rep,name=list,proto3" json:"list"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryResp) Reset() {
	*x = GetHistoryResp{}
	mi := &file_message_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryResp) ProtoMessage() {}

func (x *GetHistoryResp) ProtoReflect() protoreflect.Message {
	mi := &file_message_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryResp.ProtoReflect.Descriptor instead.
func (*GetHistoryResp) Descriptor() ([]byte, []int) {
	return file_message_api_proto_rawDescGZIP(), []int{4}
}

func (x *GetHistoryResp) GetList() []*Message {
	if x != nil {
		return x.List
	}
	return nil
}

// ReadMessageReq
type ReadMessageReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: json:"conversation_id"
	ConversationId string `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id"`
	// @gotags: json:"seq"
	Seq           uint64 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadMessageReq) Reset() {
	*x = ReadMessageReq{}
	mi := &file_message_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadMessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadMessageReq) ProtoMessage() {}

func (x *ReadMessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_message_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadMessageReq.ProtoReflect.Descriptor instead.
func (*ReadMessageReq) Descriptor() ([]byte, []int) {
	return file_message_api_proto_rawDescGZIP(), []int{5}
}

func (x *ReadMessageReq) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ReadMessageReq) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

// UpdateConversationReq
type UpdateConversationReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: json:"conversation_id"
	ConversationId string `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id"`
	// @gotags: json:"is_top,optional"
	IsTop int32 `protobuf:"varint,2,opt,name=is_top,json=isTop,proto3" json:"is_top,optional"`
	// @gotags: json:"is_disturb,optional"
	IsDisturb int32 `protobuf:"varint,3,opt,name=is_disturb,json=isDisturb,proto3" json:"is_disturb,optional"`
	// @gotags: json:"is_mute,optional"
	IsMute        int32 `protobuf:"varint,4,opt,name=is_mute,json=isMute,proto3" json:"is_mute,optional"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConversationReq) Reset() {
	*x = UpdateConversationReq{}
	mi := &file_message_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConversationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConversationReq) ProtoMessage() {}

func (x *UpdateConversationReq) ProtoReflect() protoreflect.Message {
	mi := &file_message_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConversationReq.ProtoReflect.Descriptor instead.
func (*UpdateConversationReq) Descriptor() ([]byte, []int) {
	return file_message_api_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateConversationReq) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *UpdateConversationReq) GetIsTop() int32 {
	if x != nil {
		return x.IsTop
	}
	return 0
}

func (x *UpdateConversationReq) GetIsDisturb() int32 {
	if x != nil {
		return x.IsDisturb
	}
	return 0
}

func (x *UpdateConversationReq) GetIsMute() int32 {
	if x != nil {
		return x.IsMute
	}
	return 0
}

// GetUserConversationsResp
type GetUserConversationsResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: json:"conversations"
	Conversations []*UserConversation `protobuf:"bytes,1,rep,name=conversations,proto3" json:"conversations"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserConversationsResp) Reset() {
	*x = GetUserConversationsResp{}
	mi := &file_message_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserConversationsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserConversationsResp) ProtoMessage() {}

func (x *GetUserConversationsResp) ProtoReflect() protoreflect.Message {
	mi := &file_message_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserConversationsResp.ProtoReflect.Descriptor instead.
func (*GetUserConversationsResp) Descriptor() ([]byte, []int) {
	return file_message_api_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserConversationsResp) GetConversations() []*UserConversation {
	if x != nil {
		return x.Conversations
	}
	return nil
}

type GetUserActiveConversationsReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: form:"timestamp,optional" json:"timestamp,optional"
	Timestamp     int64 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,optional" form:"timestamp,optional"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserActiveConversationsReq) Reset() {
	*x = GetUserActiveConversationsReq{}
	mi := &file_message_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserActiveConversationsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserActiveConversationsReq) ProtoMessage() {}

func (x *GetUserActiveConversationsReq) ProtoReflect() protoreflect.Message {
	mi := &file_message_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserActiveConversationsReq.ProtoReflect.Descriptor instead.
func (*GetUserActiveConversationsReq) Descriptor() ([]byte, []int) {
	return file_message_api_proto_rawDescGZIP(), []int{8}
}

func (x *GetUserActiveConversationsReq) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type GetUserActiveConversationsResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: json:"conversations"
	Conversations []*Conversation `protobuf:"bytes,1,rep,name=conversations,proto3" json:"conversations"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserActiveConversationsResp) Reset() {
	*x = GetUserActiveConversationsResp{}
	mi := &file_message_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserActiveConversationsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserActiveConversationsResp) ProtoMessage() {}

func (x *GetUserActiveConversationsResp) ProtoReflect() protoreflect.Message {
	mi := &file_message_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserActiveConversationsResp.ProtoReflect.Descriptor instead.
func (*GetUserActiveConversationsResp) Descriptor() ([]byte, []int) {
	return file_message_api_proto_rawDescGZIP(), []int{9}
}

func (x *GetUserActiveConversationsResp) GetConversations() []*Conversation {
	if x != nil {
		return x.Conversations
	}
	return nil
}

var File_message_api_proto protoreflect.FileDescriptor

const file_message_api_proto_rawDesc = "" +
	"\n" +
	"\x11message_api.proto\x12\x05types\"\xbb\x02\n" +
	"\aMessage\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\tR\x05msgId\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12'\n" +
	"\x0fconversation_id\x18\x03 \x01(\tR\x0econversationId\x12 \n" +
	"\ffrom_user_id\x18\x04 \x01(\x04R\n" +
	"fromUserId\x12\x19\n" +
	"\bmsg_type\x18\x05 \x01(\x05R\amsgType\x12\x10\n" +
	"\x03seq\x18\x06 \x01(\x04R\x03seq\x12\x18\n" +
	"\acontent\x18\a \x01(\tR\acontent\x12\x1b\n" +
	"\tmedia_url\x18\b \x01(\tR\bmediaUrl\x12\x14\n" +
	"\x05extra\x18\t \x01(\tR\x05extra\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\x05R\x06status\x12\x1f\n" +
	"\vcreate_time\x18\v \x01(\x03R\n" +
	"createTime\"\xbf\x01\n" +
	"\fConversation\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12+\n" +
	"\x11conversation_type\x18\x02 \x01(\x05R\x10conversationType\x12\x17\n" +
	"\amax_seq\x18\x03 \x01(\x03R\x06maxSeq\x12\x1f\n" +
	"\vcreate_time\x18\x04 \x01(\x03R\n" +
	"createTime\x12\x1f\n" +
	"\vupdate_time\x18\x05 \x01(\x03R\n" +
	"updateTime\"\x89\x02\n" +
	"\x10UserConversation\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12\x15\n" +
	"\x06is_top\x18\x03 \x01(\bR\x05isTop\x12\x1d\n" +
	"\n" +
	"is_disturb\x18\x04 \x01(\bR\tisDisturb\x12\x17\n" +
	"\ais_mute\x18\x05 \x01(\bR\x06isMute\x12\"\n" +
	"\rlast_read_seq\x18\x06 \x01(\x04R\vlastReadSeq\x12\x1f\n" +
	"\vcreate_time\x18\a \x01(\x03R\n" +
	"createTime\x12\x1f\n" +
	"\vupdate_time\x18\b \x01(\x03R\n" +
	"updateTime\"\x84\x01\n" +
	"\rGetHistoryReq\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x1b\n" +
	"\tstart_seq\x18\x02 \x01(\x03R\bstartSeq\x12\x17\n" +
	"\aend_seq\x18\x03 \x01(\x03R\x06endSeq\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"4\n" +
	"\x0eGetHistoryResp\x12\"\n" +
	"\x04list\x18\x01 \x03(\v2\x0e.types.MessageR\x04list\"K\n" +
	"\x0eReadMessageReq\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\"\x8f\x01\n" +
	"\x15UpdateConversationReq\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x15\n" +
	"\x06is_top\x18\x02 \x01(\x05R\x05isTop\x12\x1d\n" +
	"\n" +
	"is_disturb\x18\x03 \x01(\x05R\tisDisturb\x12\x17\n" +
	"\ais_mute\x18\x04 \x01(\x05R\x06isMute\"Y\n" +
	"\x18GetUserConversationsResp\x12=\n" +
	"\rconversations\x18\x01 \x03(\v2\x17.types.UserConversationR\rconversations\"=\n" +
	"\x1dGetUserActiveConversationsReq\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\"[\n" +
	"\x1eGetUserActiveConversationsResp\x129\n" +
	"\rconversations\x18\x01 \x03(\v2\x13.types.ConversationR\rconversationsB\n" +
	"Z\b./;typesb\x06proto3"

var (
	file_message_api_proto_rawDescOnce sync.Once
	file_message_api_proto_rawDescData []byte
)

func file_message_api_proto_rawDescGZIP() []byte {
	file_message_api_proto_rawDescOnce.Do(func() {
		file_message_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_api_proto_rawDesc), len(file_message_api_proto_rawDesc)))
	})
	return file_message_api_proto_rawDescData
}

var file_message_api_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_message_api_proto_goTypes = []any{
	(*Message)(nil),                        // 0: types.Message
	(*Conversation)(nil),                   // 1: types.Conversation
	(*UserConversation)(nil),               // 2: types.UserConversation
	(*GetHistoryReq)(nil),                  // 3: types.GetHistoryReq
	(*GetHistoryResp)(nil),                 // 4: types.GetHistoryResp
	(*ReadMessageReq)(nil),                 // 5: types.ReadMessageReq
	(*UpdateConversationReq)(nil),          // 6: types.UpdateConversationReq
	(*GetUserConversationsResp)(nil),       // 7: types.GetUserConversationsResp
	(*GetUserActiveConversationsReq)(nil),  // 8: types.GetUserActiveConversationsReq
	(*GetUserActiveConversationsResp)(nil), // 9: types.GetUserActiveConversationsResp
}
var file_message_api_proto_depIdxs = []int32{
	0, // 0: types.GetHistoryResp.list:type_name -> types.Message
	2, // 1: types.GetUserConversationsResp.conversations:type_name -> types.UserConversation
	1, // 2: types.GetUserActiveConversationsResp.conversations:type_name -> types.Conversation
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_message_api_proto_init() }
func file_message_api_proto_init() {
	if File_message_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_api_proto_rawDesc), len(file_message_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_api_proto_goTypes,
		DependencyIndexes: file_message_api_proto_depIdxs,
		MessageInfos:      file_message_api_proto_msgTypes,
	}.Build()
	File_message_api_proto = out.File
	file_message_api_proto_goTypes = nil
	file_message_api_proto_depIdxs = nil
}
