// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: user.proto

package userclient

import (
	"context"

	"IM2/internal/apps/User/rpc/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateFriendReq             = user.CreateFriendReq
	CreateUserReq               = user.CreateUserReq
	CreateUserResp              = user.CreateUserResp
	DeleteFriendReq             = user.DeleteFriendReq
	EmptyResp                   = user.EmptyResp
	Friend                      = user.Friend
	FriendRequest               = user.FriendRequest
	GetFriendsReq               = user.GetFriendsReq
	GetFriendsResp              = user.GetFriendsResp
	GetPendingFriendAppliesReq  = user.GetPendingFriendAppliesReq
	GetPendingFriendAppliesResp = user.GetPendingFriendAppliesResp
	GetUserInfoReq              = user.GetUserInfoReq
	GetUserInfoResp             = user.GetUserInfoResp
	HandleFriendApplyReq        = user.HandleFriendApplyReq
	NewFriendApplyReq           = user.NewFriendApplyReq
	NewFriendApplyResp          = user.NewFriendApplyResp
	UpdateFriendReq             = user.UpdateFriendReq
	UpdateInfoReq               = user.UpdateInfoReq
	UserInfo                    = user.UserInfo
	VerifyPasswordReq           = user.VerifyPasswordReq
	VerifyPasswordResp          = user.VerifyPasswordResp

	User interface {
		// 用户管理
		CreateUser(ctx context.Context, in *CreateUserReq, opts ...grpc.CallOption) (*CreateUserResp, error)
		GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoResp, error)
		UpdateInfo(ctx context.Context, in *UpdateInfoReq, opts ...grpc.CallOption) (*EmptyResp, error)
		VerifyPassword(ctx context.Context, in *VerifyPasswordReq, opts ...grpc.CallOption) (*VerifyPasswordResp, error)
		// 好友管理
		GetFriends(ctx context.Context, in *GetFriendsReq, opts ...grpc.CallOption) (*GetFriendsResp, error)
		CreateFriend(ctx context.Context, in *CreateFriendReq, opts ...grpc.CallOption) (*EmptyResp, error)
		UpdateFriend(ctx context.Context, in *UpdateFriendReq, opts ...grpc.CallOption) (*EmptyResp, error)
		DeleteFriend(ctx context.Context, in *DeleteFriendReq, opts ...grpc.CallOption) (*EmptyResp, error)
		// 好友申请
		NewFriendApply(ctx context.Context, in *NewFriendApplyReq, opts ...grpc.CallOption) (*NewFriendApplyResp, error)
		HandleFriendApply(ctx context.Context, in *HandleFriendApplyReq, opts ...grpc.CallOption) (*EmptyResp, error)
		GetPendingFriendApplies(ctx context.Context, in *GetPendingFriendAppliesReq, opts ...grpc.CallOption) (*GetPendingFriendAppliesResp, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

// 用户管理
func (m *defaultUser) CreateUser(ctx context.Context, in *CreateUserReq, opts ...grpc.CallOption) (*CreateUserResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.CreateUser(ctx, in, opts...)
}

func (m *defaultUser) GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetUserInfo(ctx, in, opts...)
}

func (m *defaultUser) UpdateInfo(ctx context.Context, in *UpdateInfoReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.UpdateInfo(ctx, in, opts...)
}

func (m *defaultUser) VerifyPassword(ctx context.Context, in *VerifyPasswordReq, opts ...grpc.CallOption) (*VerifyPasswordResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.VerifyPassword(ctx, in, opts...)
}

// 好友管理
func (m *defaultUser) GetFriends(ctx context.Context, in *GetFriendsReq, opts ...grpc.CallOption) (*GetFriendsResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetFriends(ctx, in, opts...)
}

func (m *defaultUser) CreateFriend(ctx context.Context, in *CreateFriendReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.CreateFriend(ctx, in, opts...)
}

func (m *defaultUser) UpdateFriend(ctx context.Context, in *UpdateFriendReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.UpdateFriend(ctx, in, opts...)
}

func (m *defaultUser) DeleteFriend(ctx context.Context, in *DeleteFriendReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.DeleteFriend(ctx, in, opts...)
}

// 好友申请
func (m *defaultUser) NewFriendApply(ctx context.Context, in *NewFriendApplyReq, opts ...grpc.CallOption) (*NewFriendApplyResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.NewFriendApply(ctx, in, opts...)
}

func (m *defaultUser) HandleFriendApply(ctx context.Context, in *HandleFriendApplyReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.HandleFriendApply(ctx, in, opts...)
}

func (m *defaultUser) GetPendingFriendApplies(ctx context.Context, in *GetPendingFriendAppliesReq, opts ...grpc.CallOption) (*GetPendingFriendAppliesResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetPendingFriendApplies(ctx, in, opts...)
}
