apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: im2

# 动态生成 ConfigMap
configMapGenerator:
  - name: im2-config
    env: .env
generatorOptions:
  disableNameSuffixHash: true   # 不加随机哈希后缀，这样之前的 Deployment 才能直接挂载到 im2-config

# 包含你需要部署的所有资源清单
resources:
  - deploy/k8s/im2-apis.yaml
  - deploy/k8s/im2-rpcs.yaml
  - deploy/k8s/apisix-routes.yaml

# 全局镜像映射替换
images:
  - name: imchat
    newName: crpi-sxfmavixm0flbpia.cn-heyuan.personal.cr.aliyuncs.com/dev-development/imchat
