// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: llm_api.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Role int32

const (
	Role_ROLE_ME     Role = 0
	Role_ROLE_OTHER  Role = 1
	Role_ROLE_SYSTEM Role = 2
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "ROLE_ME",
		1: "ROLE_OTHER",
		2: "ROLE_SYSTEM",
	}
	Role_value = map[string]int32{
		"ROLE_ME":     0,
		"ROLE_OTHER":  1,
		"ROLE_SYSTEM": 2,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_llm_api_proto_enumTypes[0].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_llm_api_proto_enumTypes[0]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_llm_api_proto_rawDescGZIP(), []int{0}
}

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          Role                   `protobuf:"varint,1,opt,name=role,proto3,enum=types.llm.Role" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_llm_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_llm_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_llm_api_proto_rawDescGZIP(), []int{0}
}

func (x *ChatMessage) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_ROLE_ME
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type SuggestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	History       []*ChatMessage         `protobuf:"bytes,1,rep,name=history,proto3" json:"history,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuggestRequest) Reset() {
	*x = SuggestRequest{}
	mi := &file_llm_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuggestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestRequest) ProtoMessage() {}

func (x *SuggestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llm_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestRequest.ProtoReflect.Descriptor instead.
func (*SuggestRequest) Descriptor() ([]byte, []int) {
	return file_llm_api_proto_rawDescGZIP(), []int{1}
}

func (x *SuggestRequest) GetHistory() []*ChatMessage {
	if x != nil {
		return x.History
	}
	return nil
}

type SuggestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reply         []string               `protobuf:"bytes,1,rep,name=reply,proto3" json:"reply,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuggestResponse) Reset() {
	*x = SuggestResponse{}
	mi := &file_llm_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuggestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestResponse) ProtoMessage() {}

func (x *SuggestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llm_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestResponse.ProtoReflect.Descriptor instead.
func (*SuggestResponse) Descriptor() ([]byte, []int) {
	return file_llm_api_proto_rawDescGZIP(), []int{2}
}

func (x *SuggestResponse) GetReply() []string {
	if x != nil {
		return x.Reply
	}
	return nil
}

var File_llm_api_proto protoreflect.FileDescriptor

const file_llm_api_proto_rawDesc = "" +
	"\n" +
	"\rllm_api.proto\x12\ttypes.llm\"L\n" +
	"\vChatMessage\x12#\n" +
	"\x04role\x18\x01 \x01(\x0e2\x0f.types.llm.RoleR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"B\n" +
	"\x0eSuggestRequest\x120\n" +
	"\ahistory\x18\x01 \x03(\v2\x16.types.llm.ChatMessageR\ahistory\"'\n" +
	"\x0fSuggestResponse\x12\x14\n" +
	"\x05reply\x18\x01 \x03(\tR\x05reply*4\n" +
	"\x04Role\x12\v\n" +
	"\aROLE_ME\x10\x00\x12\x0e\n" +
	"\n" +
	"ROLE_OTHER\x10\x01\x12\x0f\n" +
	"\vROLE_SYSTEM\x10\x02B\n" +
	"Z\b./;typesb\x06proto3"

var (
	file_llm_api_proto_rawDescOnce sync.Once
	file_llm_api_proto_rawDescData []byte
)

func file_llm_api_proto_rawDescGZIP() []byte {
	file_llm_api_proto_rawDescOnce.Do(func() {
		file_llm_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_llm_api_proto_rawDesc), len(file_llm_api_proto_rawDesc)))
	})
	return file_llm_api_proto_rawDescData
}

var file_llm_api_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_llm_api_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_llm_api_proto_goTypes = []any{
	(Role)(0),               // 0: types.llm.Role
	(*ChatMessage)(nil),     // 1: types.llm.ChatMessage
	(*SuggestRequest)(nil),  // 2: types.llm.SuggestRequest
	(*SuggestResponse)(nil), // 3: types.llm.SuggestResponse
}
var file_llm_api_proto_depIdxs = []int32{
	0, // 0: types.llm.ChatMessage.role:type_name -> types.llm.Role
	1, // 1: types.llm.SuggestRequest.history:type_name -> types.llm.ChatMessage
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_llm_api_proto_init() }
func file_llm_api_proto_init() {
	if File_llm_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_llm_api_proto_rawDesc), len(file_llm_api_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_llm_api_proto_goTypes,
		DependencyIndexes: file_llm_api_proto_depIdxs,
		EnumInfos:         file_llm_api_proto_enumTypes,
		MessageInfos:      file_llm_api_proto_msgTypes,
	}.Build()
	File_llm_api_proto = out.File
	file_llm_api_proto_goTypes = nil
	file_llm_api_proto_depIdxs = nil
}
