// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package handler

import (
	"net/http"

	direct "IM2/internal/apps/Auth/api/handler/direct"
	jwt "IM2/internal/apps/Auth/api/handler/jwt"
	"IM2/internal/apps/Auth/api/svc"
	"IM2/internal/middleware"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/getAuthCode",
				Handler: direct.GetAuthCodeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: direct.RegisterHandler(serverCtx),
			},
			{
				// 下载入口由浏览器打开，带不上 X-App-Version，不能挂版本门槛：挂上会把要下载新版的人也挡成 426
				Method:  http.MethodGet,
				Path:    "/download",
				Handler: direct.DownloadHandler(serverCtx),
			},
		},
		rest.WithPrefix("/auth"),
	)

	// 客户端最低版本门槛只挂在登录、刷新 token 和启动版本探测上：这三个请求由客户端主进程发出，
	// 会带 X-App-Version。注册、验证码由渲染进程经 axios 发出，带不上这个头（自定义头会触发 CORS
	// 预检，需网关放行），挂上会把新版客户端也当成旧版拦掉；旧版能注册也登录不了，无需拦。
	appVersionGate := middleware.WithAppVersionGate(serverCtx.VersionGate, serverCtx.Config.AppVersion.DownloadURL)

	server.AddRoutes(
		rest.WithMiddlewares([]rest.Middleware{appVersionGate}, []rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/version",
				Handler: direct.VersionHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: direct.LoginHandler(serverCtx),
			},
		}...),
		rest.WithPrefix("/auth"),
	)

	server.AddRoutes(
		rest.WithMiddlewares([]rest.Middleware{
			// 版本门槛在 JWT 之前：版本过低直接 426，不必先校验 token
			appVersionGate,
			middleware.WithJwtAuth(serverCtx.TokenManager),
		}, []rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/refresh",
				Handler: jwt.RefreshHandler(serverCtx),
			},
		}...,
		),
		rest.WithPrefix("/auth"),
	)
}
