// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: pkg/proto/social/social.proto

package social

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GroupApplyStatus int32

const (
	GroupApplyStatus_GROUP_APPLY_STATUS_UNSPECIFIED GroupApplyStatus = 0 // 未知
	GroupApplyStatus_GROUP_APPLY_STATUS_PENDING     GroupApplyStatus = 1 // 待处理
	GroupApplyStatus_GROUP_APPLY_STATUS_ACCEPTED    GroupApplyStatus = 2 // 已同意
	GroupApplyStatus_GROUP_APPLY_STATUS_REJECTED    GroupApplyStatus = 3 // 已拒绝
	GroupApplyStatus_GROUP_APPLY_STATUS_IGNORED     GroupApplyStatus = 4 // 已忽略
)

// Enum value maps for GroupApplyStatus.
var (
	GroupApplyStatus_name = map[int32]string{
		0: "GROUP_APPLY_STATUS_UNSPECIFIED",
		1: "GROUP_APPLY_STATUS_PENDING",
		2: "GROUP_APPLY_STATUS_ACCEPTED",
		3: "GROUP_APPLY_STATUS_REJECTED",
		4: "GROUP_APPLY_STATUS_IGNORED",
	}
	GroupApplyStatus_value = map[string]int32{
		"GROUP_APPLY_STATUS_UNSPECIFIED": 0,
		"GROUP_APPLY_STATUS_PENDING":     1,
		"GROUP_APPLY_STATUS_ACCEPTED":    2,
		"GROUP_APPLY_STATUS_REJECTED":    3,
		"GROUP_APPLY_STATUS_IGNORED":     4,
	}
)

func (x GroupApplyStatus) Enum() *GroupApplyStatus {
	p := new(GroupApplyStatus)
	*p = x
	return p
}

func (x GroupApplyStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GroupApplyStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_social_social_proto_enumTypes[0].Descriptor()
}

func (GroupApplyStatus) Type() protoreflect.EnumType {
	return &file_pkg_proto_social_social_proto_enumTypes[0]
}

func (x GroupApplyStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GroupApplyStatus.Descriptor instead.
func (GroupApplyStatus) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_social_social_proto_rawDescGZIP(), []int{0}
}

type InviteStatus int32

const (
	InviteStatus_INVITE_STATUS_UNSPECIFIED InviteStatus = 0 // 未知
	InviteStatus_INVITE_STATUS_PENDING     InviteStatus = 1 // 待处理
	InviteStatus_INVITE_STATUS_ACCEPTED    InviteStatus = 2 // 已接受
	InviteStatus_INVITE_STATUS_REJECTED    InviteStatus = 3 // 已拒绝
)

// Enum value maps for InviteStatus.
var (
	InviteStatus_name = map[int32]string{
		0: "INVITE_STATUS_UNSPECIFIED",
		1: "INVITE_STATUS_PENDING",
		2: "INVITE_STATUS_ACCEPTED",
		3: "INVITE_STATUS_REJECTED",
	}
	InviteStatus_value = map[string]int32{
		"INVITE_STATUS_UNSPECIFIED": 0,
		"INVITE_STATUS_PENDING":     1,
		"INVITE_STATUS_ACCEPTED":    2,
		"INVITE_STATUS_REJECTED":    3,
	}
)

func (x InviteStatus) Enum() *InviteStatus {
	p := new(InviteStatus)
	*p = x
	return p
}

func (x InviteStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InviteStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_social_social_proto_enumTypes[1].Descriptor()
}

func (InviteStatus) Type() protoreflect.EnumType {
	return &file_pkg_proto_social_social_proto_enumTypes[1]
}

func (x InviteStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InviteStatus.Descriptor instead.
func (InviteStatus) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_social_social_proto_rawDescGZIP(), []int{1}
}

type FriendSource int32

const (
	FriendSource_FRIEND_SOURCE_UNSPECIFIED FriendSource = 0 // 未知
	FriendSource_FRIEND_SOURCE_SEARCH      FriendSource = 1 // 搜索添加
	FriendSource_FRIEND_SOURCE_GROUP       FriendSource = 2 // 群聊添加
	FriendSource_FRIEND_SOURCE_RECOMMEND   FriendSource = 3 // 系统推荐
)

// Enum value maps for FriendSource.
var (
	FriendSource_name = map[int32]string{
		0: "FRIEND_SOURCE_UNSPECIFIED",
		1: "FRIEND_SOURCE_SEARCH",
		2: "FRIEND_SOURCE_GROUP",
		3: "FRIEND_SOURCE_RECOMMEND",
	}
	FriendSource_value = map[string]int32{
		"FRIEND_SOURCE_UNSPECIFIED": 0,
		"FRIEND_SOURCE_SEARCH":      1,
		"FRIEND_SOURCE_GROUP":       2,
		"FRIEND_SOURCE_RECOMMEND":   3,
	}
)

func (x FriendSource) Enum() *FriendSource {
	p := new(FriendSource)
	*p = x
	return p
}

func (x FriendSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FriendSource) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_social_social_proto_enumTypes[2].Descriptor()
}

func (FriendSource) Type() protoreflect.EnumType {
	return &file_pkg_proto_social_social_proto_enumTypes[2]
}

func (x FriendSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FriendSource.Descriptor instead.
func (FriendSource) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_social_social_proto_rawDescGZIP(), []int{2}
}

type ApplyStatus int32

const (
	ApplyStatus_APPLY_STATUS_UNSPECIFIED ApplyStatus = 0 // 未知
	ApplyStatus_APPLY_STATUS_PENDING     ApplyStatus = 1 // 待处理
	ApplyStatus_APPLY_STATUS_AGREED      ApplyStatus = 2 // 已同意
	ApplyStatus_APPLY_STATUS_REJECTED    ApplyStatus = 3 // 已拒绝
	ApplyStatus_APPLY_STATUS_IGNORED     ApplyStatus = 4 // 已忽略
)

// Enum value maps for ApplyStatus.
var (
	ApplyStatus_name = map[int32]string{
		0: "APPLY_STATUS_UNSPECIFIED",
		1: "APPLY_STATUS_PENDING",
		2: "APPLY_STATUS_AGREED",
		3: "APPLY_STATUS_REJECTED",
		4: "APPLY_STATUS_IGNORED",
	}
	ApplyStatus_value = map[string]int32{
		"APPLY_STATUS_UNSPECIFIED": 0,
		"APPLY_STATUS_PENDING":     1,
		"APPLY_STATUS_AGREED":      2,
		"APPLY_STATUS_REJECTED":    3,
		"APPLY_STATUS_IGNORED":     4,
	}
)

func (x ApplyStatus) Enum() *ApplyStatus {
	p := new(ApplyStatus)
	*p = x
	return p
}

func (x ApplyStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ApplyStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_social_social_proto_enumTypes[3].Descriptor()
}

func (ApplyStatus) Type() protoreflect.EnumType {
	return &file_pkg_proto_social_social_proto_enumTypes[3]
}

func (x ApplyStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ApplyStatus.Descriptor instead.
func (ApplyStatus) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_social_social_proto_rawDescGZIP(), []int{3}
}

type ApplySource int32

const (
	ApplySource_APPLY_SOURCE_UNSPECIFIED    ApplySource = 0
	ApplySource_APPLY_SOURCE_SEARCH_ACCOUNT ApplySource = 1 // 搜索账号
	ApplySource_APPLY_SOURCE_SEARCH_PHONE   ApplySource = 2 // 搜索手机
	ApplySource_APPLY_SOURCE_SEARCH_NAME    ApplySource = 3 // 搜索昵称
	ApplySource_APPLY_SOURCE_FROM_GROUP     ApplySource = 4 // 群组添加
	ApplySource_APPLY_SOURCE_FROM_RECOMMEND ApplySource = 5 // 系统推荐
)

// Enum value maps for ApplySource.
var (
	ApplySource_name = map[int32]string{
		0: "APPLY_SOURCE_UNSPECIFIED",
		1: "APPLY_SOURCE_SEARCH_ACCOUNT",
		2: "APPLY_SOURCE_SEARCH_PHONE",
		3: "APPLY_SOURCE_SEARCH_NAME",
		4: "APPLY_SOURCE_FROM_GROUP",
		5: "APPLY_SOURCE_FROM_RECOMMEND",
	}
	ApplySource_value = map[string]int32{
		"APPLY_SOURCE_UNSPECIFIED":    0,
		"APPLY_SOURCE_SEARCH_ACCOUNT": 1,
		"APPLY_SOURCE_SEARCH_PHONE":   2,
		"APPLY_SOURCE_SEARCH_NAME":    3,
		"APPLY_SOURCE_FROM_GROUP":     4,
		"APPLY_SOURCE_FROM_RECOMMEND": 5,
	}
)

func (x ApplySource) Enum() *ApplySource {
	p := new(ApplySource)
	*p = x
	return p
}

func (x ApplySource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ApplySource) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_social_social_proto_enumTypes[4].Descriptor()
}

func (ApplySource) Type() protoreflect.EnumType {
	return &file_pkg_proto_social_social_proto_enumTypes[4]
}

func (x ApplySource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ApplySource.Descriptor instead.
func (ApplySource) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_social_social_proto_rawDescGZIP(), []int{4}
}

// 群申请
type GroupApply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                        // 申请ID
	SenderId      uint64                 `protobuf:"varint,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`            // 发起者ID
	GroupId       uint64                 `protobuf:"varint,3,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`               // 群组ID
	ApplyMsg      string                 `protobuf:"bytes,4,opt,name=apply_msg,json=applyMsg,proto3" json:"apply_msg,omitempty"`             // 申请消息
	Status        GroupApplyStatus       `protobuf:"varint,5,opt,name=status,proto3,enum=social.GroupApplyStatus" json:"status,omitempty"`   // 申请状态
	HandlerId     uint64                 `protobuf:"varint,6,opt,name=handler_id,json=handlerId,proto3" json:"handler_id,omitempty"`         // 处理者ID
	RequestTime   int64                  `protobuf:"varint,7,opt,name=request_time,json=requestTime,proto3" json:"request_time,omitempty"`   // 申请时间
	HandleTime    int64                  `protobuf:"varint,8,opt,name=handle_time,json=handleTime,proto3" json:"handle_time,omitempty"`      // 处理时间
	RejectReason  string                 `protobuf:"bytes,9,opt,name=reject_reason,json=rejectReason,proto3" json:"reject_reason,omitempty"` // 拒绝原因
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupApply) Reset() {
	*x = GroupApply{}
	mi := &file_pkg_proto_social_social_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupApply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupApply) ProtoMessage() {}

func (x *GroupApply) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_social_social_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupApply.ProtoReflect.Descriptor instead.
func (*GroupApply) Descriptor() ([]byte, []int) {
	return file_pkg_proto_social_social_proto_rawDescGZIP(), []int{0}
}

func (x *GroupApply) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GroupApply) GetSenderId() uint64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *GroupApply) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GroupApply) GetApplyMsg() string {
	if x != nil {
		return x.ApplyMsg
	}
	return ""
}

func (x *GroupApply) GetStatus() GroupApplyStatus {
	if x != nil {
		return x.Status
	}
	return GroupApplyStatus_GROUP_APPLY_STATUS_UNSPECIFIED
}

func (x *GroupApply) GetHandlerId() uint64 {
	if x != nil {
		return x.HandlerId
	}
	return 0
}

func (x *GroupApply) GetRequestTime() int64 {
	if x != nil {
		return x.RequestTime
	}
	return 0
}

func (x *GroupApply) GetHandleTime() int64 {
	if x != nil {
		return x.HandleTime
	}
	return 0
}

func (x *GroupApply) GetRejectReason() string {
	if x != nil {
		return x.RejectReason
	}
	return ""
}

// 群邀请（被邀请人视角）：群成员邀请他人入群，待被邀请人确认
type GroupInvite struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                   // 邀请ID
	GroupId       uint64                 `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`          // 群组ID
	InviterId     uint64                 `protobuf:"varint,3,opt,name=inviter_id,json=inviterId,proto3" json:"inviter_id,omitempty"`    // 邀请人ID（群成员）
	InviteeId     uint64                 `protobuf:"varint,4,opt,name=invitee_id,json=inviteeId,proto3" json:"invitee_id,omitempty"`    // 被邀请人ID
	Status        InviteStatus           `protobuf:"varint,5,opt,name=status,proto3,enum=social.InviteStatus" json:"status,omitempty"`  // 邀请状态
	InviteMsg     string                 `protobuf:"bytes,6,opt,name=invite_msg,json=inviteMsg,proto3" json:"invite_msg,omitempty"`     // 邀请语
	CreateTime    int64                  `protobuf:"varint,7,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"` // 创建时间
	UpdateTime    int64                  `protobuf:"varint,8,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"` // 更新时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupInvite) Reset() {
	*x = GroupInvite{}
	mi := &file_pkg_proto_social_social_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupInvite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupInvite) ProtoMessage() {}

func (x *GroupInvite) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_social_social_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupInvite.ProtoReflect.Descriptor instead.
func (*GroupInvite) Descriptor() ([]byte, []int) {
	return file_pkg_proto_social_social_proto_rawDescGZIP(), []int{1}
}

func (x *GroupInvite) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GroupInvite) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GroupInvite) GetInviterId() uint64 {
	if x != nil {
		return x.InviterId
	}
	return 0
}

func (x *GroupInvite) GetInviteeId() uint64 {
	if x != nil {
		return x.InviteeId
	}
	return 0
}

func (x *GroupInvite) GetStatus() InviteStatus {
	if x != nil {
		return x.Status
	}
	return InviteStatus_INVITE_STATUS_UNSPECIFIED
}

func (x *GroupInvite) GetInviteMsg() string {
	if x != nil {
		return x.InviteMsg
	}
	return ""
}

func (x *GroupInvite) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *GroupInvite) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

// 好友信息
type Friend struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`             // 用户ID（我）
	FriendId      uint64                 `protobuf:"varint,2,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"`       // 好友ID（对方）
	Remark        string                 `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`                            // 好友备注名
	Starred       bool                   `protobuf:"varint,4,opt,name=starred,proto3" json:"starred,omitempty"`                         // 是否星标
	Blocked       bool                   `protobuf:"varint,5,opt,name=blocked,proto3" json:"blocked,omitempty"`                         // 是否拉黑
	Source        FriendSource           `protobuf:"varint,6,opt,name=source,proto3,enum=social.FriendSource" json:"source,omitempty"`  // 来源
	CreateTime    int64                  `protobuf:"varint,9,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"` // 成为好友时间
	Extra         string                 `protobuf:"bytes,10,opt,name=extra,proto3" json:"extra,omitempty"`                             // 扩展字段
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Friend) Reset() {
	*x = Friend{}
	mi := &file_pkg_proto_social_social_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Friend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Friend) ProtoMessage() {}

func (x *Friend) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_social_social_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Friend.ProtoReflect.Descriptor instead.
func (*Friend) Descriptor() ([]byte, []int) {
	return file_pkg_proto_social_social_proto_rawDescGZIP(), []int{2}
}

func (x *Friend) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Friend) GetFriendId() uint64 {
	if x != nil {
		return x.FriendId
	}
	return 0
}

func (x *Friend) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *Friend) GetStarred() bool {
	if x != nil {
		return x.Starred
	}
	return false
}

func (x *Friend) GetBlocked() bool {
	if x != nil {
		return x.Blocked
	}
	return false
}

func (x *Friend) GetSource() FriendSource {
	if x != nil {
		return x.Source
	}
	return FriendSource_FRIEND_SOURCE_UNSPECIFIED
}

func (x *Friend) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *Friend) GetExtra() string {
	if x != nil {
		return x.Extra
	}
	return ""
}

// 好友请求
type FriendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                        // 申请记录ID
	FromUserId    uint64                 `protobuf:"varint,2,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`    // 发起者ID
	ToUserId      uint64                 `protobuf:"varint,3,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`          // 接收者ID
	ApplyMsg      string                 `protobuf:"bytes,4,opt,name=apply_msg,json=applyMsg,proto3" json:"apply_msg,omitempty"`             // 申请理由
	Status        ApplyStatus            `protobuf:"varint,5,opt,name=status,proto3,enum=social.ApplyStatus" json:"status,omitempty"`        // 申请状态
	Source        ApplySource            `protobuf:"varint,6,opt,name=source,proto3,enum=social.ApplySource" json:"source,omitempty"`        // 来源
	RequestTime   int64                  `protobuf:"varint,7,opt,name=request_time,json=requestTime,proto3" json:"request_time,omitempty"`   // 申请时间
	HandleTime    int64                  `protobuf:"varint,8,opt,name=handle_time,json=handleTime,proto3" json:"handle_time,omitempty"`      // 处理时间
	RejectReason  string                 `protobuf:"bytes,9,opt,name=reject_reason,json=rejectReason,proto3" json:"reject_reason,omitempty"` // 拒绝原因
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendRequest) Reset() {
	*x = FriendRequest{}
	mi := &file_pkg_proto_social_social_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendRequest) ProtoMessage() {}

func (x *FriendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_social_social_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendRequest.ProtoReflect.Descriptor instead.
func (*FriendRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_social_social_proto_rawDescGZIP(), []int{3}
}

func (x *FriendRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FriendRequest) GetFromUserId() uint64 {
	if x != nil {
		return x.FromUserId
	}
	return 0
}

func (x *FriendRequest) GetToUserId() uint64 {
	if x != nil {
		return x.ToUserId
	}
	return 0
}

func (x *FriendRequest) GetApplyMsg() string {
	if x != nil {
		return x.ApplyMsg
	}
	return ""
}

func (x *FriendRequest) GetStatus() ApplyStatus {
	if x != nil {
		return x.Status
	}
	return ApplyStatus_APPLY_STATUS_UNSPECIFIED
}

func (x *FriendRequest) GetSource() ApplySource {
	if x != nil {
		return x.Source
	}
	return ApplySource_APPLY_SOURCE_UNSPECIFIED
}

func (x *FriendRequest) GetRequestTime() int64 {
	if x != nil {
		return x.RequestTime
	}
	return 0
}

func (x *FriendRequest) GetHandleTime() int64 {
	if x != nil {
		return x.HandleTime
	}
	return 0
}

func (x *FriendRequest) GetRejectReason() string {
	if x != nil {
		return x.RejectReason
	}
	return ""
}

var File_pkg_proto_social_social_proto protoreflect.FileDescriptor

const file_pkg_proto_social_social_proto_rawDesc = "" +
	"\n" +
	"\x1dpkg/proto/social/social.proto\x12\x06social\"\xab\x02\n" +
	"\n" +
	"GroupApply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\x04R\bsenderId\x12\x19\n" +
	"\bgroup_id\x18\x03 \x01(\x04R\agroupId\x12\x1b\n" +
	"\tapply_msg\x18\x04 \x01(\tR\bapplyMsg\x120\n" +
	"\x06status\x18\x05 \x01(\x0e2\x18.social.GroupApplyStatusR\x06status\x12\x1d\n" +
	"\n" +
	"handler_id\x18\x06 \x01(\x04R\thandlerId\x12!\n" +
	"\frequest_time\x18\a \x01(\x03R\vrequestTime\x12\x1f\n" +
	"\vhandle_time\x18\b \x01(\x03R\n" +
	"handleTime\x12#\n" +
	"\rreject_reason\x18\t \x01(\tR\frejectReason\"\x85\x02\n" +
	"\vGroupInvite\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\x04R\agroupId\x12\x1d\n" +
	"\n" +
	"inviter_id\x18\x03 \x01(\x04R\tinviterId\x12\x1d\n" +
	"\n" +
	"invitee_id\x18\x04 \x01(\x04R\tinviteeId\x12,\n" +
	"\x06status\x18\x05 \x01(\x0e2\x14.social.InviteStatusR\x06status\x12\x1d\n" +
	"\n" +
	"invite_msg\x18\x06 \x01(\tR\tinviteMsg\x12\x1f\n" +
	"\vcreate_time\x18\a \x01(\x03R\n" +
	"createTime\x12\x1f\n" +
	"\vupdate_time\x18\b \x01(\x03R\n" +
	"updateTime\"\xef\x01\n" +
	"\x06Friend\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1b\n" +
	"\tfriend_id\x18\x02 \x01(\x04R\bfriendId\x12\x16\n" +
	"\x06remark\x18\x03 \x01(\tR\x06remark\x12\x18\n" +
	"\astarred\x18\x04 \x01(\bR\astarred\x12\x18\n" +
	"\ablocked\x18\x05 \x01(\bR\ablocked\x12,\n" +
	"\x06source\x18\x06 \x01(\x0e2\x14.social.FriendSourceR\x06source\x12\x1f\n" +
	"\vcreate_time\x18\t \x01(\x03R\n" +
	"createTime\x12\x14\n" +
	"\x05extra\x18\n" +
	" \x01(\tR\x05extra\"\xbf\x02\n" +
	"\rFriendRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12 \n" +
	"\ffrom_user_id\x18\x02 \x01(\x04R\n" +
	"fromUserId\x12\x1c\n" +
	"\n" +
	"to_user_id\x18\x03 \x01(\x04R\btoUserId\x12\x1b\n" +
	"\tapply_msg\x18\x04 \x01(\tR\bapplyMsg\x12+\n" +
	"\x06status\x18\x05 \x01(\x0e2\x13.social.ApplyStatusR\x06status\x12+\n" +
	"\x06source\x18\x06 \x01(\x0e2\x13.social.ApplySourceR\x06source\x12!\n" +
	"\frequest_time\x18\a \x01(\x03R\vrequestTime\x12\x1f\n" +
	"\vhandle_time\x18\b \x01(\x03R\n" +
	"handleTime\x12#\n" +
	"\rreject_reason\x18\t \x01(\tR\frejectReason*\xb8\x01\n" +
	"\x10GroupApplyStatus\x12\"\n" +
	"\x1eGROUP_APPLY_STATUS_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aGROUP_APPLY_STATUS_PENDING\x10\x01\x12\x1f\n" +
	"\x1bGROUP_APPLY_STATUS_ACCEPTED\x10\x02\x12\x1f\n" +
	"\x1bGROUP_APPLY_STATUS_REJECTED\x10\x03\x12\x1e\n" +
	"\x1aGROUP_APPLY_STATUS_IGNORED\x10\x04*\x80\x01\n" +
	"\fInviteStatus\x12\x1d\n" +
	"\x19INVITE_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15INVITE_STATUS_PENDING\x10\x01\x12\x1a\n" +
	"\x16INVITE_STATUS_ACCEPTED\x10\x02\x12\x1a\n" +
	"\x16INVITE_STATUS_REJECTED\x10\x03*}\n" +
	"\fFriendSource\x12\x1d\n" +
	"\x19FRIEND_SOURCE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14FRIEND_SOURCE_SEARCH\x10\x01\x12\x17\n" +
	"\x13FRIEND_SOURCE_GROUP\x10\x02\x12\x1b\n" +
	"\x17FRIEND_SOURCE_RECOMMEND\x10\x03*\x93\x01\n" +
	"\vApplyStatus\x12\x1c\n" +
	"\x18APPLY_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14APPLY_STATUS_PENDING\x10\x01\x12\x17\n" +
	"\x13APPLY_STATUS_AGREED\x10\x02\x12\x19\n" +
	"\x15APPLY_STATUS_REJECTED\x10\x03\x12\x18\n" +
	"\x14APPLY_STATUS_IGNORED\x10\x04*\xc7\x01\n" +
	"\vApplySource\x12\x1c\n" +
	"\x18APPLY_SOURCE_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bAPPLY_SOURCE_SEARCH_ACCOUNT\x10\x01\x12\x1d\n" +
	"\x19APPLY_SOURCE_SEARCH_PHONE\x10\x02\x12\x1c\n" +
	"\x18APPLY_SOURCE_SEARCH_NAME\x10\x03\x12\x1b\n" +
	"\x17APPLY_SOURCE_FROM_GROUP\x10\x04\x12\x1f\n" +
	"\x1bAPPLY_SOURCE_FROM_RECOMMEND\x10\x05B\x16Z\x14IM2/pkg/proto/socialb\x06proto3"

var (
	file_pkg_proto_social_social_proto_rawDescOnce sync.Once
	file_pkg_proto_social_social_proto_rawDescData []byte
)

func file_pkg_proto_social_social_proto_rawDescGZIP() []byte {
	file_pkg_proto_social_social_proto_rawDescOnce.Do(func() {
		file_pkg_proto_social_social_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_social_social_proto_rawDesc), len(file_pkg_proto_social_social_proto_rawDesc)))
	})
	return file_pkg_proto_social_social_proto_rawDescData
}

var file_pkg_proto_social_social_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_pkg_proto_social_social_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_proto_social_social_proto_goTypes = []any{
	(GroupApplyStatus)(0), // 0: social.GroupApplyStatus
	(InviteStatus)(0),     // 1: social.InviteStatus
	(FriendSource)(0),     // 2: social.FriendSource
	(ApplyStatus)(0),      // 3: social.ApplyStatus
	(ApplySource)(0),      // 4: social.ApplySource
	(*GroupApply)(nil),    // 5: social.GroupApply
	(*GroupInvite)(nil),   // 6: social.GroupInvite
	(*Friend)(nil),        // 7: social.Friend
	(*FriendRequest)(nil), // 8: social.FriendRequest
}
var file_pkg_proto_social_social_proto_depIdxs = []int32{
	0, // 0: social.GroupApply.status:type_name -> social.GroupApplyStatus
	1, // 1: social.GroupInvite.status:type_name -> social.InviteStatus
	2, // 2: social.Friend.source:type_name -> social.FriendSource
	3, // 3: social.FriendRequest.status:type_name -> social.ApplyStatus
	4, // 4: social.FriendRequest.source:type_name -> social.ApplySource
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_pkg_proto_social_social_proto_init() }
func file_pkg_proto_social_social_proto_init() {
	if File_pkg_proto_social_social_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_social_social_proto_rawDesc), len(file_pkg_proto_social_social_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_social_social_proto_goTypes,
		DependencyIndexes: file_pkg_proto_social_social_proto_depIdxs,
		EnumInfos:         file_pkg_proto_social_social_proto_enumTypes,
		MessageInfos:      file_pkg_proto_social_social_proto_msgTypes,
	}.Build()
	File_pkg_proto_social_social_proto = out.File
	file_pkg_proto_social_social_proto_goTypes = nil
	file_pkg_proto_social_social_proto_depIdxs = nil
}
