// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: message.proto

package messagerpc

import (
	"context"

	"IM2/internal/apps/Message/rpc/message"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Conversation             = message.Conversation
	GetConversationListReq   = message.GetConversationListReq
	GetConversationListResp  = message.GetConversationListResp
	GetHistoryReq            = message.GetHistoryReq
	GetHistoryResp           = message.GetHistoryResp
	GetUserConversationsReq  = message.GetUserConversationsReq
	GetUserConversationsResp = message.GetUserConversationsResp
	Message                  = message.Message
	ReadMessageReq           = message.ReadMessageReq
	ReadMessageResp          = message.ReadMessageResp
	UpdateConversationReq    = message.UpdateConversationReq
	UpdateConversationResp   = message.UpdateConversationResp
	UserConversation         = message.UserConversation

	MessageRpc interface {
		GetHistory(ctx context.Context, in *GetHistoryReq, opts ...grpc.CallOption) (*GetHistoryResp, error)
		GetConversationList(ctx context.Context, in *GetConversationListReq, opts ...grpc.CallOption) (*GetConversationListResp, error)
		ReadMessage(ctx context.Context, in *ReadMessageReq, opts ...grpc.CallOption) (*ReadMessageResp, error)
		UpdateConversation(ctx context.Context, in *UpdateConversationReq, opts ...grpc.CallOption) (*UpdateConversationResp, error)
		GetUserConversations(ctx context.Context, in *GetUserConversationsReq, opts ...grpc.CallOption) (*GetUserConversationsResp, error)
	}

	defaultMessageRpc struct {
		cli zrpc.Client
	}
)

func NewMessageRpc(cli zrpc.Client) MessageRpc {
	return &defaultMessageRpc{
		cli: cli,
	}
}

func (m *defaultMessageRpc) GetHistory(ctx context.Context, in *GetHistoryReq, opts ...grpc.CallOption) (*GetHistoryResp, error) {
	client := message.NewMessageRpcClient(m.cli.Conn())
	return client.GetHistory(ctx, in, opts...)
}

func (m *defaultMessageRpc) GetConversationList(ctx context.Context, in *GetConversationListReq, opts ...grpc.CallOption) (*GetConversationListResp, error) {
	client := message.NewMessageRpcClient(m.cli.Conn())
	return client.GetConversationList(ctx, in, opts...)
}

func (m *defaultMessageRpc) ReadMessage(ctx context.Context, in *ReadMessageReq, opts ...grpc.CallOption) (*ReadMessageResp, error) {
	client := message.NewMessageRpcClient(m.cli.Conn())
	return client.ReadMessage(ctx, in, opts...)
}

func (m *defaultMessageRpc) UpdateConversation(ctx context.Context, in *UpdateConversationReq, opts ...grpc.CallOption) (*UpdateConversationResp, error) {
	client := message.NewMessageRpcClient(m.cli.Conn())
	return client.UpdateConversation(ctx, in, opts...)
}

func (m *defaultMessageRpc) GetUserConversations(ctx context.Context, in *GetUserConversationsReq, opts ...grpc.CallOption) (*GetUserConversationsResp, error) {
	client := message.NewMessageRpcClient(m.cli.Conn())
	return client.GetUserConversations(ctx, in, opts...)
}
