// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: message.proto

package messagerpc

import (
	"context"

	"IM2/internal/apps/Message/rpc/message"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetConversationListReq         = message.GetConversationListReq
	GetConversationListResp        = message.GetConversationListResp
	GetHistoryReq                  = message.GetHistoryReq
	GetHistoryResp                 = message.GetHistoryResp
	GetUserActiveConversationsReq  = message.GetUserActiveConversationsReq
	GetUserActiveConversationsResp = message.GetUserActiveConversationsResp
	GetUserConversationsReq        = message.GetUserConversationsReq
	GetUserConversationsResp       = message.GetUserConversationsResp
	ReadMessageReq                 = message.ReadMessageReq
	ReadMessageResp                = message.ReadMessageResp
	RecallMessageReq               = message.RecallMessageReq
	RecallMessageResp              = message.RecallMessageResp
	UpdateConversationReq          = message.UpdateConversationReq
	UpdateConversationResp         = message.UpdateConversationResp

	MessageRpc interface {
		GetHistory(ctx context.Context, in *GetHistoryReq, opts ...grpc.CallOption) (*GetHistoryResp, error)
		GetConversationList(ctx context.Context, in *GetConversationListReq, opts ...grpc.CallOption) (*GetConversationListResp, error)
		ReadMessage(ctx context.Context, in *ReadMessageReq, opts ...grpc.CallOption) (*ReadMessageResp, error)
		UpdateConversation(ctx context.Context, in *UpdateConversationReq, opts ...grpc.CallOption) (*UpdateConversationResp, error)
		GetUserConversations(ctx context.Context, in *GetUserConversationsReq, opts ...grpc.CallOption) (*GetUserConversationsResp, error)
		GetUserActiveConversations(ctx context.Context, in *GetUserActiveConversationsReq, opts ...grpc.CallOption) (*GetUserActiveConversationsResp, error)
		RecallMessage(ctx context.Context, in *RecallMessageReq, opts ...grpc.CallOption) (*RecallMessageResp, error)
	}

	defaultMessageRpc struct {
		cli zrpc.Client
	}
)

func NewMessageRpc(cli zrpc.Client) MessageRpc {
	return &defaultMessageRpc{
		cli: cli,
	}
}

func (m *defaultMessageRpc) GetHistory(ctx context.Context, in *GetHistoryReq, opts ...grpc.CallOption) (*GetHistoryResp, error) {
	client := message.NewMessageRpcClient(m.cli.Conn())
	return client.GetHistory(ctx, in, opts...)
}

func (m *defaultMessageRpc) GetConversationList(ctx context.Context, in *GetConversationListReq, opts ...grpc.CallOption) (*GetConversationListResp, error) {
	client := message.NewMessageRpcClient(m.cli.Conn())
	return client.GetConversationList(ctx, in, opts...)
}

func (m *defaultMessageRpc) ReadMessage(ctx context.Context, in *ReadMessageReq, opts ...grpc.CallOption) (*ReadMessageResp, error) {
	client := message.NewMessageRpcClient(m.cli.Conn())
	return client.ReadMessage(ctx, in, opts...)
}

func (m *defaultMessageRpc) UpdateConversation(ctx context.Context, in *UpdateConversationReq, opts ...grpc.CallOption) (*UpdateConversationResp, error) {
	client := message.NewMessageRpcClient(m.cli.Conn())
	return client.UpdateConversation(ctx, in, opts...)
}

func (m *defaultMessageRpc) GetUserConversations(ctx context.Context, in *GetUserConversationsReq, opts ...grpc.CallOption) (*GetUserConversationsResp, error) {
	client := message.NewMessageRpcClient(m.cli.Conn())
	return client.GetUserConversations(ctx, in, opts...)
}

func (m *defaultMessageRpc) GetUserActiveConversations(ctx context.Context, in *GetUserActiveConversationsReq, opts ...grpc.CallOption) (*GetUserActiveConversationsResp, error) {
	client := message.NewMessageRpcClient(m.cli.Conn())
	return client.GetUserActiveConversations(ctx, in, opts...)
}

func (m *defaultMessageRpc) RecallMessage(ctx context.Context, in *RecallMessageReq, opts ...grpc.CallOption) (*RecallMessageResp, error) {
	client := message.NewMessageRpcClient(m.cli.Conn())
	return client.RecallMessage(ctx, in, opts...)
}
