// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: rpc/llm.proto

package llm

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Llm_Suggestions_FullMethodName = "/llm.Llm/Suggestions"
)

// LlmClient is the client API for Llm service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LlmClient interface {
	Suggestions(ctx context.Context, in *SuggestionReq, opts ...grpc.CallOption) (*SuggestionResp, error)
}

type llmClient struct {
	cc grpc.ClientConnInterface
}

func NewLlmClient(cc grpc.ClientConnInterface) LlmClient {
	return &llmClient{cc}
}

func (c *llmClient) Suggestions(ctx context.Context, in *SuggestionReq, opts ...grpc.CallOption) (*SuggestionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuggestionResp)
	err := c.cc.Invoke(ctx, Llm_Suggestions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LlmServer is the server API for Llm service.
// All implementations must embed UnimplementedLlmServer
// for forward compatibility.
type LlmServer interface {
	Suggestions(context.Context, *SuggestionReq) (*SuggestionResp, error)
	mustEmbedUnimplementedLlmServer()
}

// UnimplementedLlmServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLlmServer struct{}

func (UnimplementedLlmServer) Suggestions(context.Context, *SuggestionReq) (*SuggestionResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Suggestions not implemented")
}
func (UnimplementedLlmServer) mustEmbedUnimplementedLlmServer() {}
func (UnimplementedLlmServer) testEmbeddedByValue()             {}

// UnsafeLlmServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LlmServer will
// result in compilation errors.
type UnsafeLlmServer interface {
	mustEmbedUnimplementedLlmServer()
}

func RegisterLlmServer(s grpc.ServiceRegistrar, srv LlmServer) {
	// If the following call pancis, it indicates UnimplementedLlmServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Llm_ServiceDesc, srv)
}

func _Llm_Suggestions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SuggestionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LlmServer).Suggestions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Llm_Suggestions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LlmServer).Suggestions(ctx, req.(*SuggestionReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Llm_ServiceDesc is the grpc.ServiceDesc for Llm service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Llm_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "llm.Llm",
	HandlerType: (*LlmServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Suggestions",
			Handler:    _Llm_Suggestions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc/llm.proto",
}
