// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: pkg/proto/user/user.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JoinType int32

const (
	JoinType_JOIN_TYPE_UNSPECIFIED    JoinType = 0
	JoinType_JOIN_TYPE_AFTER_APPROVAL JoinType = 1 // 同意后加入
	JoinType_JOIN_TYPE_DIRECT         JoinType = 2 // 直接加入
)

// Enum value maps for JoinType.
var (
	JoinType_name = map[int32]string{
		0: "JOIN_TYPE_UNSPECIFIED",
		1: "JOIN_TYPE_AFTER_APPROVAL",
		2: "JOIN_TYPE_DIRECT",
	}
	JoinType_value = map[string]int32{
		"JOIN_TYPE_UNSPECIFIED":    0,
		"JOIN_TYPE_AFTER_APPROVAL": 1,
		"JOIN_TYPE_DIRECT":         2,
	}
)

func (x JoinType) Enum() *JoinType {
	p := new(JoinType)
	*p = x
	return p
}

func (x JoinType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JoinType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_user_user_proto_enumTypes[0].Descriptor()
}

func (JoinType) Type() protoreflect.EnumType {
	return &file_pkg_proto_user_user_proto_enumTypes[0]
}

func (x JoinType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JoinType.Descriptor instead.
func (JoinType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_user_user_proto_rawDescGZIP(), []int{0}
}

type Gender int32

const (
	Gender_GENDER_UNSPECIFIED Gender = 0
	Gender_GENDER_MALE        Gender = 1
	Gender_GENDER_FEMALE      Gender = 2
	Gender_GENDER_UNKNOWN     Gender = 3 // TS: Unknown=3
)

// Enum value maps for Gender.
var (
	Gender_name = map[int32]string{
		0: "GENDER_UNSPECIFIED",
		1: "GENDER_MALE",
		2: "GENDER_FEMALE",
		3: "GENDER_UNKNOWN",
	}
	Gender_value = map[string]int32{
		"GENDER_UNSPECIFIED": 0,
		"GENDER_MALE":        1,
		"GENDER_FEMALE":      2,
		"GENDER_UNKNOWN":     3,
	}
)

func (x Gender) Enum() *Gender {
	p := new(Gender)
	*p = x
	return p
}

func (x Gender) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Gender) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_user_user_proto_enumTypes[1].Descriptor()
}

func (Gender) Type() protoreflect.EnumType {
	return &file_pkg_proto_user_user_proto_enumTypes[1]
}

func (x Gender) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Gender.Descriptor instead.
func (Gender) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_user_user_proto_rawDescGZIP(), []int{1}
}

type UserStatus int32

const (
	UserStatus_USER_STATUS_DISABLED UserStatus = 0 // 禁用
	UserStatus_USER_STATUS_NORMAL   UserStatus = 1 // 正常
)

// Enum value maps for UserStatus.
var (
	UserStatus_name = map[int32]string{
		0: "USER_STATUS_DISABLED",
		1: "USER_STATUS_NORMAL",
	}
	UserStatus_value = map[string]int32{
		"USER_STATUS_DISABLED": 0,
		"USER_STATUS_NORMAL":   1,
	}
)

func (x UserStatus) Enum() *UserStatus {
	p := new(UserStatus)
	*p = x
	return p
}

func (x UserStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_user_user_proto_enumTypes[2].Descriptor()
}

func (UserStatus) Type() protoreflect.EnumType {
	return &file_pkg_proto_user_user_proto_enumTypes[2]
}

func (x UserStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserStatus.Descriptor instead.
func (UserStatus) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_user_user_proto_rawDescGZIP(), []int{2}
}

type OnlineStatus int32

const (
	OnlineStatus_ONLINE_STATUS_OFFLINE   OnlineStatus = 0 // 离线
	OnlineStatus_ONLINE_STATUS_ONLINE    OnlineStatus = 1 // 在线
	OnlineStatus_ONLINE_STATUS_AWAY      OnlineStatus = 2 // 离开
	OnlineStatus_ONLINE_STATUS_BUSY      OnlineStatus = 3 // 忙碌
	OnlineStatus_ONLINE_STATUS_INVISIBLE OnlineStatus = 4 // 隐身
)

// Enum value maps for OnlineStatus.
var (
	OnlineStatus_name = map[int32]string{
		0: "ONLINE_STATUS_OFFLINE",
		1: "ONLINE_STATUS_ONLINE",
		2: "ONLINE_STATUS_AWAY",
		3: "ONLINE_STATUS_BUSY",
		4: "ONLINE_STATUS_INVISIBLE",
	}
	OnlineStatus_value = map[string]int32{
		"ONLINE_STATUS_OFFLINE":   0,
		"ONLINE_STATUS_ONLINE":    1,
		"ONLINE_STATUS_AWAY":      2,
		"ONLINE_STATUS_BUSY":      3,
		"ONLINE_STATUS_INVISIBLE": 4,
	}
)

func (x OnlineStatus) Enum() *OnlineStatus {
	p := new(OnlineStatus)
	*p = x
	return p
}

func (x OnlineStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OnlineStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_user_user_proto_enumTypes[3].Descriptor()
}

func (OnlineStatus) Type() protoreflect.EnumType {
	return &file_pkg_proto_user_user_proto_enumTypes[3]
}

func (x OnlineStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OnlineStatus.Descriptor instead.
func (OnlineStatus) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_user_user_proto_rawDescGZIP(), []int{3}
}

type UserInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserId            uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                                 // 用户ID
	UserName          string                 `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`                            // 用户名
	Avatar            string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`                                                // 头像
	Gender            Gender                 `protobuf:"varint,4,opt,name=gender,proto3,enum=user.Gender" json:"gender,omitempty"`                              // 性别
	Phone             string                 `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`                                                  // 手机号
	JoinType          JoinType               `protobuf:"varint,6,opt,name=join_type,json=joinType,proto3,enum=user.JoinType" json:"join_type,omitempty"`        // 加入类型
	Status            UserStatus             `protobuf:"varint,7,opt,name=status,proto3,enum=user.UserStatus" json:"status,omitempty"`                          // 状态
	PersonalSignature string                 `protobuf:"bytes,8,opt,name=personal_signature,json=personalSignature,proto3" json:"personal_signature,omitempty"` // 签名
	CreateTime        int64                  `protobuf:"varint,9,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`                     // 创建时间
	UpdateTime        int64                  `protobuf:"varint,10,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`                    // 更新时间
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_pkg_proto_user_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_user_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_pkg_proto_user_user_proto_rawDescGZIP(), []int{0}
}

func (x *UserInfo) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserInfo) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *UserInfo) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserInfo) GetGender() Gender {
	if x != nil {
		return x.Gender
	}
	return Gender_GENDER_UNSPECIFIED
}

func (x *UserInfo) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UserInfo) GetJoinType() JoinType {
	if x != nil {
		return x.JoinType
	}
	return JoinType_JOIN_TYPE_UNSPECIFIED
}

func (x *UserInfo) GetStatus() UserStatus {
	if x != nil {
		return x.Status
	}
	return UserStatus_USER_STATUS_DISABLED
}

func (x *UserInfo) GetPersonalSignature() string {
	if x != nil {
		return x.PersonalSignature
	}
	return ""
}

func (x *UserInfo) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *UserInfo) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

// 用户在线状态
type UserOnlineStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                           // 用户ID
	Status         OnlineStatus           `protobuf:"varint,2,opt,name=status,proto3,enum=user.OnlineStatus" json:"status,omitempty"`                  // 在线状态
	LastActiveTime int64                  `protobuf:"varint,3,opt,name=last_active_time,json=lastActiveTime,proto3" json:"last_active_time,omitempty"` // 最后活跃时间
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UserOnlineStatus) Reset() {
	*x = UserOnlineStatus{}
	mi := &file_pkg_proto_user_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserOnlineStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserOnlineStatus) ProtoMessage() {}

func (x *UserOnlineStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_user_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserOnlineStatus.ProtoReflect.Descriptor instead.
func (*UserOnlineStatus) Descriptor() ([]byte, []int) {
	return file_pkg_proto_user_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserOnlineStatus) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserOnlineStatus) GetStatus() OnlineStatus {
	if x != nil {
		return x.Status
	}
	return OnlineStatus_ONLINE_STATUS_OFFLINE
}

func (x *UserOnlineStatus) GetLastActiveTime() int64 {
	if x != nil {
		return x.LastActiveTime
	}
	return 0
}

// 正在输入
type TypingStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                        // 用户ID
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"` // 会话ID
	IsTyping       bool                   `protobuf:"varint,3,opt,name=is_typing,json=isTyping,proto3" json:"is_typing,omitempty"`                  // 是否正在输入
	Timestamp      int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                // 时间戳
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TypingStatus) Reset() {
	*x = TypingStatus{}
	mi := &file_pkg_proto_user_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypingStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypingStatus) ProtoMessage() {}

func (x *TypingStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_user_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypingStatus.ProtoReflect.Descriptor instead.
func (*TypingStatus) Descriptor() ([]byte, []int) {
	return file_pkg_proto_user_user_proto_rawDescGZIP(), []int{2}
}

func (x *TypingStatus) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *TypingStatus) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *TypingStatus) GetIsTyping() bool {
	if x != nil {
		return x.IsTyping
	}
	return false
}

func (x *TypingStatus) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type UserKickoff struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户ID
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`                // 踢出原因
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`         // 时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserKickoff) Reset() {
	*x = UserKickoff{}
	mi := &file_pkg_proto_user_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserKickoff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserKickoff) ProtoMessage() {}

func (x *UserKickoff) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_user_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserKickoff.ProtoReflect.Descriptor instead.
func (*UserKickoff) Descriptor() ([]byte, []int) {
	return file_pkg_proto_user_user_proto_rawDescGZIP(), []int{3}
}

func (x *UserKickoff) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserKickoff) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *UserKickoff) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_pkg_proto_user_user_proto protoreflect.FileDescriptor

const file_pkg_proto_user_user_proto_rawDesc = "" +
	"\n" +
	"\x19pkg/proto/user/user.proto\x12\x04user\"\xdc\x02\n" +
	"\bUserInfo\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1b\n" +
	"\tuser_name\x18\x02 \x01(\tR\buserName\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12$\n" +
	"\x06gender\x18\x04 \x01(\x0e2\f.user.GenderR\x06gender\x12\x14\n" +
	"\x05phone\x18\x05 \x01(\tR\x05phone\x12+\n" +
	"\tjoin_type\x18\x06 \x01(\x0e2\x0e.user.JoinTypeR\bjoinType\x12(\n" +
	"\x06status\x18\a \x01(\x0e2\x10.user.UserStatusR\x06status\x12-\n" +
	"\x12personal_signature\x18\b \x01(\tR\x11personalSignature\x12\x1f\n" +
	"\vcreate_time\x18\t \x01(\x03R\n" +
	"createTime\x12\x1f\n" +
	"\vupdate_time\x18\n" +
	" \x01(\x03R\n" +
	"updateTime\"\x81\x01\n" +
	"\x10UserOnlineStatus\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12*\n" +
	"\x06status\x18\x02 \x01(\x0e2\x12.user.OnlineStatusR\x06status\x12(\n" +
	"\x10last_active_time\x18\x03 \x01(\x03R\x0elastActiveTime\"\x8b\x01\n" +
	"\fTypingStatus\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12\x1b\n" +
	"\tis_typing\x18\x03 \x01(\bR\bisTyping\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"\\\n" +
	"\vUserKickoff\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp*Y\n" +
	"\bJoinType\x12\x19\n" +
	"\x15JOIN_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18JOIN_TYPE_AFTER_APPROVAL\x10\x01\x12\x14\n" +
	"\x10JOIN_TYPE_DIRECT\x10\x02*X\n" +
	"\x06Gender\x12\x16\n" +
	"\x12GENDER_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vGENDER_MALE\x10\x01\x12\x11\n" +
	"\rGENDER_FEMALE\x10\x02\x12\x12\n" +
	"\x0eGENDER_UNKNOWN\x10\x03*>\n" +
	"\n" +
	"UserStatus\x12\x18\n" +
	"\x14USER_STATUS_DISABLED\x10\x00\x12\x16\n" +
	"\x12USER_STATUS_NORMAL\x10\x01*\x90\x01\n" +
	"\fOnlineStatus\x12\x19\n" +
	"\x15ONLINE_STATUS_OFFLINE\x10\x00\x12\x18\n" +
	"\x14ONLINE_STATUS_ONLINE\x10\x01\x12\x16\n" +
	"\x12ONLINE_STATUS_AWAY\x10\x02\x12\x16\n" +
	"\x12ONLINE_STATUS_BUSY\x10\x03\x12\x1b\n" +
	"\x17ONLINE_STATUS_INVISIBLE\x10\x04B\x14Z\x12IM2/pkg/proto/userb\x06proto3"

var (
	file_pkg_proto_user_user_proto_rawDescOnce sync.Once
	file_pkg_proto_user_user_proto_rawDescData []byte
)

func file_pkg_proto_user_user_proto_rawDescGZIP() []byte {
	file_pkg_proto_user_user_proto_rawDescOnce.Do(func() {
		file_pkg_proto_user_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_user_user_proto_rawDesc), len(file_pkg_proto_user_user_proto_rawDesc)))
	})
	return file_pkg_proto_user_user_proto_rawDescData
}

var file_pkg_proto_user_user_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_pkg_proto_user_user_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_proto_user_user_proto_goTypes = []any{
	(JoinType)(0),            // 0: user.JoinType
	(Gender)(0),              // 1: user.Gender
	(UserStatus)(0),          // 2: user.UserStatus
	(OnlineStatus)(0),        // 3: user.OnlineStatus
	(*UserInfo)(nil),         // 4: user.UserInfo
	(*UserOnlineStatus)(nil), // 5: user.UserOnlineStatus
	(*TypingStatus)(nil),     // 6: user.TypingStatus
	(*UserKickoff)(nil),      // 7: user.UserKickoff
}
var file_pkg_proto_user_user_proto_depIdxs = []int32{
	1, // 0: user.UserInfo.gender:type_name -> user.Gender
	0, // 1: user.UserInfo.join_type:type_name -> user.JoinType
	2, // 2: user.UserInfo.status:type_name -> user.UserStatus
	3, // 3: user.UserOnlineStatus.status:type_name -> user.OnlineStatus
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pkg_proto_user_user_proto_init() }
func file_pkg_proto_user_user_proto_init() {
	if File_pkg_proto_user_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_user_user_proto_rawDesc), len(file_pkg_proto_user_user_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_user_user_proto_goTypes,
		DependencyIndexes: file_pkg_proto_user_user_proto_depIdxs,
		EnumInfos:         file_pkg_proto_user_user_proto_enumTypes,
		MessageInfos:      file_pkg_proto_user_user_proto_msgTypes,
	}.Build()
	File_pkg_proto_user_user_proto = out.File
	file_pkg_proto_user_user_proto_goTypes = nil
	file_pkg_proto_user_user_proto_depIdxs = nil
}
