// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: idgen.proto

package idgenclient

import (
	"context"

	"IM2/internal/apps/Idgen/rpc/idgen"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetIdReq  = idgen.GetIdReq
	GetIdResp = idgen.GetIdResp

	Idgen interface {
		// GetId 获取单个或多个ID
		GetId(ctx context.Context, in *GetIdReq, opts ...grpc.CallOption) (*GetIdResp, error)
	}

	defaultIdgen struct {
		cli zrpc.Client
	}
)

func NewIdgen(cli zrpc.Client) Idgen {
	return &defaultIdgen{
		cli: cli,
	}
}

// GetId 获取单个或多个ID
func (m *defaultIdgen) GetId(ctx context.Context, in *GetIdReq, opts ...grpc.CallOption) (*GetIdResp, error) {
	client := idgen.NewIdgenClient(m.cli.Conn())
	return client.GetId(ctx, in, opts...)
}
