// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: llm.proto

package llm

import (
	"context"

	"IM2/internal/apps/Llm/rpc/llm"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Message        = llm.Message
	SuggestionReq  = llm.SuggestionReq
	SuggestionResp = llm.SuggestionResp

	Llm interface {
		Suggestions(ctx context.Context, in *SuggestionReq, opts ...grpc.CallOption) (*SuggestionResp, error)
	}

	defaultLlm struct {
		cli zrpc.Client
	}
)

func NewLlm(cli zrpc.Client) Llm {
	return &defaultLlm{
		cli: cli,
	}
}

func (m *defaultLlm) Suggestions(ctx context.Context, in *SuggestionReq, opts ...grpc.CallOption) (*SuggestionResp, error) {
	client := llm.NewLlmClient(m.cli.Conn())
	return client.Suggestions(ctx, in, opts...)
}
