// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package handler

import (
	"net/http"

	llm "IM2/internal/apps/Llm/api/handler/llm"
	"IM2/internal/apps/Llm/api/svc"
	"IM2/internal/middleware"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.Use(middleware.WithJwtAuth(serverCtx.TokenManager))
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/suggest",
				Handler: llm.SuggestHandler(serverCtx),
			},
		},
		rest.WithPrefix("/ai"),
	)
}
