// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: rpc/user.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmptyResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyResp) Reset() {
	*x = EmptyResp{}
	mi := &file_rpc_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyResp) ProtoMessage() {}

func (x *EmptyResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyResp.ProtoReflect.Descriptor instead.
func (*EmptyResp) Descriptor() ([]byte, []int) {
	return file_rpc_user_proto_rawDescGZIP(), []int{0}
}

type UserInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserId            uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName          string                 `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Avatar            string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Gender            int32                  `protobuf:"varint,4,opt,name=gender,proto3" json:"gender,omitempty"`
	Phone             string                 `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	JoinType          int32                  `protobuf:"varint,6,opt,name=join_type,json=joinType,proto3" json:"join_type,omitempty"`
	PersonalSignature string                 `protobuf:"bytes,7,opt,name=personal_signature,json=personalSignature,proto3" json:"personal_signature,omitempty"`
	Status            int32                  `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`
	CreateTime        int64                  `protobuf:"varint,9,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime        int64                  `protobuf:"varint,10,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_rpc_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_rpc_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserInfo) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserInfo) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *UserInfo) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserInfo) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *UserInfo) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UserInfo) GetJoinType() int32 {
	if x != nil {
		return x.JoinType
	}
	return 0
}

func (x *UserInfo) GetPersonalSignature() string {
	if x != nil {
		return x.PersonalSignature
	}
	return ""
}

func (x *UserInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UserInfo) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *UserInfo) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

type CreateUserReq struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Phone             string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Gender            int32                  `protobuf:"varint,3,opt,name=gender,proto3" json:"gender,omitempty"`
	JoinType          int32                  `protobuf:"varint,4,opt,name=join_type,json=joinType,proto3" json:"join_type,omitempty"`
	Avatar            string                 `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	PersonalSignature string                 `protobuf:"bytes,6,opt,name=personal_signature,json=personalSignature,proto3" json:"personal_signature,omitempty"`
	Password          string                 `protobuf:"bytes,7,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateUserReq) Reset() {
	*x = CreateUserReq{}
	mi := &file_rpc_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserReq) ProtoMessage() {}

func (x *CreateUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserReq.ProtoReflect.Descriptor instead.
func (*CreateUserReq) Descriptor() ([]byte, []int) {
	return file_rpc_user_proto_rawDescGZIP(), []int{2}
}

func (x *CreateUserReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CreateUserReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateUserReq) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *CreateUserReq) GetJoinType() int32 {
	if x != nil {
		return x.JoinType
	}
	return 0
}

func (x *CreateUserReq) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *CreateUserReq) GetPersonalSignature() string {
	if x != nil {
		return x.PersonalSignature
	}
	return ""
}

func (x *CreateUserReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type CreateUserResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResp) Reset() {
	*x = CreateUserResp{}
	mi := &file_rpc_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResp) ProtoMessage() {}

func (x *CreateUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResp.ProtoReflect.Descriptor instead.
func (*CreateUserResp) Descriptor() ([]byte, []int) {
	return file_rpc_user_proto_rawDescGZIP(), []int{3}
}

func (x *CreateUserResp) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []uint64               `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	Phone         string                 `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoReq) Reset() {
	*x = GetUserInfoReq{}
	mi := &file_rpc_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoReq) ProtoMessage() {}

func (x *GetUserInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoReq.ProtoReflect.Descriptor instead.
func (*GetUserInfoReq) Descriptor() ([]byte, []int) {
	return file_rpc_user_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserInfoReq) GetIds() []uint64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *GetUserInfoReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *GetUserInfoReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetUserInfoReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetUserInfoReq) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetUserInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*UserInfo            `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoResp) Reset() {
	*x = GetUserInfoResp{}
	mi := &file_rpc_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoResp) ProtoMessage() {}

func (x *GetUserInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoResp.ProtoReflect.Descriptor instead.
func (*GetUserInfoResp) Descriptor() ([]byte, []int) {
	return file_rpc_user_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserInfoResp) GetData() []*UserInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateInfoReq struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserId            uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Gender            int32                  `protobuf:"varint,3,opt,name=gender,proto3" json:"gender,omitempty"`
	JoinType          int32                  `protobuf:"varint,4,opt,name=join_type,json=joinType,proto3" json:"join_type,omitempty"`
	Avatar            string                 `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	PersonalSignature string                 `protobuf:"bytes,6,opt,name=personal_signature,json=personalSignature,proto3" json:"personal_signature,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdateInfoReq) Reset() {
	*x = UpdateInfoReq{}
	mi := &file_rpc_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateInfoReq) ProtoMessage() {}

func (x *UpdateInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateInfoReq.ProtoReflect.Descriptor instead.
func (*UpdateInfoReq) Descriptor() ([]byte, []int) {
	return file_rpc_user_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateInfoReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateInfoReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateInfoReq) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *UpdateInfoReq) GetJoinType() int32 {
	if x != nil {
		return x.JoinType
	}
	return 0
}

func (x *UpdateInfoReq) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UpdateInfoReq) GetPersonalSignature() string {
	if x != nil {
		return x.PersonalSignature
	}
	return ""
}

type VerifyPasswordReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyPasswordReq) Reset() {
	*x = VerifyPasswordReq{}
	mi := &file_rpc_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyPasswordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyPasswordReq) ProtoMessage() {}

func (x *VerifyPasswordReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyPasswordReq.ProtoReflect.Descriptor instead.
func (*VerifyPasswordReq) Descriptor() ([]byte, []int) {
	return file_rpc_user_proto_rawDescGZIP(), []int{7}
}

func (x *VerifyPasswordReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *VerifyPasswordReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type VerifyPasswordResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyPasswordResp) Reset() {
	*x = VerifyPasswordResp{}
	mi := &file_rpc_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyPasswordResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyPasswordResp) ProtoMessage() {}

func (x *VerifyPasswordResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyPasswordResp.ProtoReflect.Descriptor instead.
func (*VerifyPasswordResp) Descriptor() ([]byte, []int) {
	return file_rpc_user_proto_rawDescGZIP(), []int{8}
}

func (x *VerifyPasswordResp) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

type Friend struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`             // 用户ID（我）
	FriendId      uint64                 `protobuf:"varint,2,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"`       // 好友ID（对方）
	Remark        string                 `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`                            // 好友备注名
	Source        int32                  `protobuf:"varint,4,opt,name=source,proto3" json:"source,omitempty"`                           // 好友来源
	Blocked       bool                   `protobuf:"varint,5,opt,name=blocked,proto3" json:"blocked,omitempty"`                         // 是否拉黑
	Starred       bool                   `protobuf:"varint,6,opt,name=starred,proto3" json:"starred,omitempty"`                         // 是否星标
	CreateTime    int64                  `protobuf:"varint,9,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"` // 成为好友时间
	Extra         string                 `protobuf:"bytes,10,opt,name=extra,proto3" json:"extra,omitempty"`                             // 扩展字段
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Friend) Reset() {
	*x = Friend{}
	mi := &file_rpc_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Friend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Friend) ProtoMessage() {}

func (x *Friend) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Friend.ProtoReflect.Descriptor instead.
func (*Friend) Descriptor() ([]byte, []int) {
	return file_rpc_user_proto_rawDescGZIP(), []int{9}
}

func (x *Friend) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Friend) GetFriendId() uint64 {
	if x != nil {
		return x.FriendId
	}
	return 0
}

func (x *Friend) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *Friend) GetSource() int32 {
	if x != nil {
		return x.Source
	}
	return 0
}

func (x *Friend) GetBlocked() bool {
	if x != nil {
		return x.Blocked
	}
	return false
}

func (x *Friend) GetStarred() bool {
	if x != nil {
		return x.Starred
	}
	return false
}

func (x *Friend) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *Friend) GetExtra() string {
	if x != nil {
		return x.Extra
	}
	return ""
}

type FriendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                        // 申请记录ID
	FromUserId    uint64                 `protobuf:"varint,2,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`    // 申请人ID
	ToUserId      uint64                 `protobuf:"varint,3,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`          // 接收人ID
	ApplyMsg      string                 `protobuf:"bytes,4,opt,name=apply_msg,json=applyMsg,proto3" json:"apply_msg,omitempty"`             // 申请理由
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`                                // 申请状态
	Source        int32                  `protobuf:"varint,6,opt,name=source,proto3" json:"source,omitempty"`                                // 申请来源
	RequestTime   int64                  `protobuf:"varint,7,opt,name=request_time,json=requestTime,proto3" json:"request_time,omitempty"`   // 申请时间
	HandleTime    int64                  `protobuf:"varint,8,opt,name=handle_time,json=handleTime,proto3" json:"handle_time,omitempty"`      // 处理时间
	RejectReason  string                 `protobuf:"bytes,9,opt,name=reject_reason,json=rejectReason,proto3" json:"reject_reason,omitempty"` // 拒绝原因
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendRequest) Reset() {
	*x = FriendRequest{}
	mi := &file_rpc_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendRequest) ProtoMessage() {}

func (x *FriendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendRequest.ProtoReflect.Descriptor instead.
func (*FriendRequest) Descriptor() ([]byte, []int) {
	return file_rpc_user_proto_rawDescGZIP(), []int{10}
}

func (x *FriendRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FriendRequest) GetFromUserId() uint64 {
	if x != nil {
		return x.FromUserId
	}
	return 0
}

func (x *FriendRequest) GetToUserId() uint64 {
	if x != nil {
		return x.ToUserId
	}
	return 0
}

func (x *FriendRequest) GetApplyMsg() string {
	if x != nil {
		return x.ApplyMsg
	}
	return ""
}

func (x *FriendRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *FriendRequest) GetSource() int32 {
	if x != nil {
		return x.Source
	}
	return 0
}

func (x *FriendRequest) GetRequestTime() int64 {
	if x != nil {
		return x.RequestTime
	}
	return 0
}

func (x *FriendRequest) GetHandleTime() int64 {
	if x != nil {
		return x.HandleTime
	}
	return 0
}

func (x *FriendRequest) GetRejectReason() string {
	if x != nil {
		return x.RejectReason
	}
	return ""
}

type GetFriendsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFriendsReq) Reset() {
	*x = GetFriendsReq{}
	mi := &file_rpc_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFriendsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFriendsReq) ProtoMessage() {}

func (x *GetFriendsReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFriendsReq.ProtoReflect.Descriptor instead.
func (*GetFriendsReq) Descriptor() ([]byte, []int) {
	return file_rpc_user_proto_rawDescGZIP(), []int{11}
}

func (x *GetFriendsReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetFriendsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Friend              `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFriendsResp) Reset() {
	*x = GetFriendsResp{}
	mi := &file_rpc_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFriendsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFriendsResp) ProtoMessage() {}

func (x *GetFriendsResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFriendsResp.ProtoReflect.Descriptor instead.
func (*GetFriendsResp) Descriptor() ([]byte, []int) {
	return file_rpc_user_proto_rawDescGZIP(), []int{12}
}

func (x *GetFriendsResp) GetData() []*Friend {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateFriendReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FriendId      uint64                 `protobuf:"varint,2,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"`
	Remark        string                 `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`
	Source        int32                  `protobuf:"varint,4,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFriendReq) Reset() {
	*x = CreateFriendReq{}
	mi := &file_rpc_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFriendReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFriendReq) ProtoMessage() {}

func (x *CreateFriendReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFriendReq.ProtoReflect.Descriptor instead.
func (*CreateFriendReq) Descriptor() ([]byte, []int) {
	return file_rpc_user_proto_rawDescGZIP(), []int{13}
}

func (x *CreateFriendReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateFriendReq) GetFriendId() uint64 {
	if x != nil {
		return x.FriendId
	}
	return 0
}

func (x *CreateFriendReq) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *CreateFriendReq) GetSource() int32 {
	if x != nil {
		return x.Source
	}
	return 0
}

type CreateFriendResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *Friend                `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFriendResp) Reset() {
	*x = CreateFriendResp{}
	mi := &file_rpc_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFriendResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFriendResp) ProtoMessage() {}

func (x *CreateFriendResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFriendResp.ProtoReflect.Descriptor instead.
func (*CreateFriendResp) Descriptor() ([]byte, []int) {
	return file_rpc_user_proto_rawDescGZIP(), []int{14}
}

func (x *CreateFriendResp) GetData() *Friend {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateFriendReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FriendId      uint64                 `protobuf:"varint,2,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"`
	Remark        string                 `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`
	Blocked       bool                   `protobuf:"varint,4,opt,name=blocked,proto3" json:"blocked,omitempty"`
	Starred       bool                   `protobuf:"varint,5,opt,name=starred,proto3" json:"starred,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFriendReq) Reset() {
	*x = UpdateFriendReq{}
	mi := &file_rpc_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFriendReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFriendReq) ProtoMessage() {}

func (x *UpdateFriendReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFriendReq.ProtoReflect.Descriptor instead.
func (*UpdateFriendReq) Descriptor() ([]byte, []int) {
	return file_rpc_user_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateFriendReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateFriendReq) GetFriendId() uint64 {
	if x != nil {
		return x.FriendId
	}
	return 0
}

func (x *UpdateFriendReq) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *UpdateFriendReq) GetBlocked() bool {
	if x != nil {
		return x.Blocked
	}
	return false
}

func (x *UpdateFriendReq) GetStarred() bool {
	if x != nil {
		return x.Starred
	}
	return false
}

type DeleteFriendReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FriendId      uint64                 `protobuf:"varint,2,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFriendReq) Reset() {
	*x = DeleteFriendReq{}
	mi := &file_rpc_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFriendReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFriendReq) ProtoMessage() {}

func (x *DeleteFriendReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFriendReq.ProtoReflect.Descriptor instead.
func (*DeleteFriendReq) Descriptor() ([]byte, []int) {
	return file_rpc_user_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteFriendReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeleteFriendReq) GetFriendId() uint64 {
	if x != nil {
		return x.FriendId
	}
	return 0
}

type NewFriendApplyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromUserId    uint64                 `protobuf:"varint,1,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	ToUserId      uint64                 `protobuf:"varint,2,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`
	ApplyMsg      string                 `protobuf:"bytes,3,opt,name=apply_msg,json=applyMsg,proto3" json:"apply_msg,omitempty"`
	Source        int32                  `protobuf:"varint,4,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewFriendApplyReq) Reset() {
	*x = NewFriendApplyReq{}
	mi := &file_rpc_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewFriendApplyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewFriendApplyReq) ProtoMessage() {}

func (x *NewFriendApplyReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewFriendApplyReq.ProtoReflect.Descriptor instead.
func (*NewFriendApplyReq) Descriptor() ([]byte, []int) {
	return file_rpc_user_proto_rawDescGZIP(), []int{17}
}

func (x *NewFriendApplyReq) GetFromUserId() uint64 {
	if x != nil {
		return x.FromUserId
	}
	return 0
}

func (x *NewFriendApplyReq) GetToUserId() uint64 {
	if x != nil {
		return x.ToUserId
	}
	return 0
}

func (x *NewFriendApplyReq) GetApplyMsg() string {
	if x != nil {
		return x.ApplyMsg
	}
	return ""
}

func (x *NewFriendApplyReq) GetSource() int32 {
	if x != nil {
		return x.Source
	}
	return 0
}

type NewFriendApplyResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *FriendRequest         `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Friend        *Friend                `protobuf:"bytes,2,opt,name=friend,proto3" json:"friend,omitempty"` // Returns Friend if join_type is Direct
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewFriendApplyResp) Reset() {
	*x = NewFriendApplyResp{}
	mi := &file_rpc_user_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewFriendApplyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewFriendApplyResp) ProtoMessage() {}

func (x *NewFriendApplyResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_user_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewFriendApplyResp.ProtoReflect.Descriptor instead.
func (*NewFriendApplyResp) Descriptor() ([]byte, []int) {
	return file_rpc_user_proto_rawDescGZIP(), []int{18}
}

func (x *NewFriendApplyResp) GetData() *FriendRequest {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *NewFriendApplyResp) GetFriend() *Friend {
	if x != nil {
		return x.Friend
	}
	return nil
}

type HandleFriendApplyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                        // 申请记录ID
	OperatorId    uint64                 `protobuf:"varint,2,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`      // 操作者ID
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`                                // 处理结果
	RejectReason  string                 `protobuf:"bytes,4,opt,name=reject_reason,json=rejectReason,proto3" json:"reject_reason,omitempty"` // 拒绝原因
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleFriendApplyReq) Reset() {
	*x = HandleFriendApplyReq{}
	mi := &file_rpc_user_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleFriendApplyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleFriendApplyReq) ProtoMessage() {}

func (x *HandleFriendApplyReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_user_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleFriendApplyReq.ProtoReflect.Descriptor instead.
func (*HandleFriendApplyReq) Descriptor() ([]byte, []int) {
	return file_rpc_user_proto_rawDescGZIP(), []int{19}
}

func (x *HandleFriendApplyReq) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *HandleFriendApplyReq) GetOperatorId() uint64 {
	if x != nil {
		return x.OperatorId
	}
	return 0
}

func (x *HandleFriendApplyReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *HandleFriendApplyReq) GetRejectReason() string {
	if x != nil {
		return x.RejectReason
	}
	return ""
}

type HandleFriendApplyResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *FriendRequest         `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleFriendApplyResp) Reset() {
	*x = HandleFriendApplyResp{}
	mi := &file_rpc_user_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleFriendApplyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleFriendApplyResp) ProtoMessage() {}

func (x *HandleFriendApplyResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_user_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleFriendApplyResp.ProtoReflect.Descriptor instead.
func (*HandleFriendApplyResp) Descriptor() ([]byte, []int) {
	return file_rpc_user_proto_rawDescGZIP(), []int{20}
}

func (x *HandleFriendApplyResp) GetData() *FriendRequest {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetPendingFriendAppliesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPendingFriendAppliesReq) Reset() {
	*x = GetPendingFriendAppliesReq{}
	mi := &file_rpc_user_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPendingFriendAppliesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPendingFriendAppliesReq) ProtoMessage() {}

func (x *GetPendingFriendAppliesReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_user_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPendingFriendAppliesReq.ProtoReflect.Descriptor instead.
func (*GetPendingFriendAppliesReq) Descriptor() ([]byte, []int) {
	return file_rpc_user_proto_rawDescGZIP(), []int{21}
}

func (x *GetPendingFriendAppliesReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetPendingFriendAppliesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*FriendRequest       `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPendingFriendAppliesResp) Reset() {
	*x = GetPendingFriendAppliesResp{}
	mi := &file_rpc_user_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPendingFriendAppliesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPendingFriendAppliesResp) ProtoMessage() {}

func (x *GetPendingFriendAppliesResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_user_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPendingFriendAppliesResp.ProtoReflect.Descriptor instead.
func (*GetPendingFriendAppliesResp) Descriptor() ([]byte, []int) {
	return file_rpc_user_proto_rawDescGZIP(), []int{22}
}

func (x *GetPendingFriendAppliesResp) GetData() []*FriendRequest {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_rpc_user_proto protoreflect.FileDescriptor

const file_rpc_user_proto_rawDesc = "" +
	"\n" +
	"\x0erpc/user.proto\x12\x04user\"\v\n" +
	"\tEmptyResp\"\xac\x02\n" +
	"\bUserInfo\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1b\n" +
	"\tuser_name\x18\x02 \x01(\tR\buserName\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12\x16\n" +
	"\x06gender\x18\x04 \x01(\x05R\x06gender\x12\x14\n" +
	"\x05phone\x18\x05 \x01(\tR\x05phone\x12\x1b\n" +
	"\tjoin_type\x18\x06 \x01(\x05R\bjoinType\x12-\n" +
	"\x12personal_signature\x18\a \x01(\tR\x11personalSignature\x12\x16\n" +
	"\x06status\x18\b \x01(\x05R\x06status\x12\x1f\n" +
	"\vcreate_time\x18\t \x01(\x03R\n" +
	"createTime\x12\x1f\n" +
	"\vupdate_time\x18\n" +
	" \x01(\x03R\n" +
	"updateTime\"\xd1\x01\n" +
	"\rCreateUserReq\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06gender\x18\x03 \x01(\x05R\x06gender\x12\x1b\n" +
	"\tjoin_type\x18\x04 \x01(\x05R\bjoinType\x12\x16\n" +
	"\x06avatar\x18\x05 \x01(\tR\x06avatar\x12-\n" +
	"\x12personal_signature\x18\x06 \x01(\tR\x11personalSignature\x12\x1a\n" +
	"\bpassword\x18\a \x01(\tR\bpassword\")\n" +
	"\x0eCreateUserResp\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"z\n" +
	"\x0eGetUserInfoReq\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x04R\x03ids\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x05R\x06offset\"5\n" +
	"\x0fGetUserInfoResp\x12\"\n" +
	"\x04data\x18\x01 \x03(\v2\x0e.user.UserInfoR\x04data\"\xb8\x01\n" +
	"\rUpdateInfoReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06gender\x18\x03 \x01(\x05R\x06gender\x12\x1b\n" +
	"\tjoin_type\x18\x04 \x01(\x05R\bjoinType\x12\x16\n" +
	"\x06avatar\x18\x05 \x01(\tR\x06avatar\x12-\n" +
	"\x12personal_signature\x18\x06 \x01(\tR\x11personalSignature\"H\n" +
	"\x11VerifyPasswordReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"*\n" +
	"\x12VerifyPasswordResp\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\"\xd9\x01\n" +
	"\x06Friend\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1b\n" +
	"\tfriend_id\x18\x02 \x01(\x04R\bfriendId\x12\x16\n" +
	"\x06remark\x18\x03 \x01(\tR\x06remark\x12\x16\n" +
	"\x06source\x18\x04 \x01(\x05R\x06source\x12\x18\n" +
	"\ablocked\x18\x05 \x01(\bR\ablocked\x12\x18\n" +
	"\astarred\x18\x06 \x01(\bR\astarred\x12\x1f\n" +
	"\vcreate_time\x18\t \x01(\x03R\n" +
	"createTime\x12\x14\n" +
	"\x05extra\x18\n" +
	" \x01(\tR\x05extra\"\x95\x02\n" +
	"\rFriendRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12 \n" +
	"\ffrom_user_id\x18\x02 \x01(\x04R\n" +
	"fromUserId\x12\x1c\n" +
	"\n" +
	"to_user_id\x18\x03 \x01(\x04R\btoUserId\x12\x1b\n" +
	"\tapply_msg\x18\x04 \x01(\tR\bapplyMsg\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\x12\x16\n" +
	"\x06source\x18\x06 \x01(\x05R\x06source\x12!\n" +
	"\frequest_time\x18\a \x01(\x03R\vrequestTime\x12\x1f\n" +
	"\vhandle_time\x18\b \x01(\x03R\n" +
	"handleTime\x12#\n" +
	"\rreject_reason\x18\t \x01(\tR\frejectReason\"(\n" +
	"\rGetFriendsReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"2\n" +
	"\x0eGetFriendsResp\x12 \n" +
	"\x04data\x18\x01 \x03(\v2\f.user.FriendR\x04data\"w\n" +
	"\x0fCreateFriendReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1b\n" +
	"\tfriend_id\x18\x02 \x01(\x04R\bfriendId\x12\x16\n" +
	"\x06remark\x18\x03 \x01(\tR\x06remark\x12\x16\n" +
	"\x06source\x18\x04 \x01(\x05R\x06source\"4\n" +
	"\x10CreateFriendResp\x12 \n" +
	"\x04data\x18\x01 \x01(\v2\f.user.FriendR\x04data\"\x93\x01\n" +
	"\x0fUpdateFriendReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1b\n" +
	"\tfriend_id\x18\x02 \x01(\x04R\bfriendId\x12\x16\n" +
	"\x06remark\x18\x03 \x01(\tR\x06remark\x12\x18\n" +
	"\ablocked\x18\x04 \x01(\bR\ablocked\x12\x18\n" +
	"\astarred\x18\x05 \x01(\bR\astarred\"G\n" +
	"\x0fDeleteFriendReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1b\n" +
	"\tfriend_id\x18\x02 \x01(\x04R\bfriendId\"\x88\x01\n" +
	"\x11NewFriendApplyReq\x12 \n" +
	"\ffrom_user_id\x18\x01 \x01(\x04R\n" +
	"fromUserId\x12\x1c\n" +
	"\n" +
	"to_user_id\x18\x02 \x01(\x04R\btoUserId\x12\x1b\n" +
	"\tapply_msg\x18\x03 \x01(\tR\bapplyMsg\x12\x16\n" +
	"\x06source\x18\x04 \x01(\x05R\x06source\"c\n" +
	"\x12NewFriendApplyResp\x12'\n" +
	"\x04data\x18\x01 \x01(\v2\x13.user.FriendRequestR\x04data\x12$\n" +
	"\x06friend\x18\x02 \x01(\v2\f.user.FriendR\x06friend\"\x84\x01\n" +
	"\x14HandleFriendApplyReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1f\n" +
	"\voperator_id\x18\x02 \x01(\x04R\n" +
	"operatorId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\x12#\n" +
	"\rreject_reason\x18\x04 \x01(\tR\frejectReason\"@\n" +
	"\x15HandleFriendApplyResp\x12'\n" +
	"\x04data\x18\x01 \x01(\v2\x13.user.FriendRequestR\x04data\"5\n" +
	"\x1aGetPendingFriendAppliesReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"F\n" +
	"\x1bGetPendingFriendAppliesResp\x12'\n" +
	"\x04data\x18\x01 \x03(\v2\x13.user.FriendRequestR\x04data2\xcf\x05\n" +
	"\x04User\x127\n" +
	"\n" +
	"CreateUser\x12\x13.user.CreateUserReq\x1a\x14.user.CreateUserResp\x12:\n" +
	"\vGetUserInfo\x12\x14.user.GetUserInfoReq\x1a\x15.user.GetUserInfoResp\x122\n" +
	"\n" +
	"UpdateInfo\x12\x13.user.UpdateInfoReq\x1a\x0f.user.EmptyResp\x12C\n" +
	"\x0eVerifyPassword\x12\x17.user.VerifyPasswordReq\x1a\x18.user.VerifyPasswordResp\x127\n" +
	"\n" +
	"GetFriends\x12\x13.user.GetFriendsReq\x1a\x14.user.GetFriendsResp\x12=\n" +
	"\fCreateFriend\x12\x15.user.CreateFriendReq\x1a\x16.user.CreateFriendResp\x126\n" +
	"\fUpdateFriend\x12\x15.user.UpdateFriendReq\x1a\x0f.user.EmptyResp\x126\n" +
	"\fDeleteFriend\x12\x15.user.DeleteFriendReq\x1a\x0f.user.EmptyResp\x12C\n" +
	"\x0eNewFriendApply\x12\x17.user.NewFriendApplyReq\x1a\x18.user.NewFriendApplyResp\x12L\n" +
	"\x11HandleFriendApply\x12\x1a.user.HandleFriendApplyReq\x1a\x1b.user.HandleFriendApplyResp\x12^\n" +
	"\x17GetPendingFriendApplies\x12 .user.GetPendingFriendAppliesReq\x1a!.user.GetPendingFriendAppliesRespB\bZ\x06./userb\x06proto3"

var (
	file_rpc_user_proto_rawDescOnce sync.Once
	file_rpc_user_proto_rawDescData []byte
)

func file_rpc_user_proto_rawDescGZIP() []byte {
	file_rpc_user_proto_rawDescOnce.Do(func() {
		file_rpc_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_user_proto_rawDesc), len(file_rpc_user_proto_rawDesc)))
	})
	return file_rpc_user_proto_rawDescData
}

var file_rpc_user_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_rpc_user_proto_goTypes = []any{
	(*EmptyResp)(nil),                   // 0: user.EmptyResp
	(*UserInfo)(nil),                    // 1: user.UserInfo
	(*CreateUserReq)(nil),               // 2: user.CreateUserReq
	(*CreateUserResp)(nil),              // 3: user.CreateUserResp
	(*GetUserInfoReq)(nil),              // 4: user.GetUserInfoReq
	(*GetUserInfoResp)(nil),             // 5: user.GetUserInfoResp
	(*UpdateInfoReq)(nil),               // 6: user.UpdateInfoReq
	(*VerifyPasswordReq)(nil),           // 7: user.VerifyPasswordReq
	(*VerifyPasswordResp)(nil),          // 8: user.VerifyPasswordResp
	(*Friend)(nil),                      // 9: user.Friend
	(*FriendRequest)(nil),               // 10: user.FriendRequest
	(*GetFriendsReq)(nil),               // 11: user.GetFriendsReq
	(*GetFriendsResp)(nil),              // 12: user.GetFriendsResp
	(*CreateFriendReq)(nil),             // 13: user.CreateFriendReq
	(*CreateFriendResp)(nil),            // 14: user.CreateFriendResp
	(*UpdateFriendReq)(nil),             // 15: user.UpdateFriendReq
	(*DeleteFriendReq)(nil),             // 16: user.DeleteFriendReq
	(*NewFriendApplyReq)(nil),           // 17: user.NewFriendApplyReq
	(*NewFriendApplyResp)(nil),          // 18: user.NewFriendApplyResp
	(*HandleFriendApplyReq)(nil),        // 19: user.HandleFriendApplyReq
	(*HandleFriendApplyResp)(nil),       // 20: user.HandleFriendApplyResp
	(*GetPendingFriendAppliesReq)(nil),  // 21: user.GetPendingFriendAppliesReq
	(*GetPendingFriendAppliesResp)(nil), // 22: user.GetPendingFriendAppliesResp
}
var file_rpc_user_proto_depIdxs = []int32{
	1,  // 0: user.GetUserInfoResp.data:type_name -> user.UserInfo
	9,  // 1: user.GetFriendsResp.data:type_name -> user.Friend
	9,  // 2: user.CreateFriendResp.data:type_name -> user.Friend
	10, // 3: user.NewFriendApplyResp.data:type_name -> user.FriendRequest
	9,  // 4: user.NewFriendApplyResp.friend:type_name -> user.Friend
	10, // 5: user.HandleFriendApplyResp.data:type_name -> user.FriendRequest
	10, // 6: user.GetPendingFriendAppliesResp.data:type_name -> user.FriendRequest
	2,  // 7: user.User.CreateUser:input_type -> user.CreateUserReq
	4,  // 8: user.User.GetUserInfo:input_type -> user.GetUserInfoReq
	6,  // 9: user.User.UpdateInfo:input_type -> user.UpdateInfoReq
	7,  // 10: user.User.VerifyPassword:input_type -> user.VerifyPasswordReq
	11, // 11: user.User.GetFriends:input_type -> user.GetFriendsReq
	13, // 12: user.User.CreateFriend:input_type -> user.CreateFriendReq
	15, // 13: user.User.UpdateFriend:input_type -> user.UpdateFriendReq
	16, // 14: user.User.DeleteFriend:input_type -> user.DeleteFriendReq
	17, // 15: user.User.NewFriendApply:input_type -> user.NewFriendApplyReq
	19, // 16: user.User.HandleFriendApply:input_type -> user.HandleFriendApplyReq
	21, // 17: user.User.GetPendingFriendApplies:input_type -> user.GetPendingFriendAppliesReq
	3,  // 18: user.User.CreateUser:output_type -> user.CreateUserResp
	5,  // 19: user.User.GetUserInfo:output_type -> user.GetUserInfoResp
	0,  // 20: user.User.UpdateInfo:output_type -> user.EmptyResp
	8,  // 21: user.User.VerifyPassword:output_type -> user.VerifyPasswordResp
	12, // 22: user.User.GetFriends:output_type -> user.GetFriendsResp
	14, // 23: user.User.CreateFriend:output_type -> user.CreateFriendResp
	0,  // 24: user.User.UpdateFriend:output_type -> user.EmptyResp
	0,  // 25: user.User.DeleteFriend:output_type -> user.EmptyResp
	18, // 26: user.User.NewFriendApply:output_type -> user.NewFriendApplyResp
	20, // 27: user.User.HandleFriendApply:output_type -> user.HandleFriendApplyResp
	22, // 28: user.User.GetPendingFriendApplies:output_type -> user.GetPendingFriendAppliesResp
	18, // [18:29] is the sub-list for method output_type
	7,  // [7:18] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_rpc_user_proto_init() }
func file_rpc_user_proto_init() {
	if File_rpc_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_user_proto_rawDesc), len(file_rpc_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_user_proto_goTypes,
		DependencyIndexes: file_rpc_user_proto_depIdxs,
		MessageInfos:      file_rpc_user_proto_msgTypes,
	}.Build()
	File_rpc_user_proto = out.File
	file_rpc_user_proto_goTypes = nil
	file_rpc_user_proto_depIdxs = nil
}
