// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type CreateFriendReq struct {
	FriendID uint64 `json:"friend_id"`
	Source   int8   `json:"source,optional"`
	Remark   string `json:"remark,optional"`
}

type DeleteFriendReq struct {
	FriendID uint64 `json:"friend_id"`
}

type Friend struct {
	UserID     uint64 `json:"user_id"`     // 用户ID（我）
	FriendID   uint64 `json:"friend_id"`   // 好友ID（对方）
	Remark     string `json:"remark"`      // 好友备注名
	Source     int8   `json:"source"`      // 来源
	Blocked    bool   `json:"blocked"`     // 是否拉黑
	Starred    bool   `json:"starred"`     // 是否星标
	CreateTime int64  `json:"create_time"` // 成为好友时间
	Extra      string `json:"extra"`       // 扩展字段
}

type FriendRequest struct {
	RequestID    uint64 `json:"request_id"`
	FromUserID   uint64 `json:"from_user_id"`
	ToUserID     uint64 `json:"to_user_id"`
	ApplyMsg     string `json:"apply_msg"`
	Status       int    `json:"status"` // 1待处理 2已同意 3已拒绝 4已忽略
	Source       int8   `json:"source"`
	RequestTime  int64  `json:"request_time"`
	HandleTime   int64  `json:"handle_time"`
	RejectReason string `json:"reject_reason"`
}

type GetFriendsReq struct {
}

type GetFriendsResp struct {
	Data []Friend `json:"data"`
}

type GetPendingFriendAppliesReq struct {
}

type GetPendingFriendAppliesResp struct {
	Data []FriendRequest `json:"data"`
}

type GetUserInfoReq struct {
	IDs    []uint64 `form:"ids,optional"`
	Phone  string   `form:"phone,optional"`
	Name   string   `form:"name,optional"`
	Limit  int      `form:"limit,optional,default=20"`
	Offset int      `form:"offset,optional,default=0"`
}

type GetUserInfoResp struct {
	Data []UserInfo `json:"data"`
}

type HandleFriendApplyReq struct {
	RequestID    uint64 `json:"request_id"`
	Result       int    `json:"result"` // 2同意 3拒绝
	RejectReason string `json:"reject_reason,optional"`
}

type NewFriendApplyReq struct {
	ToUserID uint64 `json:"to_user_id"`
	ApplyMsg string `json:"apply_msg,optional"`
	Source   int8   `json:"source,optional"`
}

type NewFriendApplyResp struct {
	Data FriendRequest `json:"data"`
}

type SearchFriendReq struct {
	Name   string `form:"name,optional"`
	ID     uint64 `form:"id,optional"`
	Phone  string `form:"phone,optional"`
	Limit  int    `form:"limit,optional,default=30"`
	Offset int    `form:"offset,optional,default=0"`
}

type SearchFriendResp struct {
	Data  []UserInfo `json:"data"`
	Total int64      `json:"total"`
}

type UpdateFriendReq struct {
	FriendID uint64 `json:"friend_id"`
	Remark   string `json:"remark,optional"`
	Blocked  *bool  `json:"blocked,optional"`
	Starred  *bool  `json:"starred,optional"`
}

type UpdateInfoReq struct {
	Name              string `json:"user_name,optional"`
	Gender            int    `json:"gender,optional"`
	Avatar            string `json:"avatar,optional"`
	JoinType          int    `json:"join_type,optional"`
	PersonalSignature string `json:"personal_signature,optional"`
}

type UserInfo struct {
	UserID            uint64 `json:"user_id"`
	UserName          string `json:"user_name"`
	Avatar            string `json:"avatar"`
	Gender            int32  `json:"gender"`
	Phone             string `json:"phone"`
	JoinType          int32  `json:"join_type"`
	PersonalSignature string `json:"personal_signature"`
	Status            int32  `json:"status"`
	CreateTime        int64  `json:"create_time"`
	UpdateTime        int64  `json:"update_time"`
}
