// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.31.1
// source: rpc/message.proto

package message

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MessageRpc_GetHistory_FullMethodName            = "/messagerpc.MessageRpc/GetHistory"
	MessageRpc_UpdateSession_FullMethodName         = "/messagerpc.MessageRpc/UpdateSession"
	MessageRpc_GetUserSessions_FullMethodName       = "/messagerpc.MessageRpc/GetUserSessions"
	MessageRpc_GetUserActiveSessions_FullMethodName = "/messagerpc.MessageRpc/GetUserActiveSessions"
	MessageRpc_MarkSessionRead_FullMethodName       = "/messagerpc.MessageRpc/MarkSessionRead"
	MessageRpc_GetSession_FullMethodName            = "/messagerpc.MessageRpc/GetSession"
)

// MessageRpcClient is the client API for MessageRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MessageRpcClient interface {
	GetHistory(ctx context.Context, in *GetHistoryReq, opts ...grpc.CallOption) (*GetHistoryResp, error)
	UpdateSession(ctx context.Context, in *UpdateSessionReq, opts ...grpc.CallOption) (*UpdateSessionResp, error)
	GetUserSessions(ctx context.Context, in *GetUserSessionsReq, opts ...grpc.CallOption) (*GetUserSessionsResp, error)
	GetUserActiveSessions(ctx context.Context, in *GetUserActiveSessionsReq, opts ...grpc.CallOption) (*GetUserActiveSessionsResp, error)
	MarkSessionRead(ctx context.Context, in *MarkSessionReadReq, opts ...grpc.CallOption) (*MarkSessionReadResp, error)
	// 内部会话管理接口
	GetSession(ctx context.Context, in *GetSessionReq, opts ...grpc.CallOption) (*GetSessionResp, error)
}

type messageRpcClient struct {
	cc grpc.ClientConnInterface
}

func NewMessageRpcClient(cc grpc.ClientConnInterface) MessageRpcClient {
	return &messageRpcClient{cc}
}

func (c *messageRpcClient) GetHistory(ctx context.Context, in *GetHistoryReq, opts ...grpc.CallOption) (*GetHistoryResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHistoryResp)
	err := c.cc.Invoke(ctx, MessageRpc_GetHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageRpcClient) UpdateSession(ctx context.Context, in *UpdateSessionReq, opts ...grpc.CallOption) (*UpdateSessionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSessionResp)
	err := c.cc.Invoke(ctx, MessageRpc_UpdateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageRpcClient) GetUserSessions(ctx context.Context, in *GetUserSessionsReq, opts ...grpc.CallOption) (*GetUserSessionsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserSessionsResp)
	err := c.cc.Invoke(ctx, MessageRpc_GetUserSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageRpcClient) GetUserActiveSessions(ctx context.Context, in *GetUserActiveSessionsReq, opts ...grpc.CallOption) (*GetUserActiveSessionsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserActiveSessionsResp)
	err := c.cc.Invoke(ctx, MessageRpc_GetUserActiveSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageRpcClient) MarkSessionRead(ctx context.Context, in *MarkSessionReadReq, opts ...grpc.CallOption) (*MarkSessionReadResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarkSessionReadResp)
	err := c.cc.Invoke(ctx, MessageRpc_MarkSessionRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageRpcClient) GetSession(ctx context.Context, in *GetSessionReq, opts ...grpc.CallOption) (*GetSessionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSessionResp)
	err := c.cc.Invoke(ctx, MessageRpc_GetSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessageRpcServer is the server API for MessageRpc service.
// All implementations must embed UnimplementedMessageRpcServer
// for forward compatibility.
type MessageRpcServer interface {
	GetHistory(context.Context, *GetHistoryReq) (*GetHistoryResp, error)
	UpdateSession(context.Context, *UpdateSessionReq) (*UpdateSessionResp, error)
	GetUserSessions(context.Context, *GetUserSessionsReq) (*GetUserSessionsResp, error)
	GetUserActiveSessions(context.Context, *GetUserActiveSessionsReq) (*GetUserActiveSessionsResp, error)
	MarkSessionRead(context.Context, *MarkSessionReadReq) (*MarkSessionReadResp, error)
	// 内部会话管理接口
	GetSession(context.Context, *GetSessionReq) (*GetSessionResp, error)
	mustEmbedUnimplementedMessageRpcServer()
}

// UnimplementedMessageRpcServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMessageRpcServer struct{}

func (UnimplementedMessageRpcServer) GetHistory(context.Context, *GetHistoryReq) (*GetHistoryResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHistory not implemented")
}
func (UnimplementedMessageRpcServer) UpdateSession(context.Context, *UpdateSessionReq) (*UpdateSessionResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSession not implemented")
}
func (UnimplementedMessageRpcServer) GetUserSessions(context.Context, *GetUserSessionsReq) (*GetUserSessionsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserSessions not implemented")
}
func (UnimplementedMessageRpcServer) GetUserActiveSessions(context.Context, *GetUserActiveSessionsReq) (*GetUserActiveSessionsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserActiveSessions not implemented")
}
func (UnimplementedMessageRpcServer) MarkSessionRead(context.Context, *MarkSessionReadReq) (*MarkSessionReadResp, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkSessionRead not implemented")
}
func (UnimplementedMessageRpcServer) GetSession(context.Context, *GetSessionReq) (*GetSessionResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSession not implemented")
}
func (UnimplementedMessageRpcServer) mustEmbedUnimplementedMessageRpcServer() {}
func (UnimplementedMessageRpcServer) testEmbeddedByValue()                    {}

// UnsafeMessageRpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessageRpcServer will
// result in compilation errors.
type UnsafeMessageRpcServer interface {
	mustEmbedUnimplementedMessageRpcServer()
}

func RegisterMessageRpcServer(s grpc.ServiceRegistrar, srv MessageRpcServer) {
	// If the following call panics, it indicates UnimplementedMessageRpcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MessageRpc_ServiceDesc, srv)
}

func _MessageRpc_GetHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHistoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageRpcServer).GetHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageRpc_GetHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageRpcServer).GetHistory(ctx, req.(*GetHistoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageRpc_UpdateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSessionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageRpcServer).UpdateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageRpc_UpdateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageRpcServer).UpdateSession(ctx, req.(*UpdateSessionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageRpc_GetUserSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserSessionsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageRpcServer).GetUserSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageRpc_GetUserSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageRpcServer).GetUserSessions(ctx, req.(*GetUserSessionsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageRpc_GetUserActiveSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserActiveSessionsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageRpcServer).GetUserActiveSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageRpc_GetUserActiveSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageRpcServer).GetUserActiveSessions(ctx, req.(*GetUserActiveSessionsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageRpc_MarkSessionRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkSessionReadReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageRpcServer).MarkSessionRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageRpc_MarkSessionRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageRpcServer).MarkSessionRead(ctx, req.(*MarkSessionReadReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageRpc_GetSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageRpcServer).GetSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageRpc_GetSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageRpcServer).GetSession(ctx, req.(*GetSessionReq))
	}
	return interceptor(ctx, in, info, handler)
}

// MessageRpc_ServiceDesc is the grpc.ServiceDesc for MessageRpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MessageRpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "messagerpc.MessageRpc",
	HandlerType: (*MessageRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetHistory",
			Handler:    _MessageRpc_GetHistory_Handler,
		},
		{
			MethodName: "UpdateSession",
			Handler:    _MessageRpc_UpdateSession_Handler,
		},
		{
			MethodName: "GetUserSessions",
			Handler:    _MessageRpc_GetUserSessions_Handler,
		},
		{
			MethodName: "GetUserActiveSessions",
			Handler:    _MessageRpc_GetUserActiveSessions_Handler,
		},
		{
			MethodName: "MarkSessionRead",
			Handler:    _MessageRpc_MarkSessionRead_Handler,
		},
		{
			MethodName: "GetSession",
			Handler:    _MessageRpc_GetSession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc/message.proto",
}
