// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: rpc/message.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         string                 `protobuf:"bytes,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	FromUserId    uint64                 `protobuf:"varint,4,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	MsgType       int32                  `protobuf:"varint,5,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`
	Seq           uint64                 `protobuf:"varint,6,opt,name=seq,proto3" json:"seq,omitempty"`
	Content       string                 `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	MediaUrl      string                 `protobuf:"bytes,8,opt,name=media_url,json=mediaUrl,proto3" json:"media_url,omitempty"`
	Extra         []byte                 `protobuf:"bytes,9,opt,name=extra,proto3" json:"extra,omitempty"`
	Status        int32                  `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty"`
	CreateTime    int64                  `protobuf:"varint,11,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_rpc_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_rpc_message_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *Message) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *Message) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Message) GetFromUserId() uint64 {
	if x != nil {
		return x.FromUserId
	}
	return 0
}

func (x *Message) GetMsgType() int32 {
	if x != nil {
		return x.MsgType
	}
	return 0
}

func (x *Message) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetMediaUrl() string {
	if x != nil {
		return x.MediaUrl
	}
	return ""
}

func (x *Message) GetExtra() []byte {
	if x != nil {
		return x.Extra
	}
	return nil
}

func (x *Message) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Message) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

type Session struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Type          int32                  `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	SessionKey    string                 `protobuf:"bytes,3,opt,name=session_key,json=sessionKey,proto3" json:"session_key,omitempty"`
	MaxSeq        uint64                 `protobuf:"varint,4,opt,name=max_seq,json=maxSeq,proto3" json:"max_seq,omitempty"`
	ActualSeq     uint64                 `protobuf:"varint,5,opt,name=actual_seq,json=actualSeq,proto3" json:"actual_seq,omitempty"`
	LastContent   string                 `protobuf:"bytes,6,opt,name=last_content,json=lastContent,proto3" json:"last_content,omitempty"`
	LastSender    uint64                 `protobuf:"varint,7,opt,name=last_sender,json=lastSender,proto3" json:"last_sender,omitempty"`
	CreateTime    int64                  `protobuf:"varint,8,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime    int64                  `protobuf:"varint,9,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_rpc_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_rpc_message_proto_rawDescGZIP(), []int{1}
}

func (x *Session) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Session) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Session) GetSessionKey() string {
	if x != nil {
		return x.SessionKey
	}
	return ""
}

func (x *Session) GetMaxSeq() uint64 {
	if x != nil {
		return x.MaxSeq
	}
	return 0
}

func (x *Session) GetActualSeq() uint64 {
	if x != nil {
		return x.ActualSeq
	}
	return 0
}

func (x *Session) GetLastContent() string {
	if x != nil {
		return x.LastContent
	}
	return ""
}

func (x *Session) GetLastSender() uint64 {
	if x != nil {
		return x.LastSender
	}
	return 0
}

func (x *Session) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *Session) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

type UserSession struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	IsTop         int32                  `protobuf:"varint,3,opt,name=is_top,json=isTop,proto3" json:"is_top,omitempty"`
	IsDisturb     int32                  `protobuf:"varint,4,opt,name=is_disturb,json=isDisturb,proto3" json:"is_disturb,omitempty"`
	LastReadSeq   uint64                 `protobuf:"varint,5,opt,name=last_read_seq,json=lastReadSeq,proto3" json:"last_read_seq,omitempty"`
	CreateTime    int64                  `protobuf:"varint,6,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime    int64                  `protobuf:"varint,7,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserSession) Reset() {
	*x = UserSession{}
	mi := &file_rpc_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSession) ProtoMessage() {}

func (x *UserSession) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSession.ProtoReflect.Descriptor instead.
func (*UserSession) Descriptor() ([]byte, []int) {
	return file_rpc_message_proto_rawDescGZIP(), []int{2}
}

func (x *UserSession) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserSession) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *UserSession) GetIsTop() int32 {
	if x != nil {
		return x.IsTop
	}
	return 0
}

func (x *UserSession) GetIsDisturb() int32 {
	if x != nil {
		return x.IsDisturb
	}
	return 0
}

func (x *UserSession) GetLastReadSeq() uint64 {
	if x != nil {
		return x.LastReadSeq
	}
	return 0
}

func (x *UserSession) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *UserSession) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

type GetHistoryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	StartSeq      int64                  `protobuf:"varint,2,opt,name=start_seq,json=startSeq,proto3" json:"start_seq,omitempty"`
	EndSeq        int64                  `protobuf:"varint,3,opt,name=end_seq,json=endSeq,proto3" json:"end_seq,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryReq) Reset() {
	*x = GetHistoryReq{}
	mi := &file_rpc_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryReq) ProtoMessage() {}

func (x *GetHistoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryReq.ProtoReflect.Descriptor instead.
func (*GetHistoryReq) Descriptor() ([]byte, []int) {
	return file_rpc_message_proto_rawDescGZIP(), []int{3}
}

func (x *GetHistoryReq) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetHistoryReq) GetStartSeq() int64 {
	if x != nil {
		return x.StartSeq
	}
	return 0
}

func (x *GetHistoryReq) GetEndSeq() int64 {
	if x != nil {
		return x.EndSeq
	}
	return 0
}

func (x *GetHistoryReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetHistoryResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryResp) Reset() {
	*x = GetHistoryResp{}
	mi := &file_rpc_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryResp) ProtoMessage() {}

func (x *GetHistoryResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryResp.ProtoReflect.Descriptor instead.
func (*GetHistoryResp) Descriptor() ([]byte, []int) {
	return file_rpc_message_proto_rawDescGZIP(), []int{4}
}

func (x *GetHistoryResp) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

type GetUserSessionsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserSessionsReq) Reset() {
	*x = GetUserSessionsReq{}
	mi := &file_rpc_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserSessionsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserSessionsReq) ProtoMessage() {}

func (x *GetUserSessionsReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserSessionsReq.ProtoReflect.Descriptor instead.
func (*GetUserSessionsReq) Descriptor() ([]byte, []int) {
	return file_rpc_message_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserSessionsReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserSessionsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*UserSession         `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserSessionsResp) Reset() {
	*x = GetUserSessionsResp{}
	mi := &file_rpc_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserSessionsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserSessionsResp) ProtoMessage() {}

func (x *GetUserSessionsResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserSessionsResp.ProtoReflect.Descriptor instead.
func (*GetUserSessionsResp) Descriptor() ([]byte, []int) {
	return file_rpc_message_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserSessionsResp) GetSessions() []*UserSession {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type UpdateSessionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	IsTop         int32                  `protobuf:"varint,3,opt,name=is_top,json=isTop,proto3" json:"is_top,omitempty"`             // 0:不变更 1:置顶 2:取消置顶
	IsDisturb     int32                  `protobuf:"varint,4,opt,name=is_disturb,json=isDisturb,proto3" json:"is_disturb,omitempty"` // 0:不变更 1:免打扰 2:取消免打扰
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSessionReq) Reset() {
	*x = UpdateSessionReq{}
	mi := &file_rpc_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSessionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSessionReq) ProtoMessage() {}

func (x *UpdateSessionReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSessionReq.ProtoReflect.Descriptor instead.
func (*UpdateSessionReq) Descriptor() ([]byte, []int) {
	return file_rpc_message_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateSessionReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateSessionReq) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *UpdateSessionReq) GetIsTop() int32 {
	if x != nil {
		return x.IsTop
	}
	return 0
}

func (x *UpdateSessionReq) GetIsDisturb() int32 {
	if x != nil {
		return x.IsDisturb
	}
	return 0
}

type UpdateSessionResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSessionResp) Reset() {
	*x = UpdateSessionResp{}
	mi := &file_rpc_message_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSessionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSessionResp) ProtoMessage() {}

func (x *UpdateSessionResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_message_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSessionResp.ProtoReflect.Descriptor instead.
func (*UpdateSessionResp) Descriptor() ([]byte, []int) {
	return file_rpc_message_proto_rawDescGZIP(), []int{8}
}

type GetUserActiveSessionsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserActiveSessionsReq) Reset() {
	*x = GetUserActiveSessionsReq{}
	mi := &file_rpc_message_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserActiveSessionsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserActiveSessionsReq) ProtoMessage() {}

func (x *GetUserActiveSessionsReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_message_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserActiveSessionsReq.ProtoReflect.Descriptor instead.
func (*GetUserActiveSessionsReq) Descriptor() ([]byte, []int) {
	return file_rpc_message_proto_rawDescGZIP(), []int{9}
}

func (x *GetUserActiveSessionsReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetUserActiveSessionsReq) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type GetUserActiveSessionsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*Session             `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserActiveSessionsResp) Reset() {
	*x = GetUserActiveSessionsResp{}
	mi := &file_rpc_message_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserActiveSessionsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserActiveSessionsResp) ProtoMessage() {}

func (x *GetUserActiveSessionsResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_message_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserActiveSessionsResp.ProtoReflect.Descriptor instead.
func (*GetUserActiveSessionsResp) Descriptor() ([]byte, []int) {
	return file_rpc_message_proto_rawDescGZIP(), []int{10}
}

func (x *GetUserActiveSessionsResp) GetSessions() []*Session {
	if x != nil {
		return x.Sessions
	}
	return nil
}

// 根据 session_id 或 conv_key 查询会话；通过 conv_key 查询时若不存在则按给定类型创建
type GetSessionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`        // 按 session_id 查询（精确）
	SessionKey    string                 `protobuf:"bytes,2,opt,name=session_key,json=sessionKey,proto3" json:"session_key,omitempty"`     // 按 session_key 查询（不存在则创建）
	SessionType   int32                  `protobuf:"varint,3,opt,name=session_type,json=sessionType,proto3" json:"session_type,omitempty"` // 仅 session_key 模式下有效，指定创建时的会话类型
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionReq) Reset() {
	*x = GetSessionReq{}
	mi := &file_rpc_message_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionReq) ProtoMessage() {}

func (x *GetSessionReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_message_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionReq.ProtoReflect.Descriptor instead.
func (*GetSessionReq) Descriptor() ([]byte, []int) {
	return file_rpc_message_proto_rawDescGZIP(), []int{11}
}

func (x *GetSessionReq) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetSessionReq) GetSessionKey() string {
	if x != nil {
		return x.SessionKey
	}
	return ""
}

func (x *GetSessionReq) GetSessionType() int32 {
	if x != nil {
		return x.SessionType
	}
	return 0
}

type GetSessionResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionResp) Reset() {
	*x = GetSessionResp{}
	mi := &file_rpc_message_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionResp) ProtoMessage() {}

func (x *GetSessionResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_message_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionResp.ProtoReflect.Descriptor instead.
func (*GetSessionResp) Descriptor() ([]byte, []int) {
	return file_rpc_message_proto_rawDescGZIP(), []int{12}
}

func (x *GetSessionResp) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

var File_rpc_message_proto protoreflect.FileDescriptor

const file_rpc_message_proto_rawDesc = "" +
	"\n" +
	"\x11rpc/message.proto\x12\n" +
	"messagerpc\"\xb1\x02\n" +
	"\aMessage\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\tR\x05msgId\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12 \n" +
	"\ffrom_user_id\x18\x04 \x01(\x04R\n" +
	"fromUserId\x12\x19\n" +
	"\bmsg_type\x18\x05 \x01(\x05R\amsgType\x12\x10\n" +
	"\x03seq\x18\x06 \x01(\x04R\x03seq\x12\x18\n" +
	"\acontent\x18\a \x01(\tR\acontent\x12\x1b\n" +
	"\tmedia_url\x18\b \x01(\tR\bmediaUrl\x12\x14\n" +
	"\x05extra\x18\t \x01(\fR\x05extra\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\x05R\x06status\x12\x1f\n" +
	"\vcreate_time\x18\v \x01(\x03R\n" +
	"createTime\"\x9b\x02\n" +
	"\aSession\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\x05R\x04type\x12\x1f\n" +
	"\vsession_key\x18\x03 \x01(\tR\n" +
	"sessionKey\x12\x17\n" +
	"\amax_seq\x18\x04 \x01(\x04R\x06maxSeq\x12\x1d\n" +
	"\n" +
	"actual_seq\x18\x05 \x01(\x04R\tactualSeq\x12!\n" +
	"\flast_content\x18\x06 \x01(\tR\vlastContent\x12\x1f\n" +
	"\vlast_sender\x18\a \x01(\x04R\n" +
	"lastSender\x12\x1f\n" +
	"\vcreate_time\x18\b \x01(\x03R\n" +
	"createTime\x12\x1f\n" +
	"\vupdate_time\x18\t \x01(\x03R\n" +
	"updateTime\"\xe1\x01\n" +
	"\vUserSession\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x15\n" +
	"\x06is_top\x18\x03 \x01(\x05R\x05isTop\x12\x1d\n" +
	"\n" +
	"is_disturb\x18\x04 \x01(\x05R\tisDisturb\x12\"\n" +
	"\rlast_read_seq\x18\x05 \x01(\x04R\vlastReadSeq\x12\x1f\n" +
	"\vcreate_time\x18\x06 \x01(\x03R\n" +
	"createTime\x12\x1f\n" +
	"\vupdate_time\x18\a \x01(\x03R\n" +
	"updateTime\"z\n" +
	"\rGetHistoryReq\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tstart_seq\x18\x02 \x01(\x03R\bstartSeq\x12\x17\n" +
	"\aend_seq\x18\x03 \x01(\x03R\x06endSeq\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"A\n" +
	"\x0eGetHistoryResp\x12/\n" +
	"\bmessages\x18\x01 \x03(\v2\x13.messagerpc.MessageR\bmessages\"-\n" +
	"\x12GetUserSessionsReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"J\n" +
	"\x13GetUserSessionsResp\x123\n" +
	"\bsessions\x18\x01 \x03(\v2\x17.messagerpc.UserSessionR\bsessions\"\x80\x01\n" +
	"\x10UpdateSessionReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x15\n" +
	"\x06is_top\x18\x03 \x01(\x05R\x05isTop\x12\x1d\n" +
	"\n" +
	"is_disturb\x18\x04 \x01(\x05R\tisDisturb\"\x13\n" +
	"\x11UpdateSessionResp\"Q\n" +
	"\x18GetUserActiveSessionsReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"L\n" +
	"\x19GetUserActiveSessionsResp\x12/\n" +
	"\bsessions\x18\x01 \x03(\v2\x13.messagerpc.SessionR\bsessions\"r\n" +
	"\rGetSessionReq\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1f\n" +
	"\vsession_key\x18\x02 \x01(\tR\n" +
	"sessionKey\x12!\n" +
	"\fsession_type\x18\x03 \x01(\x05R\vsessionType\"?\n" +
	"\x0eGetSessionResp\x12-\n" +
	"\asession\x18\x01 \x01(\v2\x13.messagerpc.SessionR\asession2\x9e\x03\n" +
	"\n" +
	"MessageRpc\x12C\n" +
	"\n" +
	"GetHistory\x12\x19.messagerpc.GetHistoryReq\x1a\x1a.messagerpc.GetHistoryResp\x12L\n" +
	"\rUpdateSession\x12\x1c.messagerpc.UpdateSessionReq\x1a\x1d.messagerpc.UpdateSessionResp\x12R\n" +
	"\x0fGetUserSessions\x12\x1e.messagerpc.GetUserSessionsReq\x1a\x1f.messagerpc.GetUserSessionsResp\x12d\n" +
	"\x15GetUserActiveSessions\x12$.messagerpc.GetUserActiveSessionsReq\x1a%.messagerpc.GetUserActiveSessionsResp\x12C\n" +
	"\n" +
	"GetSession\x12\x19.messagerpc.GetSessionReq\x1a\x1a.messagerpc.GetSessionRespB\vZ\t./messageb\x06proto3"

var (
	file_rpc_message_proto_rawDescOnce sync.Once
	file_rpc_message_proto_rawDescData []byte
)

func file_rpc_message_proto_rawDescGZIP() []byte {
	file_rpc_message_proto_rawDescOnce.Do(func() {
		file_rpc_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_message_proto_rawDesc), len(file_rpc_message_proto_rawDesc)))
	})
	return file_rpc_message_proto_rawDescData
}

var file_rpc_message_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_rpc_message_proto_goTypes = []any{
	(*Message)(nil),                   // 0: messagerpc.Message
	(*Session)(nil),                   // 1: messagerpc.Session
	(*UserSession)(nil),               // 2: messagerpc.UserSession
	(*GetHistoryReq)(nil),             // 3: messagerpc.GetHistoryReq
	(*GetHistoryResp)(nil),            // 4: messagerpc.GetHistoryResp
	(*GetUserSessionsReq)(nil),        // 5: messagerpc.GetUserSessionsReq
	(*GetUserSessionsResp)(nil),       // 6: messagerpc.GetUserSessionsResp
	(*UpdateSessionReq)(nil),          // 7: messagerpc.UpdateSessionReq
	(*UpdateSessionResp)(nil),         // 8: messagerpc.UpdateSessionResp
	(*GetUserActiveSessionsReq)(nil),  // 9: messagerpc.GetUserActiveSessionsReq
	(*GetUserActiveSessionsResp)(nil), // 10: messagerpc.GetUserActiveSessionsResp
	(*GetSessionReq)(nil),             // 11: messagerpc.GetSessionReq
	(*GetSessionResp)(nil),            // 12: messagerpc.GetSessionResp
}
var file_rpc_message_proto_depIdxs = []int32{
	0,  // 0: messagerpc.GetHistoryResp.messages:type_name -> messagerpc.Message
	2,  // 1: messagerpc.GetUserSessionsResp.sessions:type_name -> messagerpc.UserSession
	1,  // 2: messagerpc.GetUserActiveSessionsResp.sessions:type_name -> messagerpc.Session
	1,  // 3: messagerpc.GetSessionResp.session:type_name -> messagerpc.Session
	3,  // 4: messagerpc.MessageRpc.GetHistory:input_type -> messagerpc.GetHistoryReq
	7,  // 5: messagerpc.MessageRpc.UpdateSession:input_type -> messagerpc.UpdateSessionReq
	5,  // 6: messagerpc.MessageRpc.GetUserSessions:input_type -> messagerpc.GetUserSessionsReq
	9,  // 7: messagerpc.MessageRpc.GetUserActiveSessions:input_type -> messagerpc.GetUserActiveSessionsReq
	11, // 8: messagerpc.MessageRpc.GetSession:input_type -> messagerpc.GetSessionReq
	4,  // 9: messagerpc.MessageRpc.GetHistory:output_type -> messagerpc.GetHistoryResp
	8,  // 10: messagerpc.MessageRpc.UpdateSession:output_type -> messagerpc.UpdateSessionResp
	6,  // 11: messagerpc.MessageRpc.GetUserSessions:output_type -> messagerpc.GetUserSessionsResp
	10, // 12: messagerpc.MessageRpc.GetUserActiveSessions:output_type -> messagerpc.GetUserActiveSessionsResp
	12, // 13: messagerpc.MessageRpc.GetSession:output_type -> messagerpc.GetSessionResp
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_rpc_message_proto_init() }
func file_rpc_message_proto_init() {
	if File_rpc_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_message_proto_rawDesc), len(file_rpc_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_message_proto_goTypes,
		DependencyIndexes: file_rpc_message_proto_depIdxs,
		MessageInfos:      file_rpc_message_proto_msgTypes,
	}.Build()
	File_rpc_message_proto = out.File
	file_rpc_message_proto_goTypes = nil
	file_rpc_message_proto_depIdxs = nil
}
