// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: rpc/message.proto

package message

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MessageRpc_GetHistory_FullMethodName           = "/message.MessageRpc/GetHistory"
	MessageRpc_GetConversationList_FullMethodName  = "/message.MessageRpc/GetConversationList"
	MessageRpc_ReadMessage_FullMethodName          = "/message.MessageRpc/ReadMessage"
	MessageRpc_UpdateConversation_FullMethodName   = "/message.MessageRpc/UpdateConversation"
	MessageRpc_GetUserConversations_FullMethodName = "/message.MessageRpc/GetUserConversations"
)

// MessageRpcClient is the client API for MessageRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MessageRpcClient interface {
	GetHistory(ctx context.Context, in *GetHistoryReq, opts ...grpc.CallOption) (*GetHistoryResp, error)
	GetConversationList(ctx context.Context, in *GetConversationListReq, opts ...grpc.CallOption) (*GetConversationListResp, error)
	ReadMessage(ctx context.Context, in *ReadMessageReq, opts ...grpc.CallOption) (*ReadMessageResp, error)
	UpdateConversation(ctx context.Context, in *UpdateConversationReq, opts ...grpc.CallOption) (*UpdateConversationResp, error)
	GetUserConversations(ctx context.Context, in *GetUserConversationsReq, opts ...grpc.CallOption) (*GetUserConversationsResp, error)
}

type messageRpcClient struct {
	cc grpc.ClientConnInterface
}

func NewMessageRpcClient(cc grpc.ClientConnInterface) MessageRpcClient {
	return &messageRpcClient{cc}
}

func (c *messageRpcClient) GetHistory(ctx context.Context, in *GetHistoryReq, opts ...grpc.CallOption) (*GetHistoryResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHistoryResp)
	err := c.cc.Invoke(ctx, MessageRpc_GetHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageRpcClient) GetConversationList(ctx context.Context, in *GetConversationListReq, opts ...grpc.CallOption) (*GetConversationListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConversationListResp)
	err := c.cc.Invoke(ctx, MessageRpc_GetConversationList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageRpcClient) ReadMessage(ctx context.Context, in *ReadMessageReq, opts ...grpc.CallOption) (*ReadMessageResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadMessageResp)
	err := c.cc.Invoke(ctx, MessageRpc_ReadMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageRpcClient) UpdateConversation(ctx context.Context, in *UpdateConversationReq, opts ...grpc.CallOption) (*UpdateConversationResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateConversationResp)
	err := c.cc.Invoke(ctx, MessageRpc_UpdateConversation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageRpcClient) GetUserConversations(ctx context.Context, in *GetUserConversationsReq, opts ...grpc.CallOption) (*GetUserConversationsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserConversationsResp)
	err := c.cc.Invoke(ctx, MessageRpc_GetUserConversations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessageRpcServer is the server API for MessageRpc service.
// All implementations must embed UnimplementedMessageRpcServer
// for forward compatibility.
type MessageRpcServer interface {
	GetHistory(context.Context, *GetHistoryReq) (*GetHistoryResp, error)
	GetConversationList(context.Context, *GetConversationListReq) (*GetConversationListResp, error)
	ReadMessage(context.Context, *ReadMessageReq) (*ReadMessageResp, error)
	UpdateConversation(context.Context, *UpdateConversationReq) (*UpdateConversationResp, error)
	GetUserConversations(context.Context, *GetUserConversationsReq) (*GetUserConversationsResp, error)
	mustEmbedUnimplementedMessageRpcServer()
}

// UnimplementedMessageRpcServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMessageRpcServer struct{}

func (UnimplementedMessageRpcServer) GetHistory(context.Context, *GetHistoryReq) (*GetHistoryResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHistory not implemented")
}
func (UnimplementedMessageRpcServer) GetConversationList(context.Context, *GetConversationListReq) (*GetConversationListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConversationList not implemented")
}
func (UnimplementedMessageRpcServer) ReadMessage(context.Context, *ReadMessageReq) (*ReadMessageResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadMessage not implemented")
}
func (UnimplementedMessageRpcServer) UpdateConversation(context.Context, *UpdateConversationReq) (*UpdateConversationResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateConversation not implemented")
}
func (UnimplementedMessageRpcServer) GetUserConversations(context.Context, *GetUserConversationsReq) (*GetUserConversationsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserConversations not implemented")
}
func (UnimplementedMessageRpcServer) mustEmbedUnimplementedMessageRpcServer() {}
func (UnimplementedMessageRpcServer) testEmbeddedByValue()                    {}

// UnsafeMessageRpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessageRpcServer will
// result in compilation errors.
type UnsafeMessageRpcServer interface {
	mustEmbedUnimplementedMessageRpcServer()
}

func RegisterMessageRpcServer(s grpc.ServiceRegistrar, srv MessageRpcServer) {
	// If the following call pancis, it indicates UnimplementedMessageRpcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MessageRpc_ServiceDesc, srv)
}

func _MessageRpc_GetHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHistoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageRpcServer).GetHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageRpc_GetHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageRpcServer).GetHistory(ctx, req.(*GetHistoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageRpc_GetConversationList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConversationListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageRpcServer).GetConversationList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageRpc_GetConversationList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageRpcServer).GetConversationList(ctx, req.(*GetConversationListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageRpc_ReadMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadMessageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageRpcServer).ReadMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageRpc_ReadMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageRpcServer).ReadMessage(ctx, req.(*ReadMessageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageRpc_UpdateConversation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateConversationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageRpcServer).UpdateConversation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageRpc_UpdateConversation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageRpcServer).UpdateConversation(ctx, req.(*UpdateConversationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageRpc_GetUserConversations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserConversationsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageRpcServer).GetUserConversations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageRpc_GetUserConversations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageRpcServer).GetUserConversations(ctx, req.(*GetUserConversationsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// MessageRpc_ServiceDesc is the grpc.ServiceDesc for MessageRpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MessageRpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "message.MessageRpc",
	HandlerType: (*MessageRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetHistory",
			Handler:    _MessageRpc_GetHistory_Handler,
		},
		{
			MethodName: "GetConversationList",
			Handler:    _MessageRpc_GetConversationList_Handler,
		},
		{
			MethodName: "ReadMessage",
			Handler:    _MessageRpc_ReadMessage_Handler,
		},
		{
			MethodName: "UpdateConversation",
			Handler:    _MessageRpc_UpdateConversation_Handler,
		},
		{
			MethodName: "GetUserConversations",
			Handler:    _MessageRpc_GetUserConversations_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc/message.proto",
}
