// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: rpc/message.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MsgId          string                 `protobuf:"bytes,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	FromUserId     uint64                 `protobuf:"varint,3,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	MsgType        int32                  `protobuf:"varint,4,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`
	Content        string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	MediaUrl       string                 `protobuf:"bytes,6,opt,name=media_url,json=mediaUrl,proto3" json:"media_url,omitempty"`
	Extra          string                 `protobuf:"bytes,7,opt,name=extra,proto3" json:"extra,omitempty"`
	Status         int32                  `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`
	CreateTime     int64                  `protobuf:"varint,9,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	Seq            uint64                 `protobuf:"varint,10,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_rpc_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_rpc_message_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *Message) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *Message) GetFromUserId() uint64 {
	if x != nil {
		return x.FromUserId
	}
	return 0
}

func (x *Message) GetMsgType() int32 {
	if x != nil {
		return x.MsgType
	}
	return 0
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetMediaUrl() string {
	if x != nil {
		return x.MediaUrl
	}
	return ""
}

func (x *Message) GetExtra() string {
	if x != nil {
		return x.Extra
	}
	return ""
}

func (x *Message) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Message) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *Message) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type Conversation struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Type           int32                  `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	LastMsgId      uint64                 `protobuf:"varint,3,opt,name=last_msg_id,json=lastMsgId,proto3" json:"last_msg_id,omitempty"`
	LastMsgTime    int64                  `protobuf:"varint,4,opt,name=last_msg_time,json=lastMsgTime,proto3" json:"last_msg_time,omitempty"`
	MaxSeq         uint64                 `protobuf:"varint,5,opt,name=max_seq,json=maxSeq,proto3" json:"max_seq,omitempty"`
	UnreadCount    int32                  `protobuf:"varint,6,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Conversation) Reset() {
	*x = Conversation{}
	mi := &file_rpc_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Conversation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Conversation) ProtoMessage() {}

func (x *Conversation) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Conversation.ProtoReflect.Descriptor instead.
func (*Conversation) Descriptor() ([]byte, []int) {
	return file_rpc_message_proto_rawDescGZIP(), []int{1}
}

func (x *Conversation) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *Conversation) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Conversation) GetLastMsgId() uint64 {
	if x != nil {
		return x.LastMsgId
	}
	return 0
}

func (x *Conversation) GetLastMsgTime() int64 {
	if x != nil {
		return x.LastMsgTime
	}
	return 0
}

func (x *Conversation) GetMaxSeq() uint64 {
	if x != nil {
		return x.MaxSeq
	}
	return 0
}

func (x *Conversation) GetUnreadCount() int32 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

type SendMessageReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MsgId          string                 `protobuf:"bytes,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	FromUserId     uint64                 `protobuf:"varint,3,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	MsgType        int32                  `protobuf:"varint,4,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`
	Content        string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	MediaUrl       string                 `protobuf:"bytes,6,opt,name=media_url,json=mediaUrl,proto3" json:"media_url,omitempty"`
	Extra          string                 `protobuf:"bytes,7,opt,name=extra,proto3" json:"extra,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendMessageReq) Reset() {
	*x = SendMessageReq{}
	mi := &file_rpc_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageReq) ProtoMessage() {}

func (x *SendMessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageReq.ProtoReflect.Descriptor instead.
func (*SendMessageReq) Descriptor() ([]byte, []int) {
	return file_rpc_message_proto_rawDescGZIP(), []int{2}
}

func (x *SendMessageReq) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *SendMessageReq) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *SendMessageReq) GetFromUserId() uint64 {
	if x != nil {
		return x.FromUserId
	}
	return 0
}

func (x *SendMessageReq) GetMsgType() int32 {
	if x != nil {
		return x.MsgType
	}
	return 0
}

func (x *SendMessageReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SendMessageReq) GetMediaUrl() string {
	if x != nil {
		return x.MediaUrl
	}
	return ""
}

func (x *SendMessageReq) GetExtra() string {
	if x != nil {
		return x.Extra
	}
	return ""
}

type SendMessageResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	CreateTime    int64                  `protobuf:"varint,2,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResp) Reset() {
	*x = SendMessageResp{}
	mi := &file_rpc_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResp) ProtoMessage() {}

func (x *SendMessageResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResp.ProtoReflect.Descriptor instead.
func (*SendMessageResp) Descriptor() ([]byte, []int) {
	return file_rpc_message_proto_rawDescGZIP(), []int{3}
}

func (x *SendMessageResp) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *SendMessageResp) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

type GetHistoryReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	CursorSeq      uint64                 `protobuf:"varint,2,opt,name=cursor_seq,json=cursorSeq,proto3" json:"cursor_seq,omitempty"` // 上一次拉取的seq，首次传0(最新)
	Limit          int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Forward        bool                   `protobuf:"varint,4,opt,name=forward,proto3" json:"forward,omitempty"` // true: 向旧消息拉取(History), false: 向新消息拉取(Sync)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetHistoryReq) Reset() {
	*x = GetHistoryReq{}
	mi := &file_rpc_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryReq) ProtoMessage() {}

func (x *GetHistoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryReq.ProtoReflect.Descriptor instead.
func (*GetHistoryReq) Descriptor() ([]byte, []int) {
	return file_rpc_message_proto_rawDescGZIP(), []int{4}
}

func (x *GetHistoryReq) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *GetHistoryReq) GetCursorSeq() uint64 {
	if x != nil {
		return x.CursorSeq
	}
	return 0
}

func (x *GetHistoryReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetHistoryReq) GetForward() bool {
	if x != nil {
		return x.Forward
	}
	return false
}

type GetHistoryResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryResp) Reset() {
	*x = GetHistoryResp{}
	mi := &file_rpc_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryResp) ProtoMessage() {}

func (x *GetHistoryResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryResp.ProtoReflect.Descriptor instead.
func (*GetHistoryResp) Descriptor() ([]byte, []int) {
	return file_rpc_message_proto_rawDescGZIP(), []int{5}
}

func (x *GetHistoryResp) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

type GetConversationListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConversationListReq) Reset() {
	*x = GetConversationListReq{}
	mi := &file_rpc_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConversationListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConversationListReq) ProtoMessage() {}

func (x *GetConversationListReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConversationListReq.ProtoReflect.Descriptor instead.
func (*GetConversationListReq) Descriptor() ([]byte, []int) {
	return file_rpc_message_proto_rawDescGZIP(), []int{6}
}

func (x *GetConversationListReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetConversationListReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetConversationListReq) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetConversationListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conversations []*Conversation        `protobuf:"bytes,1,rep,name=conversations,proto3" json:"conversations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConversationListResp) Reset() {
	*x = GetConversationListResp{}
	mi := &file_rpc_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConversationListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConversationListResp) ProtoMessage() {}

func (x *GetConversationListResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConversationListResp.ProtoReflect.Descriptor instead.
func (*GetConversationListResp) Descriptor() ([]byte, []int) {
	return file_rpc_message_proto_rawDescGZIP(), []int{7}
}

func (x *GetConversationListResp) GetConversations() []*Conversation {
	if x != nil {
		return x.Conversations
	}
	return nil
}

type ReadMessageReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Seq            uint64                 `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"` // 读到的seq
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReadMessageReq) Reset() {
	*x = ReadMessageReq{}
	mi := &file_rpc_message_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadMessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadMessageReq) ProtoMessage() {}

func (x *ReadMessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_message_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadMessageReq.ProtoReflect.Descriptor instead.
func (*ReadMessageReq) Descriptor() ([]byte, []int) {
	return file_rpc_message_proto_rawDescGZIP(), []int{8}
}

func (x *ReadMessageReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ReadMessageReq) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ReadMessageReq) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type ReadMessageResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadMessageResp) Reset() {
	*x = ReadMessageResp{}
	mi := &file_rpc_message_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadMessageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadMessageResp) ProtoMessage() {}

func (x *ReadMessageResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_message_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadMessageResp.ProtoReflect.Descriptor instead.
func (*ReadMessageResp) Descriptor() ([]byte, []int) {
	return file_rpc_message_proto_rawDescGZIP(), []int{9}
}

type UpdateConversationReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	IsTop          int32                  `protobuf:"varint,3,opt,name=is_top,json=isTop,proto3" json:"is_top,omitempty"`             // 0:不变更 1:置顶 2:取消置顶
	IsDisturb      int32                  `protobuf:"varint,4,opt,name=is_disturb,json=isDisturb,proto3" json:"is_disturb,omitempty"` // 0:不变更 1:免打扰 2:取消免打扰
	IsMute         int32                  `protobuf:"varint,5,opt,name=is_mute,json=isMute,proto3" json:"is_mute,omitempty"`          // 0:不变更 1:静音 2:取消静音
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateConversationReq) Reset() {
	*x = UpdateConversationReq{}
	mi := &file_rpc_message_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConversationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConversationReq) ProtoMessage() {}

func (x *UpdateConversationReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_message_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConversationReq.ProtoReflect.Descriptor instead.
func (*UpdateConversationReq) Descriptor() ([]byte, []int) {
	return file_rpc_message_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateConversationReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateConversationReq) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *UpdateConversationReq) GetIsTop() int32 {
	if x != nil {
		return x.IsTop
	}
	return 0
}

func (x *UpdateConversationReq) GetIsDisturb() int32 {
	if x != nil {
		return x.IsDisturb
	}
	return 0
}

func (x *UpdateConversationReq) GetIsMute() int32 {
	if x != nil {
		return x.IsMute
	}
	return 0
}

type UpdateConversationResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConversationResp) Reset() {
	*x = UpdateConversationResp{}
	mi := &file_rpc_message_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConversationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConversationResp) ProtoMessage() {}

func (x *UpdateConversationResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_message_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConversationResp.ProtoReflect.Descriptor instead.
func (*UpdateConversationResp) Descriptor() ([]byte, []int) {
	return file_rpc_message_proto_rawDescGZIP(), []int{11}
}

var File_rpc_message_proto protoreflect.FileDescriptor

const file_rpc_message_proto_rawDesc = "" +
	"\n" +
	"\x11rpc/message.proto\x12\amessage\"\x9e\x02\n" +
	"\aMessage\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\tR\x05msgId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12 \n" +
	"\ffrom_user_id\x18\x03 \x01(\x04R\n" +
	"fromUserId\x12\x19\n" +
	"\bmsg_type\x18\x04 \x01(\x05R\amsgType\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x1b\n" +
	"\tmedia_url\x18\x06 \x01(\tR\bmediaUrl\x12\x14\n" +
	"\x05extra\x18\a \x01(\tR\x05extra\x12\x16\n" +
	"\x06status\x18\b \x01(\x05R\x06status\x12\x1f\n" +
	"\vcreate_time\x18\t \x01(\x03R\n" +
	"createTime\x12\x10\n" +
	"\x03seq\x18\n" +
	" \x01(\x04R\x03seq\"\xcb\x01\n" +
	"\fConversation\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\x05R\x04type\x12\x1e\n" +
	"\vlast_msg_id\x18\x03 \x01(\x04R\tlastMsgId\x12\"\n" +
	"\rlast_msg_time\x18\x04 \x01(\x03R\vlastMsgTime\x12\x17\n" +
	"\amax_seq\x18\x05 \x01(\x04R\x06maxSeq\x12!\n" +
	"\funread_count\x18\x06 \x01(\x05R\vunreadCount\"\xda\x01\n" +
	"\x0eSendMessageReq\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\tR\x05msgId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12 \n" +
	"\ffrom_user_id\x18\x03 \x01(\x04R\n" +
	"fromUserId\x12\x19\n" +
	"\bmsg_type\x18\x04 \x01(\x05R\amsgType\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x1b\n" +
	"\tmedia_url\x18\x06 \x01(\tR\bmediaUrl\x12\x14\n" +
	"\x05extra\x18\a \x01(\tR\x05extra\"D\n" +
	"\x0fSendMessageResp\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12\x1f\n" +
	"\vcreate_time\x18\x02 \x01(\x03R\n" +
	"createTime\"\x87\x01\n" +
	"\rGetHistoryReq\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x1d\n" +
	"\n" +
	"cursor_seq\x18\x02 \x01(\x04R\tcursorSeq\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x18\n" +
	"\aforward\x18\x04 \x01(\bR\aforward\">\n" +
	"\x0eGetHistoryResp\x12,\n" +
	"\bmessages\x18\x01 \x03(\v2\x10.message.MessageR\bmessages\"_\n" +
	"\x16GetConversationListReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"V\n" +
	"\x17GetConversationListResp\x12;\n" +
	"\rconversations\x18\x01 \x03(\v2\x15.message.ConversationR\rconversations\"d\n" +
	"\x0eReadMessageReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x04R\x03seq\"\x11\n" +
	"\x0fReadMessageResp\"\xa8\x01\n" +
	"\x15UpdateConversationReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12\x15\n" +
	"\x06is_top\x18\x03 \x01(\x05R\x05isTop\x12\x1d\n" +
	"\n" +
	"is_disturb\x18\x04 \x01(\x05R\tisDisturb\x12\x17\n" +
	"\ais_mute\x18\x05 \x01(\x05R\x06isMute\"\x18\n" +
	"\x16UpdateConversationResp2\x80\x03\n" +
	"\n" +
	"MessageRpc\x12@\n" +
	"\vSendMessage\x12\x17.message.SendMessageReq\x1a\x18.message.SendMessageResp\x12=\n" +
	"\n" +
	"GetHistory\x12\x16.message.GetHistoryReq\x1a\x17.message.GetHistoryResp\x12X\n" +
	"\x13GetConversationList\x12\x1f.message.GetConversationListReq\x1a .message.GetConversationListResp\x12@\n" +
	"\vReadMessage\x12\x17.message.ReadMessageReq\x1a\x18.message.ReadMessageResp\x12U\n" +
	"\x12UpdateConversation\x12\x1e.message.UpdateConversationReq\x1a\x1f.message.UpdateConversationRespB\vZ\t./messageb\x06proto3"

var (
	file_rpc_message_proto_rawDescOnce sync.Once
	file_rpc_message_proto_rawDescData []byte
)

func file_rpc_message_proto_rawDescGZIP() []byte {
	file_rpc_message_proto_rawDescOnce.Do(func() {
		file_rpc_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_message_proto_rawDesc), len(file_rpc_message_proto_rawDesc)))
	})
	return file_rpc_message_proto_rawDescData
}

var file_rpc_message_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_rpc_message_proto_goTypes = []any{
	(*Message)(nil),                 // 0: message.Message
	(*Conversation)(nil),            // 1: message.Conversation
	(*SendMessageReq)(nil),          // 2: message.SendMessageReq
	(*SendMessageResp)(nil),         // 3: message.SendMessageResp
	(*GetHistoryReq)(nil),           // 4: message.GetHistoryReq
	(*GetHistoryResp)(nil),          // 5: message.GetHistoryResp
	(*GetConversationListReq)(nil),  // 6: message.GetConversationListReq
	(*GetConversationListResp)(nil), // 7: message.GetConversationListResp
	(*ReadMessageReq)(nil),          // 8: message.ReadMessageReq
	(*ReadMessageResp)(nil),         // 9: message.ReadMessageResp
	(*UpdateConversationReq)(nil),   // 10: message.UpdateConversationReq
	(*UpdateConversationResp)(nil),  // 11: message.UpdateConversationResp
}
var file_rpc_message_proto_depIdxs = []int32{
	0,  // 0: message.GetHistoryResp.messages:type_name -> message.Message
	1,  // 1: message.GetConversationListResp.conversations:type_name -> message.Conversation
	2,  // 2: message.MessageRpc.SendMessage:input_type -> message.SendMessageReq
	4,  // 3: message.MessageRpc.GetHistory:input_type -> message.GetHistoryReq
	6,  // 4: message.MessageRpc.GetConversationList:input_type -> message.GetConversationListReq
	8,  // 5: message.MessageRpc.ReadMessage:input_type -> message.ReadMessageReq
	10, // 6: message.MessageRpc.UpdateConversation:input_type -> message.UpdateConversationReq
	3,  // 7: message.MessageRpc.SendMessage:output_type -> message.SendMessageResp
	5,  // 8: message.MessageRpc.GetHistory:output_type -> message.GetHistoryResp
	7,  // 9: message.MessageRpc.GetConversationList:output_type -> message.GetConversationListResp
	9,  // 10: message.MessageRpc.ReadMessage:output_type -> message.ReadMessageResp
	11, // 11: message.MessageRpc.UpdateConversation:output_type -> message.UpdateConversationResp
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_rpc_message_proto_init() }
func file_rpc_message_proto_init() {
	if File_rpc_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_message_proto_rawDesc), len(file_rpc_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_message_proto_goTypes,
		DependencyIndexes: file_rpc_message_proto_depIdxs,
		MessageInfos:      file_rpc_message_proto_msgTypes,
	}.Build()
	File_rpc_message_proto = out.File
	file_rpc_message_proto_goTypes = nil
	file_rpc_message_proto_depIdxs = nil
}
