// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: auth.proto

package server

import (
	"context"

	"IM2/internal/apps/Auth/rpc/auth"
	authrpclogic "IM2/internal/apps/Auth/rpc/internal/logic/authrpc"
	"IM2/internal/apps/Auth/rpc/svc"
)

type AuthRpcServer struct {
	svcCtx *svc.ServiceContext
	auth.UnimplementedAuthRpcServer
}

func NewAuthRpcServer(svcCtx *svc.ServiceContext) *AuthRpcServer {
	return &AuthRpcServer{
		svcCtx: svcCtx,
	}
}

func (s *AuthRpcServer) Login(ctx context.Context, in *auth.LoginRequest) (*auth.LoginReply, error) {
	l := authrpclogic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *AuthRpcServer) Logout(ctx context.Context, in *auth.LogoutRequest) (*auth.LogoutReply, error) {
	l := authrpclogic.NewLogoutLogic(ctx, s.svcCtx)
	return l.Logout(in)
}

func (s *AuthRpcServer) Register(ctx context.Context, in *auth.RegisterReq) (*auth.RegisterResp, error) {
	l := authrpclogic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *AuthRpcServer) GetAuthCode(ctx context.Context, in *auth.GetAuthCodeReq) (*auth.GetAuthCodeResp, error) {
	l := authrpclogic.NewGetAuthCodeLogic(ctx, s.svcCtx)
	return l.GetAuthCode(in)
}

func (s *AuthRpcServer) Refresh(ctx context.Context, in *auth.RefreshReq) (*auth.RefreshResp, error) {
	l := authrpclogic.NewRefreshLogic(ctx, s.svcCtx)
	return l.Refresh(in)
}
