// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package handler

import (
	"net/http"

	callback "IM2/internal/apps/File/api/handler/callback"
	fileupload "IM2/internal/apps/File/api/handler/fileupload"
	"IM2/internal/apps/File/api/svc"

	"IM2/middleware"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 上传回调
				Method:  http.MethodPost,
				Path:    "/uploadCallback",
				Handler: callback.UploadCallbackHandler(serverCtx),
			},
		},
		rest.WithPrefix("/fileupload"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{middleware.WithRedisJwtAuth(serverCtx.TokenManager)},
			[]rest.Route{
				{
					// 获取签名
					Method:  http.MethodGet,
					Path:    "/getPostSignature",
					Handler: fileupload.GetPostSignatureHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/fileupload"),
	)
}
