// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: file_api.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileType int32

const (
	FileType_FileTypeAvatar    FileType = 0
	FileType_FileTypeChatImage FileType = 1
	FileType_FileTypeChatFile  FileType = 2
)

// Enum value maps for FileType.
var (
	FileType_name = map[int32]string{
		0: "FileTypeAvatar",
		1: "FileTypeChatImage",
		2: "FileTypeChatFile",
	}
	FileType_value = map[string]int32{
		"FileTypeAvatar":    0,
		"FileTypeChatImage": 1,
		"FileTypeChatFile":  2,
	}
)

func (x FileType) Enum() *FileType {
	p := new(FileType)
	*p = x
	return p
}

func (x FileType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileType) Descriptor() protoreflect.EnumDescriptor {
	return file_file_api_proto_enumTypes[0].Descriptor()
}

func (FileType) Type() protoreflect.EnumType {
	return &file_file_api_proto_enumTypes[0]
}

func (x FileType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileType.Descriptor instead.
func (FileType) EnumDescriptor() ([]byte, []int) {
	return file_file_api_proto_rawDescGZIP(), []int{0}
}

type PolicyToken struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: json:"policy"
	Policy string `protobuf:"bytes,1,opt,name=policy,proto3" json:"policy"`
	// @gotags: json:"security_token"
	SecurityToken string `protobuf:"bytes,2,opt,name=security_token,json=securityToken,proto3" json:"security_token"`
	// @gotags: json:"x_oss_signature_version"
	XOssSignatureVersion string `protobuf:"bytes,3,opt,name=x_oss_signature_version,json=xOssSignatureVersion,proto3" json:"x_oss_signature_version"`
	// @gotags: json:"x_oss_credential"
	XOssCredential string `protobuf:"bytes,4,opt,name=x_oss_credential,json=xOssCredential,proto3" json:"x_oss_credential"`
	// @gotags: json:"x_oss_date"
	XOssDate string `protobuf:"bytes,5,opt,name=x_oss_date,json=xOssDate,proto3" json:"x_oss_date"`
	// @gotags: json:"signature"
	Signature string `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature"`
	// @gotags: json:"host"
	Host string `protobuf:"bytes,7,opt,name=host,proto3" json:"host"`
	// @gotags: json:"dir"
	Dir string `protobuf:"bytes,8,opt,name=dir,proto3" json:"dir"`
	// @gotags: json:"callback"
	Callback      string `protobuf:"bytes,9,opt,name=callback,proto3" json:"callback"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyToken) Reset() {
	*x = PolicyToken{}
	mi := &file_file_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyToken) ProtoMessage() {}

func (x *PolicyToken) ProtoReflect() protoreflect.Message {
	mi := &file_file_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyToken.ProtoReflect.Descriptor instead.
func (*PolicyToken) Descriptor() ([]byte, []int) {
	return file_file_api_proto_rawDescGZIP(), []int{0}
}

func (x *PolicyToken) GetPolicy() string {
	if x != nil {
		return x.Policy
	}
	return ""
}

func (x *PolicyToken) GetSecurityToken() string {
	if x != nil {
		return x.SecurityToken
	}
	return ""
}

func (x *PolicyToken) GetXOssSignatureVersion() string {
	if x != nil {
		return x.XOssSignatureVersion
	}
	return ""
}

func (x *PolicyToken) GetXOssCredential() string {
	if x != nil {
		return x.XOssCredential
	}
	return ""
}

func (x *PolicyToken) GetXOssDate() string {
	if x != nil {
		return x.XOssDate
	}
	return ""
}

func (x *PolicyToken) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *PolicyToken) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *PolicyToken) GetDir() string {
	if x != nil {
		return x.Dir
	}
	return ""
}

func (x *PolicyToken) GetCallback() string {
	if x != nil {
		return x.Callback
	}
	return ""
}

type CallbackParam struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: json:"callbackUrl"
	CallbackUrl string `protobuf:"bytes,1,opt,name=callbackUrl,proto3" json:"callbackUrl"`
	// @gotags: json:"callbackBody"
	CallbackBody string `protobuf:"bytes,2,opt,name=callbackBody,proto3" json:"callbackBody"`
	// @gotags: json:"callbackBodyType"
	CallbackBodyType string `protobuf:"bytes,3,opt,name=callbackBodyType,proto3" json:"callbackBodyType"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CallbackParam) Reset() {
	*x = CallbackParam{}
	mi := &file_file_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallbackParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallbackParam) ProtoMessage() {}

func (x *CallbackParam) ProtoReflect() protoreflect.Message {
	mi := &file_file_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallbackParam.ProtoReflect.Descriptor instead.
func (*CallbackParam) Descriptor() ([]byte, []int) {
	return file_file_api_proto_rawDescGZIP(), []int{1}
}

func (x *CallbackParam) GetCallbackUrl() string {
	if x != nil {
		return x.CallbackUrl
	}
	return ""
}

func (x *CallbackParam) GetCallbackBody() string {
	if x != nil {
		return x.CallbackBody
	}
	return ""
}

func (x *CallbackParam) GetCallbackBodyType() string {
	if x != nil {
		return x.CallbackBodyType
	}
	return ""
}

type CallbackData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: form:"id,optional" json:"id,optional"
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,optional" form:"id,optional"`
	// @gotags: form:"file_type,optional" json:"file_type,optional"
	FileType int32 `protobuf:"varint,2,opt,name=file_type,json=fileType,proto3" json:"file_type,optional" form:"file_type,optional"`
	// @gotags: form:"width,optional" json:"width,optional"
	Width int32 `protobuf:"varint,3,opt,name=width,proto3" json:"width,optional" form:"width,optional"`
	// @gotags: form:"height,optional" json:"height,optional"
	Height int32 `protobuf:"varint,4,opt,name=height,proto3" json:"height,optional" form:"height,optional"`
	// @gotags: form:"size,optional" json:"size,optional"
	Size uint64 `protobuf:"varint,5,opt,name=size,proto3" json:"size,optional" form:"size,optional"`
	// @gotags: form:"file_name,optional" json:"file_name,optional"
	FileName string `protobuf:"bytes,6,opt,name=file_name,json=fileName,proto3" json:"file_name,optional" form:"file_name,optional"`
	// @gotags: form:"mime_type,optional" json:"mime_type,optional"
	MimeType      string `protobuf:"bytes,7,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,optional" form:"mime_type,optional"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallbackData) Reset() {
	*x = CallbackData{}
	mi := &file_file_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallbackData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallbackData) ProtoMessage() {}

func (x *CallbackData) ProtoReflect() protoreflect.Message {
	mi := &file_file_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallbackData.ProtoReflect.Descriptor instead.
func (*CallbackData) Descriptor() ([]byte, []int) {
	return file_file_api_proto_rawDescGZIP(), []int{2}
}

func (x *CallbackData) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CallbackData) GetFileType() int32 {
	if x != nil {
		return x.FileType
	}
	return 0
}

func (x *CallbackData) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *CallbackData) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *CallbackData) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *CallbackData) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *CallbackData) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

type GetPostSignatureReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: form:"file_type,optional" json:"file_type,optional"
	FileType      int32 `protobuf:"varint,1,opt,name=file_type,json=fileType,proto3" json:"file_type,optional" form:"file_type,optional"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostSignatureReq) Reset() {
	*x = GetPostSignatureReq{}
	mi := &file_file_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostSignatureReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostSignatureReq) ProtoMessage() {}

func (x *GetPostSignatureReq) ProtoReflect() protoreflect.Message {
	mi := &file_file_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostSignatureReq.ProtoReflect.Descriptor instead.
func (*GetPostSignatureReq) Descriptor() ([]byte, []int) {
	return file_file_api_proto_rawDescGZIP(), []int{3}
}

func (x *GetPostSignatureReq) GetFileType() int32 {
	if x != nil {
		return x.FileType
	}
	return 0
}

var File_file_api_proto protoreflect.FileDescriptor

const file_file_api_proto_rawDesc = "" +
	"\n" +
	"\x0efile_api.proto\x12\x05types\"\xab\x02\n" +
	"\vPolicyToken\x12\x16\n" +
	"\x06policy\x18\x01 \x01(\tR\x06policy\x12%\n" +
	"\x0esecurity_token\x18\x02 \x01(\tR\rsecurityToken\x125\n" +
	"\x17x_oss_signature_version\x18\x03 \x01(\tR\x14xOssSignatureVersion\x12(\n" +
	"\x10x_oss_credential\x18\x04 \x01(\tR\x0exOssCredential\x12\x1c\n" +
	"\n" +
	"x_oss_date\x18\x05 \x01(\tR\bxOssDate\x12\x1c\n" +
	"\tsignature\x18\x06 \x01(\tR\tsignature\x12\x12\n" +
	"\x04host\x18\a \x01(\tR\x04host\x12\x10\n" +
	"\x03dir\x18\b \x01(\tR\x03dir\x12\x1a\n" +
	"\bcallback\x18\t \x01(\tR\bcallback\"\x81\x01\n" +
	"\rCallbackParam\x12 \n" +
	"\vcallbackUrl\x18\x01 \x01(\tR\vcallbackUrl\x12\"\n" +
	"\fcallbackBody\x18\x02 \x01(\tR\fcallbackBody\x12*\n" +
	"\x10callbackBodyType\x18\x03 \x01(\tR\x10callbackBodyType\"\xb7\x01\n" +
	"\fCallbackData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1b\n" +
	"\tfile_type\x18\x02 \x01(\x05R\bfileType\x12\x14\n" +
	"\x05width\x18\x03 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\x05R\x06height\x12\x12\n" +
	"\x04size\x18\x05 \x01(\x04R\x04size\x12\x1b\n" +
	"\tfile_name\x18\x06 \x01(\tR\bfileName\x12\x1b\n" +
	"\tmime_type\x18\a \x01(\tR\bmimeType\"2\n" +
	"\x13GetPostSignatureReq\x12\x1b\n" +
	"\tfile_type\x18\x01 \x01(\x05R\bfileType*K\n" +
	"\bFileType\x12\x12\n" +
	"\x0eFileTypeAvatar\x10\x00\x12\x15\n" +
	"\x11FileTypeChatImage\x10\x01\x12\x14\n" +
	"\x10FileTypeChatFile\x10\x02B\n" +
	"Z\b./;typesb\x06proto3"

var (
	file_file_api_proto_rawDescOnce sync.Once
	file_file_api_proto_rawDescData []byte
)

func file_file_api_proto_rawDescGZIP() []byte {
	file_file_api_proto_rawDescOnce.Do(func() {
		file_file_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_file_api_proto_rawDesc), len(file_file_api_proto_rawDesc)))
	})
	return file_file_api_proto_rawDescData
}

var file_file_api_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_file_api_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_file_api_proto_goTypes = []any{
	(FileType)(0),               // 0: types.FileType
	(*PolicyToken)(nil),         // 1: types.PolicyToken
	(*CallbackParam)(nil),       // 2: types.CallbackParam
	(*CallbackData)(nil),        // 3: types.CallbackData
	(*GetPostSignatureReq)(nil), // 4: types.GetPostSignatureReq
}
var file_file_api_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_file_api_proto_init() }
func file_file_api_proto_init() {
	if File_file_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_file_api_proto_rawDesc), len(file_file_api_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_file_api_proto_goTypes,
		DependencyIndexes: file_file_api_proto_depIdxs,
		EnumInfos:         file_file_api_proto_enumTypes,
		MessageInfos:      file_file_api_proto_msgTypes,
	}.Build()
	File_file_api_proto = out.File
	file_file_api_proto_goTypes = nil
	file_file_api_proto_depIdxs = nil
}
