// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type GetAuthCodeReq struct {
	Phone string `json:"phone"`
}

type GetAuthCodeResp struct {
}

type LoginReq struct {
	Account  uint64 `json:"account"`
	Password string `json:"password"`
	DeviceId string `json:"device_id"`
	Platform string `json:"platform"`
}

type LoginResp struct {
	Token        string `json:"token"`
	RefreshToken string `json:"refresh_token"`
}

type LogoutReq struct {
	RemoveRT bool `json:"remove_rt"`
}

type RefreshReq struct {
	DeviceId     string `json:"device_id"`
	Platform     string `json:"platform"`
	RefreshToken string `json:"refresh_token,omitempty"`
}

type RefreshResp struct {
	Token        string `json:"token"`
	RefreshToken string `json:"refresh_token"`
}

type RegisterReq struct {
	Name     string `json:"name"`
	Password string `json:"password"`
	Phone    string `json:"phone"`
	AuthCode string `json:"auth_code"`
}

type RegisterResp struct {
	Id uint64 `json:"id"`
}
