// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: message.proto

package server

import (
	"context"

	"IM2/internal/apps/Message/rpc/internal/logic/messagerpc"
	"IM2/internal/apps/Message/rpc/svc"
	"IM2/internal/apps/Message/rpc/message"
)

type MessageRpcServer struct {
	svcCtx *svc.ServiceContext
	message.UnimplementedMessageRpcServer
}

func NewMessageRpcServer(svcCtx *svc.ServiceContext) *MessageRpcServer {
	return &MessageRpcServer{
		svcCtx: svcCtx,
	}
}

func (s *MessageRpcServer) GetHistory(ctx context.Context, in *message.GetHistoryReq) (*message.GetHistoryResp, error) {
	l := messagerpclogic.NewGetHistoryLogic(ctx, s.svcCtx)
	return l.GetHistory(in)
}

func (s *MessageRpcServer) UpdateSession(ctx context.Context, in *message.UpdateSessionReq) (*message.UpdateSessionResp, error) {
	l := messagerpclogic.NewUpdateSessionLogic(ctx, s.svcCtx)
	return l.UpdateSession(in)
}

func (s *MessageRpcServer) GetUserSessions(ctx context.Context, in *message.GetUserSessionsReq) (*message.GetUserSessionsResp, error) {
	l := messagerpclogic.NewGetUserSessionsLogic(ctx, s.svcCtx)
	return l.GetUserSessions(in)
}

func (s *MessageRpcServer) GetUserActiveSessions(ctx context.Context, in *message.GetUserActiveSessionsReq) (*message.GetUserActiveSessionsResp, error) {
	l := messagerpclogic.NewGetUserActiveSessionsLogic(ctx, s.svcCtx)
	return l.GetUserActiveSessions(in)
}

func (s *MessageRpcServer) MarkSessionRead(ctx context.Context, in *message.MarkSessionReadReq) (*message.MarkSessionReadResp, error) {
	l := messagerpclogic.NewMarkSessionReadLogic(ctx, s.svcCtx)
	return l.MarkSessionRead(in)
}

func (s *MessageRpcServer) RecallMessage(ctx context.Context, in *message.RecallMessageReq) (*message.RecallMessageResp, error) {
	l := messagerpclogic.NewRecallMessageLogic(ctx, s.svcCtx)
	return l.RecallMessage(in)
}

// 内部会话管理接口
func (s *MessageRpcServer) GetSession(ctx context.Context, in *message.GetSessionReq) (*message.GetSessionResp, error) {
	l := messagerpclogic.NewGetSessionLogic(ctx, s.svcCtx)
	return l.GetSession(in)
}
