// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: rpc/idgen.proto

package idgen

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// IDType ID类型枚举
type IDType int32

const (
	IDType_ID_TYPE_UNSPECIFIED IDType = 0 // 未指定
	IDType_ID_TYPE_USER        IDType = 1 // 用户ID
	IDType_ID_TYPE_GROUP       IDType = 2 // 群组ID
	IDType_ID_TYPE_MESSAGE     IDType = 3 // 消息ID
)

// Enum value maps for IDType.
var (
	IDType_name = map[int32]string{
		0: "ID_TYPE_UNSPECIFIED",
		1: "ID_TYPE_USER",
		2: "ID_TYPE_GROUP",
		3: "ID_TYPE_MESSAGE",
	}
	IDType_value = map[string]int32{
		"ID_TYPE_UNSPECIFIED": 0,
		"ID_TYPE_USER":        1,
		"ID_TYPE_GROUP":       2,
		"ID_TYPE_MESSAGE":     3,
	}
)

func (x IDType) Enum() *IDType {
	p := new(IDType)
	*p = x
	return p
}

func (x IDType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IDType) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_idgen_proto_enumTypes[0].Descriptor()
}

func (IDType) Type() protoreflect.EnumType {
	return &file_rpc_idgen_proto_enumTypes[0]
}

func (x IDType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IDType.Descriptor instead.
func (IDType) EnumDescriptor() ([]byte, []int) {
	return file_rpc_idgen_proto_rawDescGZIP(), []int{0}
}

// GetIdReq 获取ID请求
type GetIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdType        IDType                 `protobuf:"varint,1,opt,name=idType,proto3,enum=idgen.IDType" json:"idType,omitempty"` // ID类型
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`                     // 需要获取的ID数量，默认为1
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIdReq) Reset() {
	*x = GetIdReq{}
	mi := &file_rpc_idgen_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIdReq) ProtoMessage() {}

func (x *GetIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_idgen_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIdReq.ProtoReflect.Descriptor instead.
func (*GetIdReq) Descriptor() ([]byte, []int) {
	return file_rpc_idgen_proto_rawDescGZIP(), []int{0}
}

func (x *GetIdReq) GetIdType() IDType {
	if x != nil {
		return x.IdType
	}
	return IDType_ID_TYPE_UNSPECIFIED
}

func (x *GetIdReq) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// GetIdResp 获取ID响应
type GetIdResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int64                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"` // 返回的ID列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIdResp) Reset() {
	*x = GetIdResp{}
	mi := &file_rpc_idgen_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIdResp) ProtoMessage() {}

func (x *GetIdResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_idgen_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIdResp.ProtoReflect.Descriptor instead.
func (*GetIdResp) Descriptor() ([]byte, []int) {
	return file_rpc_idgen_proto_rawDescGZIP(), []int{1}
}

func (x *GetIdResp) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

var File_rpc_idgen_proto protoreflect.FileDescriptor

const file_rpc_idgen_proto_rawDesc = "" +
	"\n" +
	"\x0frpc/idgen.proto\x12\x05idgen\"G\n" +
	"\bGetIdReq\x12%\n" +
	"\x06idType\x18\x01 \x01(\x0e2\r.idgen.IDTypeR\x06idType\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"\x1d\n" +
	"\tGetIdResp\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x03R\x03ids*[\n" +
	"\x06IDType\x12\x17\n" +
	"\x13ID_TYPE_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fID_TYPE_USER\x10\x01\x12\x11\n" +
	"\rID_TYPE_GROUP\x10\x02\x12\x13\n" +
	"\x0fID_TYPE_MESSAGE\x10\x0323\n" +
	"\x05Idgen\x12*\n" +
	"\x05GetId\x12\x0f.idgen.GetIdReq\x1a\x10.idgen.GetIdRespB\tZ\a./idgenb\x06proto3"

var (
	file_rpc_idgen_proto_rawDescOnce sync.Once
	file_rpc_idgen_proto_rawDescData []byte
)

func file_rpc_idgen_proto_rawDescGZIP() []byte {
	file_rpc_idgen_proto_rawDescOnce.Do(func() {
		file_rpc_idgen_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_idgen_proto_rawDesc), len(file_rpc_idgen_proto_rawDesc)))
	})
	return file_rpc_idgen_proto_rawDescData
}

var file_rpc_idgen_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_rpc_idgen_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_idgen_proto_goTypes = []any{
	(IDType)(0),       // 0: idgen.IDType
	(*GetIdReq)(nil),  // 1: idgen.GetIdReq
	(*GetIdResp)(nil), // 2: idgen.GetIdResp
}
var file_rpc_idgen_proto_depIdxs = []int32{
	0, // 0: idgen.GetIdReq.idType:type_name -> idgen.IDType
	1, // 1: idgen.Idgen.GetId:input_type -> idgen.GetIdReq
	2, // 2: idgen.Idgen.GetId:output_type -> idgen.GetIdResp
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_idgen_proto_init() }
func file_rpc_idgen_proto_init() {
	if File_rpc_idgen_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_idgen_proto_rawDesc), len(file_rpc_idgen_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_idgen_proto_goTypes,
		DependencyIndexes: file_rpc_idgen_proto_depIdxs,
		EnumInfos:         file_rpc_idgen_proto_enumTypes,
		MessageInfos:      file_rpc_idgen_proto_msgTypes,
	}.Build()
	File_rpc_idgen_proto = out.File
	file_rpc_idgen_proto_goTypes = nil
	file_rpc_idgen_proto_depIdxs = nil
}
