// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: pkg/proto/svc/svc.proto

package svc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RawError      string                 `protobuf:"bytes,3,opt,name=rawError,proto3" json:"rawError,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResp) Reset() {
	*x = ErrorResp{}
	mi := &file_pkg_proto_svc_svc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResp) ProtoMessage() {}

func (x *ErrorResp) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_svc_svc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResp.ProtoReflect.Descriptor instead.
func (*ErrorResp) Descriptor() ([]byte, []int) {
	return file_pkg_proto_svc_svc_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ErrorResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorResp) GetRawError() string {
	if x != nil {
		return x.RawError
	}
	return ""
}

type UserGroupSync struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GroupIds      []uint64               `protobuf:"varint,2,rep,packed,name=group_ids,json=groupIds,proto3" json:"group_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserGroupSync) Reset() {
	*x = UserGroupSync{}
	mi := &file_pkg_proto_svc_svc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserGroupSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGroupSync) ProtoMessage() {}

func (x *UserGroupSync) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_svc_svc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGroupSync.ProtoReflect.Descriptor instead.
func (*UserGroupSync) Descriptor() ([]byte, []int) {
	return file_pkg_proto_svc_svc_proto_rawDescGZIP(), []int{1}
}

func (x *UserGroupSync) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserGroupSync) GetGroupIds() []uint64 {
	if x != nil {
		return x.GroupIds
	}
	return nil
}

type MessageSend struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MsgId          string                 `protobuf:"bytes,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	ClientId       string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ConversationId string                 `protobuf:"bytes,3,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Sender         uint64                 `protobuf:"varint,4,opt,name=sender,proto3" json:"sender,omitempty"`
	Target         uint64                 `protobuf:"varint,5,opt,name=target,proto3" json:"target,omitempty"`
	MsgType        int64                  `protobuf:"varint,6,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`
	Timestamp      int64                  `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Preview        string                 `protobuf:"bytes,8,opt,name=preview,proto3" json:"preview,omitempty"`
	Payload        []byte                 `protobuf:"bytes,9,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MessageSend) Reset() {
	*x = MessageSend{}
	mi := &file_pkg_proto_svc_svc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageSend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageSend) ProtoMessage() {}

func (x *MessageSend) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_svc_svc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageSend.ProtoReflect.Descriptor instead.
func (*MessageSend) Descriptor() ([]byte, []int) {
	return file_pkg_proto_svc_svc_proto_rawDescGZIP(), []int{2}
}

func (x *MessageSend) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *MessageSend) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *MessageSend) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *MessageSend) GetSender() uint64 {
	if x != nil {
		return x.Sender
	}
	return 0
}

func (x *MessageSend) GetTarget() uint64 {
	if x != nil {
		return x.Target
	}
	return 0
}

func (x *MessageSend) GetMsgType() int64 {
	if x != nil {
		return x.MsgType
	}
	return 0
}

func (x *MessageSend) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *MessageSend) GetPreview() string {
	if x != nil {
		return x.Preview
	}
	return ""
}

func (x *MessageSend) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_pkg_proto_svc_svc_proto protoreflect.FileDescriptor

const file_pkg_proto_svc_svc_proto_rawDesc = "" +
	"\n" +
	"\x17pkg/proto/svc/svc.proto\x12\x03svc\"U\n" +
	"\tErrorResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1a\n" +
	"\brawError\x18\x03 \x01(\tR\brawError\"E\n" +
	"\rUserGroupSync\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1b\n" +
	"\tgroup_ids\x18\x02 \x03(\x04R\bgroupIds\"\x87\x02\n" +
	"\vMessageSend\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\tR\x05msgId\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12'\n" +
	"\x0fconversation_id\x18\x03 \x01(\tR\x0econversationId\x12\x16\n" +
	"\x06sender\x18\x04 \x01(\x04R\x06sender\x12\x16\n" +
	"\x06target\x18\x05 \x01(\x04R\x06target\x12\x19\n" +
	"\bmsg_type\x18\x06 \x01(\x03R\amsgType\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestamp\x12\x18\n" +
	"\apreview\x18\b \x01(\tR\apreview\x12\x18\n" +
	"\apayload\x18\t \x01(\fR\apayloadB\x13Z\x11IM2/pkg/proto/svcb\x06proto3"

var (
	file_pkg_proto_svc_svc_proto_rawDescOnce sync.Once
	file_pkg_proto_svc_svc_proto_rawDescData []byte
)

func file_pkg_proto_svc_svc_proto_rawDescGZIP() []byte {
	file_pkg_proto_svc_svc_proto_rawDescOnce.Do(func() {
		file_pkg_proto_svc_svc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_svc_svc_proto_rawDesc), len(file_pkg_proto_svc_svc_proto_rawDesc)))
	})
	return file_pkg_proto_svc_svc_proto_rawDescData
}

var file_pkg_proto_svc_svc_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_proto_svc_svc_proto_goTypes = []any{
	(*ErrorResp)(nil),     // 0: svc.ErrorResp
	(*UserGroupSync)(nil), // 1: svc.UserGroupSync
	(*MessageSend)(nil),   // 2: svc.MessageSend
}
var file_pkg_proto_svc_svc_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_svc_svc_proto_init() }
func file_pkg_proto_svc_svc_proto_init() {
	if File_pkg_proto_svc_svc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_svc_svc_proto_rawDesc), len(file_pkg_proto_svc_svc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_svc_svc_proto_goTypes,
		DependencyIndexes: file_pkg_proto_svc_svc_proto_depIdxs,
		MessageInfos:      file_pkg_proto_svc_svc_proto_msgTypes,
	}.Build()
	File_pkg_proto_svc_svc_proto = out.File
	file_pkg_proto_svc_svc_proto_goTypes = nil
	file_pkg_proto_svc_svc_proto_depIdxs = nil
}
