// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package handler

import (
	"net/http"

	message "IM2/internal/apps/Message/api/handler/message"
	"IM2/internal/apps/Message/api/svc"
	"IM2/middleware"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.Use(middleware.WithRedisJwtAuth(serverCtx.TokenManager))
	server.AddRoutes(
		rest.WithMiddlewares([]rest.Middleware{
			middleware.WithRedisJwtAuth(serverCtx.TokenManager),
		}, []rest.Route{
			{
				// 更新会话设置
				Method:  http.MethodPut,
				Path:    "/conversation",
				Handler: message.UpdateConversationHandler(serverCtx),
			},
			{
				// 获取用户的会话列表(根据UserID)
				Method:  http.MethodGet,
				Path:    "/conversations/user",
				Handler: message.GetUserConversationsHandler(serverCtx),
			},
			{
				// 获取用户的活跃会话列表(根据UserID)
				Method:  http.MethodGet,
				Path:    "/conversations/user/active",
				Handler: message.GetUserActiveConversationsHandler(serverCtx),
			},
			{
				// 获取历史消息
				Method:  http.MethodGet,
				Path:    "/history",
				Handler: message.GetHistoryHandler(serverCtx),
			},
			{
				// 消息已读上报
				Method:  http.MethodPost,
				Path:    "/read",
				Handler: message.ReadMessageHandler(serverCtx),
			},
			{
				// 撤回消息
				Method:  http.MethodPost,
				Path:    "/recall",
				Handler: message.RecallMessageHandler(serverCtx),
			},
		}...),
		rest.WithPrefix("/message"),
	)
}
