// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type CreateGroupReq struct {
	Name      string   `json:"name"`
	Avatar    string   `json:"avatar,optional"`
	MemberIDs []uint64 `json:"member_ids,optional"` // 初始成员ID列表
}

type CreateGroupResp struct {
	Data Group `json:"data"`
}

type DismissGroupReq struct {
	GroupID    uint64 `json:"group_id"`
	OperatorID uint64 `json:"operator_id"`
}

type GetGroupMembersReq struct {
	GroupID uint64 `form:"group_id"`
}

type GetGroupMembersResp struct {
	Data []GroupMember `json:"data"`
}

type GetGroupReq struct {
	GroupIDs    []uint64 `form:"group_id,optional"`
	NameKeyword string   `form:"name_keyword,optional"`
	Limit       int      `form:"limit,optional,default=30"`
	Offset      int      `form:"offset,optional,default=0"`
}

type GetGroupResp struct {
	Data  []Group `json:"data"`
	Total int64   `json:"total"`
}

type GetPendingAppliesReq struct {
}

type GetPendingAppliesResp struct {
	Data []GroupRequest `json:"data"`
}

type GetUserGroupsReq struct {
}

type GetUserGroupsResp struct {
	Data []uint64 `json:"data"` // 群组ID列表
}

type Group struct {
	GroupID     uint64 `json:"id"`
	Name        string `json:"name"`
	Avatar      string `json:"avatar"`
	OwnerID     uint64 `json:"owner_id"`
	MemberCount int    `json:"member_count"`
	CreatedAt   int64  `json:"created_at"`
	UpdatedAt   int64  `json:"updated_at"`
}

type GroupMember struct {
	GroupID   uint64 `json:"group_id"`
	UserID    uint64 `json:"user_id"`
	Role      int8   `json:"role"` // 1:群主 2:管理员 3:普通成员
	Nickname  string `json:"nickname"`
	MuteUntil int64  `json:"mute_until"`
	JoinedAt  int64  `json:"joined_at"`
}

type GroupRequest struct {
	RequestID   string `json:"request_id"`
	SenderID    uint64 `json:"sender_id"`
	GroupID     uint64 `json:"group_id"`
	Message     string `json:"message"`
	Status      int    `json:"status"`               // 1:待处理 2:已同意 3:已拒绝 4:已忽略
	HandlerID   uint64 `json:"handler_id,omitempty"` // 处理人 ID
	RequestTime int64  `json:"request_time"`
	HandleTime  int64  `json:"handle_time"`
}

type HandleGroupApplyReq struct {
	ApplyID      string `json:"apply_id"`
	Result       int    `json:"result"` // 2:同意 3:拒绝
	OperatorID   uint64 `json:"operator_id"`
	RejectReason string `json:"reject_reason,optional"`
}

type InviteMembersReq struct {
	GroupID   uint64   `json:"group_id"`
	MemberIDs []uint64 `json:"member_ids"`
}

type InviteMembersResp struct {
	SuccessCount int      `json:"success_count"`
	FailedIDs    []uint64 `json:"failed_ids,omitempty"`
}

type JoinGroupReq struct {
	GroupID uint64 `json:"group_id"`
	Message string `json:"message,optional"`
}

type JoinGroupResp struct {
	Data GroupRequest `json:"data"`
}

type LeaveGroupReq struct {
	GroupID uint64 `json:"group_id"`
}

type MuteMemberReq struct {
	GroupID   uint64 `json:"group_id"`
	UserID    uint64 `json:"user_id"`
	MuteUntil int64  `json:"mute_until"` // 禁言截止时间戳，0表示解除禁言
}

type RemoveMemberReq struct {
	GroupID    uint64 `json:"group_id"`
	UserID     uint64 `json:"user_id"`
	OperatorID uint64 `json:"operator_id"`
}

type SetMemberNicknameReq struct {
	GroupID  uint64 `json:"group_id"`
	Nickname string `json:"nickname"`
}

type SetMemberRoleReq struct {
	GroupID    uint64 `json:"group_id"`
	UserID     uint64 `json:"user_id"`
	Role       int8   `json:"role"` // 2:管理员 3:普通成员
	OperatorID uint64 `json:"operator_id"`
}

type UpdateGroupReq struct {
	GroupID uint64 `json:"group_id"`
	Name    string `json:"name,optional"`
	Avatar  string `json:"avatar,optional"`
}
