// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: rpc/group.proto

package group

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GroupRpc_CreateGroup_FullMethodName       = "/group.GroupRpc/CreateGroup"
	GroupRpc_GetGroup_FullMethodName          = "/group.GroupRpc/GetGroup"
	GroupRpc_UpdateGroup_FullMethodName       = "/group.GroupRpc/UpdateGroup"
	GroupRpc_DismissGroup_FullMethodName      = "/group.GroupRpc/DismissGroup"
	GroupRpc_GetUserGroups_FullMethodName     = "/group.GroupRpc/GetUserGroups"
	GroupRpc_InviteMembers_FullMethodName     = "/group.GroupRpc/InviteMembers"
	GroupRpc_RemoveMember_FullMethodName      = "/group.GroupRpc/RemoveMember"
	GroupRpc_LeaveGroup_FullMethodName        = "/group.GroupRpc/LeaveGroup"
	GroupRpc_SetMemberRole_FullMethodName     = "/group.GroupRpc/SetMemberRole"
	GroupRpc_SetMemberNickname_FullMethodName = "/group.GroupRpc/SetMemberNickname"
	GroupRpc_MuteMember_FullMethodName        = "/group.GroupRpc/MuteMember"
	GroupRpc_GetGroupMemberIDs_FullMethodName = "/group.GroupRpc/GetGroupMemberIDs"
	GroupRpc_JoinGroup_FullMethodName         = "/group.GroupRpc/JoinGroup"
	GroupRpc_HandleGroupApply_FullMethodName  = "/group.GroupRpc/HandleGroupApply"
	GroupRpc_GetPendingApplies_FullMethodName = "/group.GroupRpc/GetPendingApplies"
)

// GroupRpcClient is the client API for GroupRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GroupRpcClient interface {
	// 群组管理
	CreateGroup(ctx context.Context, in *CreateGroupReq, opts ...grpc.CallOption) (*CreateGroupResp, error)
	GetGroup(ctx context.Context, in *GetGroupReq, opts ...grpc.CallOption) (*GetGroupResp, error)
	UpdateGroup(ctx context.Context, in *UpdateGroupReq, opts ...grpc.CallOption) (*EmptyResp, error)
	DismissGroup(ctx context.Context, in *DismissGroupReq, opts ...grpc.CallOption) (*EmptyResp, error)
	GetUserGroups(ctx context.Context, in *GetUserGroupsReq, opts ...grpc.CallOption) (*GetUserGroupsResp, error)
	// 群成员管理
	InviteMembers(ctx context.Context, in *InviteMembersReq, opts ...grpc.CallOption) (*InviteMembersResp, error)
	RemoveMember(ctx context.Context, in *RemoveMemberReq, opts ...grpc.CallOption) (*EmptyResp, error)
	LeaveGroup(ctx context.Context, in *LeaveGroupReq, opts ...grpc.CallOption) (*EmptyResp, error)
	SetMemberRole(ctx context.Context, in *SetMemberRoleReq, opts ...grpc.CallOption) (*EmptyResp, error)
	SetMemberNickname(ctx context.Context, in *SetMemberNicknameReq, opts ...grpc.CallOption) (*EmptyResp, error)
	MuteMember(ctx context.Context, in *MuteMemberReq, opts ...grpc.CallOption) (*EmptyResp, error)
	GetGroupMemberIDs(ctx context.Context, in *GetGroupMemberIDsReq, opts ...grpc.CallOption) (*GetGroupMemberIDsResp, error)
	// 群申请管理
	JoinGroup(ctx context.Context, in *JoinGroupReq, opts ...grpc.CallOption) (*JoinGroupResp, error)
	HandleGroupApply(ctx context.Context, in *HandleGroupApplyReq, opts ...grpc.CallOption) (*EmptyResp, error)
	GetPendingApplies(ctx context.Context, in *GetPendingAppliesReq, opts ...grpc.CallOption) (*GetPendingAppliesResp, error)
}

type groupRpcClient struct {
	cc grpc.ClientConnInterface
}

func NewGroupRpcClient(cc grpc.ClientConnInterface) GroupRpcClient {
	return &groupRpcClient{cc}
}

func (c *groupRpcClient) CreateGroup(ctx context.Context, in *CreateGroupReq, opts ...grpc.CallOption) (*CreateGroupResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateGroupResp)
	err := c.cc.Invoke(ctx, GroupRpc_CreateGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupRpcClient) GetGroup(ctx context.Context, in *GetGroupReq, opts ...grpc.CallOption) (*GetGroupResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGroupResp)
	err := c.cc.Invoke(ctx, GroupRpc_GetGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupRpcClient) UpdateGroup(ctx context.Context, in *UpdateGroupReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResp)
	err := c.cc.Invoke(ctx, GroupRpc_UpdateGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupRpcClient) DismissGroup(ctx context.Context, in *DismissGroupReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResp)
	err := c.cc.Invoke(ctx, GroupRpc_DismissGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupRpcClient) GetUserGroups(ctx context.Context, in *GetUserGroupsReq, opts ...grpc.CallOption) (*GetUserGroupsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserGroupsResp)
	err := c.cc.Invoke(ctx, GroupRpc_GetUserGroups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupRpcClient) InviteMembers(ctx context.Context, in *InviteMembersReq, opts ...grpc.CallOption) (*InviteMembersResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InviteMembersResp)
	err := c.cc.Invoke(ctx, GroupRpc_InviteMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupRpcClient) RemoveMember(ctx context.Context, in *RemoveMemberReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResp)
	err := c.cc.Invoke(ctx, GroupRpc_RemoveMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupRpcClient) LeaveGroup(ctx context.Context, in *LeaveGroupReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResp)
	err := c.cc.Invoke(ctx, GroupRpc_LeaveGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupRpcClient) SetMemberRole(ctx context.Context, in *SetMemberRoleReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResp)
	err := c.cc.Invoke(ctx, GroupRpc_SetMemberRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupRpcClient) SetMemberNickname(ctx context.Context, in *SetMemberNicknameReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResp)
	err := c.cc.Invoke(ctx, GroupRpc_SetMemberNickname_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupRpcClient) MuteMember(ctx context.Context, in *MuteMemberReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResp)
	err := c.cc.Invoke(ctx, GroupRpc_MuteMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupRpcClient) GetGroupMemberIDs(ctx context.Context, in *GetGroupMemberIDsReq, opts ...grpc.CallOption) (*GetGroupMemberIDsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGroupMemberIDsResp)
	err := c.cc.Invoke(ctx, GroupRpc_GetGroupMemberIDs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupRpcClient) JoinGroup(ctx context.Context, in *JoinGroupReq, opts ...grpc.CallOption) (*JoinGroupResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinGroupResp)
	err := c.cc.Invoke(ctx, GroupRpc_JoinGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupRpcClient) HandleGroupApply(ctx context.Context, in *HandleGroupApplyReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResp)
	err := c.cc.Invoke(ctx, GroupRpc_HandleGroupApply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupRpcClient) GetPendingApplies(ctx context.Context, in *GetPendingAppliesReq, opts ...grpc.CallOption) (*GetPendingAppliesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPendingAppliesResp)
	err := c.cc.Invoke(ctx, GroupRpc_GetPendingApplies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GroupRpcServer is the server API for GroupRpc service.
// All implementations must embed UnimplementedGroupRpcServer
// for forward compatibility.
type GroupRpcServer interface {
	// 群组管理
	CreateGroup(context.Context, *CreateGroupReq) (*CreateGroupResp, error)
	GetGroup(context.Context, *GetGroupReq) (*GetGroupResp, error)
	UpdateGroup(context.Context, *UpdateGroupReq) (*EmptyResp, error)
	DismissGroup(context.Context, *DismissGroupReq) (*EmptyResp, error)
	GetUserGroups(context.Context, *GetUserGroupsReq) (*GetUserGroupsResp, error)
	// 群成员管理
	InviteMembers(context.Context, *InviteMembersReq) (*InviteMembersResp, error)
	RemoveMember(context.Context, *RemoveMemberReq) (*EmptyResp, error)
	LeaveGroup(context.Context, *LeaveGroupReq) (*EmptyResp, error)
	SetMemberRole(context.Context, *SetMemberRoleReq) (*EmptyResp, error)
	SetMemberNickname(context.Context, *SetMemberNicknameReq) (*EmptyResp, error)
	MuteMember(context.Context, *MuteMemberReq) (*EmptyResp, error)
	GetGroupMemberIDs(context.Context, *GetGroupMemberIDsReq) (*GetGroupMemberIDsResp, error)
	// 群申请管理
	JoinGroup(context.Context, *JoinGroupReq) (*JoinGroupResp, error)
	HandleGroupApply(context.Context, *HandleGroupApplyReq) (*EmptyResp, error)
	GetPendingApplies(context.Context, *GetPendingAppliesReq) (*GetPendingAppliesResp, error)
	mustEmbedUnimplementedGroupRpcServer()
}

// UnimplementedGroupRpcServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGroupRpcServer struct{}

func (UnimplementedGroupRpcServer) CreateGroup(context.Context, *CreateGroupReq) (*CreateGroupResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGroup not implemented")
}
func (UnimplementedGroupRpcServer) GetGroup(context.Context, *GetGroupReq) (*GetGroupResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGroup not implemented")
}
func (UnimplementedGroupRpcServer) UpdateGroup(context.Context, *UpdateGroupReq) (*EmptyResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateGroup not implemented")
}
func (UnimplementedGroupRpcServer) DismissGroup(context.Context, *DismissGroupReq) (*EmptyResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DismissGroup not implemented")
}
func (UnimplementedGroupRpcServer) GetUserGroups(context.Context, *GetUserGroupsReq) (*GetUserGroupsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserGroups not implemented")
}
func (UnimplementedGroupRpcServer) InviteMembers(context.Context, *InviteMembersReq) (*InviteMembersResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InviteMembers not implemented")
}
func (UnimplementedGroupRpcServer) RemoveMember(context.Context, *RemoveMemberReq) (*EmptyResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveMember not implemented")
}
func (UnimplementedGroupRpcServer) LeaveGroup(context.Context, *LeaveGroupReq) (*EmptyResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LeaveGroup not implemented")
}
func (UnimplementedGroupRpcServer) SetMemberRole(context.Context, *SetMemberRoleReq) (*EmptyResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetMemberRole not implemented")
}
func (UnimplementedGroupRpcServer) SetMemberNickname(context.Context, *SetMemberNicknameReq) (*EmptyResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetMemberNickname not implemented")
}
func (UnimplementedGroupRpcServer) MuteMember(context.Context, *MuteMemberReq) (*EmptyResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MuteMember not implemented")
}
func (UnimplementedGroupRpcServer) GetGroupMemberIDs(context.Context, *GetGroupMemberIDsReq) (*GetGroupMemberIDsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGroupMemberIDs not implemented")
}
func (UnimplementedGroupRpcServer) JoinGroup(context.Context, *JoinGroupReq) (*JoinGroupResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinGroup not implemented")
}
func (UnimplementedGroupRpcServer) HandleGroupApply(context.Context, *HandleGroupApplyReq) (*EmptyResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleGroupApply not implemented")
}
func (UnimplementedGroupRpcServer) GetPendingApplies(context.Context, *GetPendingAppliesReq) (*GetPendingAppliesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPendingApplies not implemented")
}
func (UnimplementedGroupRpcServer) mustEmbedUnimplementedGroupRpcServer() {}
func (UnimplementedGroupRpcServer) testEmbeddedByValue()                  {}

// UnsafeGroupRpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GroupRpcServer will
// result in compilation errors.
type UnsafeGroupRpcServer interface {
	mustEmbedUnimplementedGroupRpcServer()
}

func RegisterGroupRpcServer(s grpc.ServiceRegistrar, srv GroupRpcServer) {
	// If the following call pancis, it indicates UnimplementedGroupRpcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GroupRpc_ServiceDesc, srv)
}

func _GroupRpc_CreateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupRpcServer).CreateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupRpc_CreateGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupRpcServer).CreateGroup(ctx, req.(*CreateGroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupRpc_GetGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupRpcServer).GetGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupRpc_GetGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupRpcServer).GetGroup(ctx, req.(*GetGroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupRpc_UpdateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupRpcServer).UpdateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupRpc_UpdateGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupRpcServer).UpdateGroup(ctx, req.(*UpdateGroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupRpc_DismissGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DismissGroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupRpcServer).DismissGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupRpc_DismissGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupRpcServer).DismissGroup(ctx, req.(*DismissGroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupRpc_GetUserGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserGroupsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupRpcServer).GetUserGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupRpc_GetUserGroups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupRpcServer).GetUserGroups(ctx, req.(*GetUserGroupsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupRpc_InviteMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InviteMembersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupRpcServer).InviteMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupRpc_InviteMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupRpcServer).InviteMembers(ctx, req.(*InviteMembersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupRpc_RemoveMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveMemberReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupRpcServer).RemoveMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupRpc_RemoveMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupRpcServer).RemoveMember(ctx, req.(*RemoveMemberReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupRpc_LeaveGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaveGroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupRpcServer).LeaveGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupRpc_LeaveGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupRpcServer).LeaveGroup(ctx, req.(*LeaveGroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupRpc_SetMemberRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetMemberRoleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupRpcServer).SetMemberRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupRpc_SetMemberRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupRpcServer).SetMemberRole(ctx, req.(*SetMemberRoleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupRpc_SetMemberNickname_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetMemberNicknameReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupRpcServer).SetMemberNickname(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupRpc_SetMemberNickname_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupRpcServer).SetMemberNickname(ctx, req.(*SetMemberNicknameReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupRpc_MuteMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MuteMemberReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupRpcServer).MuteMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupRpc_MuteMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupRpcServer).MuteMember(ctx, req.(*MuteMemberReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupRpc_GetGroupMemberIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGroupMemberIDsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupRpcServer).GetGroupMemberIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupRpc_GetGroupMemberIDs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupRpcServer).GetGroupMemberIDs(ctx, req.(*GetGroupMemberIDsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupRpc_JoinGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinGroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupRpcServer).JoinGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupRpc_JoinGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupRpcServer).JoinGroup(ctx, req.(*JoinGroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupRpc_HandleGroupApply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleGroupApplyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupRpcServer).HandleGroupApply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupRpc_HandleGroupApply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupRpcServer).HandleGroupApply(ctx, req.(*HandleGroupApplyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupRpc_GetPendingApplies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPendingAppliesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupRpcServer).GetPendingApplies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupRpc_GetPendingApplies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupRpcServer).GetPendingApplies(ctx, req.(*GetPendingAppliesReq))
	}
	return interceptor(ctx, in, info, handler)
}

// GroupRpc_ServiceDesc is the grpc.ServiceDesc for GroupRpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GroupRpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "group.GroupRpc",
	HandlerType: (*GroupRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateGroup",
			Handler:    _GroupRpc_CreateGroup_Handler,
		},
		{
			MethodName: "GetGroup",
			Handler:    _GroupRpc_GetGroup_Handler,
		},
		{
			MethodName: "UpdateGroup",
			Handler:    _GroupRpc_UpdateGroup_Handler,
		},
		{
			MethodName: "DismissGroup",
			Handler:    _GroupRpc_DismissGroup_Handler,
		},
		{
			MethodName: "GetUserGroups",
			Handler:    _GroupRpc_GetUserGroups_Handler,
		},
		{
			MethodName: "InviteMembers",
			Handler:    _GroupRpc_InviteMembers_Handler,
		},
		{
			MethodName: "RemoveMember",
			Handler:    _GroupRpc_RemoveMember_Handler,
		},
		{
			MethodName: "LeaveGroup",
			Handler:    _GroupRpc_LeaveGroup_Handler,
		},
		{
			MethodName: "SetMemberRole",
			Handler:    _GroupRpc_SetMemberRole_Handler,
		},
		{
			MethodName: "SetMemberNickname",
			Handler:    _GroupRpc_SetMemberNickname_Handler,
		},
		{
			MethodName: "MuteMember",
			Handler:    _GroupRpc_MuteMember_Handler,
		},
		{
			MethodName: "GetGroupMemberIDs",
			Handler:    _GroupRpc_GetGroupMemberIDs_Handler,
		},
		{
			MethodName: "JoinGroup",
			Handler:    _GroupRpc_JoinGroup_Handler,
		},
		{
			MethodName: "HandleGroupApply",
			Handler:    _GroupRpc_HandleGroupApply_Handler,
		},
		{
			MethodName: "GetPendingApplies",
			Handler:    _GroupRpc_GetPendingApplies_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc/group.proto",
}
